import {communityEvidence,investigationDigest,profilePosterior,updateProfile} from './evidence.mjs';
import {collectAdapterEvidence,createSourceAdapters} from './source-adapters.mjs';
import {assessCandidate,calibrationReport,historicalContext,DEFAULT_INVESTIGATION_POLICY} from './scoring.mjs';

const MIN=60000,H=3600000,DAY=86400000;
const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));
const mean=a=>a.length?a.reduce((n,x)=>n+x,0)/a.length:null;
const quantile=(a,p)=>{if(!a.length)return null;const s=[...a].sort((x,y)=>x-y),i=Math.min(s.length-1,Math.floor((s.length-1)*p));return s[i];};
function ensureState(state){
 state.investigation ||= {version:1,cases:[],evidence:[],decisions:[],incidents:[],missed:[],sourceProfiles:{},reporterProfiles:{},outcomes:[],policy:structuredClone(DEFAULT_INVESTIGATION_POLICY),modelRegistry:{champion:{id:'investigation_rules_v1',version:1,status:'PRODUCTION'},challengers:[{id:'empirical_similar_cases_v1',version:1,status:'SHADOW_MODE'}]}};
 const s=state.investigation;s.cases||=[];s.evidence||=[];s.decisions||=[];s.incidents||=[];s.missed||=[];s.sourceProfiles||={};s.reporterProfiles||={};s.outcomes||=[];s.policy||=structuredClone(DEFAULT_INVESTIGATION_POLICY);s.modelRegistry||={champion:{id:'investigation_rules_v1',version:1,status:'PRODUCTION'},challengers:[{id:'empirical_similar_cases_v1',version:1,status:'SHADOW_MODE'}]};return s;
}
function addTimeline(c,type,data={},at=Date.now()){c.timeline||=[];const fingerprint=investigationDigest(JSON.stringify([type,at,...Object.entries(data).flat()]));if(c.timeline.some(x=>x.fingerprint===fingerprint))return;c.timeline.push({at,type,...data,fingerprint});if(c.timeline.length>300)c.timeline.splice(0,c.timeline.length-300);}
function upsertEvidence(store,row){const old=store.find(x=>x.id===row.id);if(old){Object.assign(old,row);return {row:old,added:false};}store.push(row);return {row,added:true};}
function caseEvidence(inv,c){const ids=new Set(c.evidenceIds||[]);return inv.evidence.filter(x=>ids.has(x.id));}
function coverageAround(state,at,windowMs=15*MIN){
 if(!Number.isFinite(at))return null;const start=at-windowMs,end=at+windowMs,segments=state.whatsapp?.coverageSegments||[],covered=segments.reduce((n,x)=>n+Math.max(0,Math.min(end,x.endAt)-Math.max(start,x.startAt)),0);return clamp(100*covered/(end-start),0,100);
}
function publicEvidence(e){return {id:e.id,type:e.type,sourceId:e.sourceId,sourceKind:e.sourceKind,boss:e.boss,world:e.world,observedAt:e.observedAt,receivedAt:e.receivedAt,estimatedAt:e.estimatedAt,authorHash:e.authorHash?e.authorHash.slice(0,12):null,reliability:Math.round((e.reliability||0)*1000)/10,sampleSize:e.sampleSize||0,freshness:Math.round((e.freshness||0)*1000)/10,evidenceStrength:Math.round((e.evidenceStrength||0)*1000)/10,positive:!!e.positive,negative:!!e.negative,canConfirm:e.canConfirm!==false,sourceHealth:e.sourceHealth,detail:e.detail||null};}
function evidenceGraph(c,evidence){const nodes=[{id:c.id,type:'CANDIDATE',label:c.boss}];const edges=[];for(const e of evidence){const eid=e.id;nodes.push({id:eid,type:e.type,label:e.sourceId+(e.authorHash?' #'+e.authorHash.slice(0,6):'')});edges.push({from:c.id,to:eid,kind:e.canConfirm===false?'CONTEXT':'EVIDENCE',independenceKey:e.independenceKey||null});}return {nodes,edges};}
function similarCases(inv,c,limit=12){
 const rows=inv.decisions.filter(x=>x.boss===c.boss&&x.world===c.world&&x.candidateId!==c.candidateId).sort((a,b)=>Math.abs((a.rawScore||0)-(c.rawScore||0))-Math.abs((b.rawScore||0)-(c.rawScore||0))).slice(0,limit);return {samples:rows.length,confirmed:rows.filter(x=>x.outcome==='CONFIRMED').length,rejected:rows.filter(x=>x.outcome==='REJECTED').length,cases:rows.map(x=>({candidateId:x.candidateId,outcome:x.outcome,rawScore:x.rawScore,decidedAt:x.decidedAt}))};
}
function shadowModel(inv,c){
 let rows=inv.decisions.filter(x=>x.boss===c.boss&&x.world===c.world&&Number.isFinite(x.rawScore));let scope='boss';if(rows.length<30){rows=inv.decisions.filter(x=>Number.isFinite(x.rawScore));scope='global';}
 if(rows.length<(scope==='boss'?30:50))return {id:'empirical_similar_cases_v1',status:'SHADOW_MODE',prediction:null,samples:rows.length,reason:'INSUFFICIENT_DATA',scope};
 const nearest=rows.filter(x=>Math.abs(x.rawScore-c.rawScore)<=10);if(nearest.length<20)return {id:'empirical_similar_cases_v1',status:'SHADOW_MODE',prediction:null,samples:nearest.length,reason:'INSUFFICIENT_SIMILAR_CASES',scope};
 return {id:'empirical_similar_cases_v1',status:'SHADOW_MODE',prediction:Math.round(1000*nearest.filter(x=>x.outcome==='CONFIRMED').length/nearest.length)/10,samples:nearest.length,reason:'EMPIRICAL_SIMILAR_CASES',scope};
}
function profileView(store,outcomes,kind){
 return Object.entries(store).map(([id,p])=>{const post=profilePosterior(p),rows=outcomes.filter(x=>x[kind]===id),recent=rows.slice(-30),prior=rows.slice(0,-recent.length),ra=recent.length?recent.filter(x=>x.correct).length/recent.length:null,pa=prior.length?prior.filter(x=>x.correct).length/prior.length:null,drift=recent.length>=8&&prior.length>=12&&pa-ra>=.2;return {id:kind==='authorHash'?id.slice(0,12):id,reliability:Math.round(post.value*1000)/10,samples:post.samples,recentSamples:recent.length,recentAccuracy:ra==null?null:Math.round(ra*1000)/10,historicalAccuracy:pa==null?null:Math.round(pa*1000)/10,drift,driftDelta:drift?Math.round((pa-ra)*1000)/10:null,bossSpecialties:Object.entries(p.byBoss||{}).map(([boss,b])=>{const x=profilePosterior({byBoss:{[boss]:b}},boss);return {boss,reliability:Math.round(x.value*1000)/10,samples:x.samples};}).filter(x=>x.samples>=3).sort((a,b)=>b.samples-a.samples).slice(0,8)};}).sort((a,b)=>b.samples-a.samples);
}
function timingMetrics(decisions){
 const detected=decisions.filter(x=>x.outcome==='CONFIRMED'&&Number.isFinite(x.finalEventAt)&&Number.isFinite(x.firstDetectionAt)).map(x=>Math.max(0,x.firstDetectionAt-x.finalEventAt)),investigate=decisions.filter(x=>Number.isFinite(x.investigationCompletedAt)&&Number.isFinite(x.firstDetectionAt)).map(x=>Math.max(0,x.investigationCompletedAt-x.firstDetectionAt)),confirm=decisions.filter(x=>x.outcome==='CONFIRMED'&&Number.isFinite(x.decidedAt)&&Number.isFinite(x.firstDetectionAt)).map(x=>Math.max(0,x.decidedAt-x.firstDetectionAt));const pack=a=>({samples:a.length,meanMs:mean(a),p50Ms:quantile(a,.5),p95Ms:quantile(a,.95)});return {timeToDetect:pack(detected),timeToInvestigate:pack(investigate),timeToConfirm:pack(confirm)};
}
function backtestFromSnapshots(inv){
 const rows=inv.decisions.filter(x=>x.snapshot&&['CONFIRMED','REJECTED'].includes(x.outcome)),recommended=rows.filter(x=>x.recommendation==='CONFIRM_RECOMMENDED'),correctRec=recommended.filter(x=>x.outcome==='CONFIRMED').length,high=rows.filter(x=>(x.rawScore||0)>=70),falsePositive=high.filter(x=>x.outcome==='REJECTED').length;
 const calibrated=rows.filter(x=>Number.isFinite(x.calibratedConfidence));const brier=calibrated.length?calibrated.reduce((n,x)=>{const p=x.calibratedConfidence/100,y=x.outcome==='CONFIRMED'?1:0;return n+(p-y)*(p-y);},0)/calibrated.length:null;
 return {temporal:true,note:'Usa somente o snapshot imutável salvo no momento da decisão; nenhuma evidência posterior é recalculada.',samples:rows.length,confirmRecommendations:recommended.length,confirmRecommendationAccuracy:recommended.length?Math.round(correctRec/recommended.length*1000)/10:null,highConfidenceSamples:high.length,falsePositiveRate:high.length?Math.round(falsePositive/high.length*1000)/10:null,brier:brier==null?null:Math.round(brier*10000)/10000};
}
function publicCase(inv,c){const evidence=caseEvidence(inv,c),{candidateSnapshot,evidenceIds,...safe}=c;return {...safe,evidenceCount:(evidenceIds||[]).length,evidence:evidence.map(publicEvidence),graph:evidenceGraph(c,evidence),timeline:(c.timeline||[]).map(({fingerprint,...x})=>x)};}

export function createInvestigationEngine({state,persist,broadcast,getSnapshot,refreshSources=async()=>{},now=()=>Date.now()}){
 const inv=ensureState(state);
 async function investigate(candidate,{forceSources=false}={}){
  if(!candidate?.id||!candidate.boss||!candidate.world)throw new Error('CandidateBossEvent inválido para investigação');
  const at=now();let c=inv.cases.find(x=>x.candidateId===candidate.id),created=false;if(!c){const prior=inv.cases.find(x=>x.status==='EXPIRED'&&x.boss===candidate.boss&&x.world===candidate.world&&at-(x.lastEvidenceAt||x.updatedAt||0)<=6*H);c={id:'investigation-'+investigationDigest(candidate.id).slice(0,24),candidateId:candidate.id,boss:candidate.boss,world:candidate.world,status:prior?'REOPENED':'ACTIVE',reopenedFromCandidateId:prior?.candidateId||null,createdAt:at,updatedAt:at,evidenceIds:[],timeline:[],confidenceHistory:[],investigationModeUntil:at+5*MIN,lastSourceCheckAt:null,originalDetected:{boss:candidate.boss,world:candidate.world,estimatedAt:candidate.estimatedAt||candidate.firstEvidenceAt||null}};inv.cases.unshift(c);created=true;addTimeline(c,prior?'INVESTIGATION_REOPENED':'INVESTIGATION_STARTED',prior?{candidateId:candidate.id,previousCandidateId:prior.candidateId}:{candidateId:candidate.id},at);}else if(c.status==='EXPIRED'){c.status='REOPENED';c.investigationModeUntil=at+5*MIN;addTimeline(c,'INVESTIGATION_REOPENED',{},at);}
  c.candidateSnapshot={id:candidate.id,boss:candidate.boss,world:candidate.world,estimatedAt:candidate.estimatedAt||candidate.firstEvidenceAt||null,firstEvidenceAt:candidate.firstEvidenceAt,lastEvidenceAt:candidate.lastEvidenceAt,evidence:(candidate.evidence||[]).map(x=>({id:x.id,bossCandidates:x.bossCandidates,contextClassification:x.contextClassification,messageTimestamp:x.messageTimestamp,capturedTimestamp:x.capturedTimestamp,receivedAt:x.receivedAt,authorHash:x.authorHash,reporter:x.reporter,textHash:investigationDigest(String(x.text||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()).slice(0,20)}))};
  let newEvidence=0;for(const e of communityEvidence(candidate,inv.reporterProfiles,at)){const r=upsertEvidence(inv.evidence,e);if(!c.evidenceIds.includes(e.id))c.evidenceIds.push(e.id);if(r.added){newEvidence++;addTimeline(c,'EVIDENCE_ADDED',{evidenceId:e.id,type:e.type,sourceId:e.sourceId},e.receivedAt||at);}}
  let safeFailure=false,sourceError=null,snapshot=getSnapshot(candidate.world);
  const shouldRefresh=forceSources||!c.lastSourceCheckAt||at-c.lastSourceCheckAt>=MIN;
  if(shouldRefresh){try{await refreshSources(candidate);c.lastSourceCheckAt=at;addTimeline(c,'SOURCE_CROSS_CHECK',{status:'COMPLETED'},at);}catch(e){safeFailure=true;sourceError=String(e?.message||e).slice(0,240);addTimeline(c,'SOURCE_CROSS_CHECK',{status:'ERROR',error:sourceError},at);}snapshot=getSnapshot(candidate.world);}
  const collected=collectAdapterEvidence(candidate,snapshot,at);for(const e of collected.evidence){const r=upsertEvidence(inv.evidence,e);if(!c.evidenceIds.includes(e.id))c.evidenceIds.push(e.id);if(r.added){newEvidence++;addTimeline(c,'EVIDENCE_ADDED',{evidenceId:e.id,type:e.type,sourceId:e.sourceId},e.receivedAt||at);}}
  const history=historicalContext(candidate,snapshot),coveragePct=state.whatsapp?(()=>{const cov=state.whatsapp.coverageSegments||[],start=at-DAY,covered=cov.reduce((n,x)=>n+Math.max(0,Math.min(at,x.endAt)-Math.max(start,x.startAt)),0);return Math.round(clamp(100*covered/DAY,0,100)*10)/10;})():null;
  const histId='inv-history-'+c.id,historyEvidence={id:histId,candidateId:candidate.id,type:'HISTORICAL_SIGNAL',sourceId:'historical-analysis',sourceKind:'model-context',boss:candidate.boss,world:candidate.world,observedAt:at,receivedAt:at,estimatedAt:null,independenceKey:null,reliability:history.plausibility,sampleSize:history.samples,freshness:1,evidenceStrength:history.plausibility,positive:false,negative:false,canConfirm:false,sourceHealth:'HEALTHY',detail:{lastEventAt:history.lastEventAt,intervalMs:history.intervalMs,anomaly:history.anomaly}};upsertEvidence(inv.evidence,historyEvidence);if(!c.evidenceIds.includes(histId))c.evidenceIds.push(histId);
  if(history.prediction){const id='inv-model-'+c.id,row={id,candidateId:candidate.id,type:'MODEL_SIGNAL',sourceId:'prediction-engine',sourceKind:'model-context',boss:candidate.boss,world:candidate.world,observedAt:at,receivedAt:at,estimatedAt:null,independenceKey:null,reliability:0,sampleSize:0,freshness:1,evidenceStrength:0,positive:false,negative:false,canConfirm:false,sourceHealth:'HEALTHY',detail:{prediction:history.prediction,compatibility:history.predictionCompatibility}};upsertEvidence(inv.evidence,row);if(!c.evidenceIds.includes(id))c.evidenceIds.push(id);}
  const evidence=caseEvidence(inv,c),assessment=assessCandidate({evidence,history,coveragePct,decisions:inv.decisions,policy:inv.policy,safeFailure});const previousScore=c.rawScore;
  Object.assign(c,{updatedAt:at,lastEvidenceAt:candidate.lastEvidenceAt||at,firstEvidenceAt:candidate.firstEvidenceAt||c.firstEvidenceAt||at,firstDetectionAt:evidence.filter(x=>x.positive&&Number.isFinite(x.observedAt)).sort((a,b)=>a.observedAt-b.observedAt)[0]?.observedAt||c.firstEvidenceAt,firstDetectionSource:evidence.filter(x=>x.positive&&Number.isFinite(x.observedAt)).sort((a,b)=>a.observedAt-b.observedAt)[0]?.sourceId||null,rawScore:assessment.rawScore,calibratedConfidence:assessment.calibration.value,calibrationStatus:assessment.calibration.status,calibrationSamples:assessment.calibration.samples,recommendation:safeFailure?'REVIEW_RECOMMENDED':assessment.recommendation,consensus:assessment.consensus,historicalPlausibility:Math.round(history.plausibility*1000)/10,anomaly:history.anomaly,predictionCompatibility:history.predictionCompatibility,factors:assessment.factors,coveragePct,sourceError,investigationCompletedAt:at,policyVersion:assessment.policyVersion});
  if(c.status==='WAITING'&&newEvidence)c.status='REOPENED';if(safeFailure)c.status='MANUAL_REVIEW_REQUIRED';else if(!['EXPIRED','CONFIRMED','CONFIRMED_LATE','REJECTED','REOPENED','WAITING'].includes(c.status))c.status='ACTIVE';
  if(previousScore!==c.rawScore){c.confidenceHistory.push({at,rawScore:c.rawScore,calibratedConfidence:c.calibratedConfidence,evidenceCount:evidence.length});if(c.confidenceHistory.length>200)c.confidenceHistory.splice(0,c.confidenceHistory.length-200);addTimeline(c,'CONFIDENCE_UPDATED',{from:previousScore??null,to:c.rawScore,calibrated:c.calibratedConfidence??null},at);}
  c.similarCases=similarCases(inv,c);c.shadowModel=shadowModel(inv,c);c.sourceHealth=collected.adapters.map(a=>({id:a.id,status:a.getSourceHealth(),reliability:Math.round(a.getReliability().value*1000)/10,samples:a.getReliability().samples,latency:a.getLatency()}));
  if(created||newEvidence)addTimeline(c,'DOSSIER_UPDATED',{recommendation:c.recommendation,rawScore:c.rawScore},at);
  inv.cases=inv.cases.slice(0,5000);inv.evidence=inv.evidence.slice(-50000);await persist();broadcast('update',{kind:'investigation',candidateId:candidate.id});return publicCase(inv,c);
 }
 async function recordDecision(candidate,{outcome,finalBoss=null,finalAt=null,reason=''}={}){
  if(!['CONFIRMED','REJECTED'].includes(outcome))throw new Error('Decisão investigativa inválida');let c=inv.cases.find(x=>x.candidateId===candidate.id);if(!c)c=(await investigate(candidate,{forceSources:false}));
  if(c.evidence)c=inv.cases.find(x=>x.candidateId===candidate.id);const at=now(),evidence=caseEvidence(inv,c),decision={id:'decision-'+investigationDigest([c.candidateId,at,outcome].join('|')).slice(0,24),candidateId:c.candidateId,boss:c.boss,world:c.world,outcome,decidedAt:at,firstDetectionAt:c.firstDetectionAt||null,investigationCompletedAt:c.investigationCompletedAt||null,finalBoss:finalBoss||c.boss,finalEventAt:Number(finalAt)||null,reason:String(reason||'').slice(0,300),rawScore:c.rawScore,calibratedConfidence:c.calibratedConfidence,recommendation:c.recommendation,snapshot:{rawScore:c.rawScore,calibratedConfidence:c.calibratedConfidence,recommendation:c.recommendation,consensus:c.consensus,historicalPlausibility:c.historicalPlausibility,anomaly:c.anomaly,predictionCompatibility:c.predictionCompatibility,factors:c.factors,shadowModel:c.shadowModel,evidence:evidence.map(publicEvidence)}};
  inv.decisions.unshift(decision);if(inv.decisions.length>20000)inv.decisions.length=20000;
  for(const e of evidence.filter(x=>x.canConfirm!==false&&(x.positive||x.negative))){const correct=outcome==='CONFIRMED'?!!e.positive:!!e.negative,weight=Math.max(.1,Math.min(1,e.evidenceStrength||.1));updateProfile(inv.sourceProfiles,e.sourceId,c.boss,correct,weight,at);if(e.authorHash)updateProfile(inv.reporterProfiles,e.authorHash,c.boss,correct,weight,at);inv.outcomes.push({at,candidateId:c.candidateId,boss:c.boss,sourceId:e.sourceId,authorHash:e.authorHash||null,correct,weight});}
  if(inv.outcomes.length>50000)inv.outcomes.splice(0,inv.outcomes.length-50000);
  c.finalValidated={boss:decision.finalBoss,at:decision.finalEventAt};c.decisionId=decision.id;c.decidedAt=at;c.status=outcome==='CONFIRMED'&&c.firstDetectionAt&&decision.finalEventAt&&c.firstDetectionAt-decision.finalEventAt>30*MIN?'CONFIRMED_LATE':outcome;addTimeline(c,'HUMAN_DECISION',{outcome,candidateId:c.candidateId,finalBoss:decision.finalBoss,finalAt:decision.finalEventAt},at);
  if(outcome==='REJECTED'&&(c.recommendation==='CONFIRM_RECOMMENDED'||c.rawScore>=85)){inv.incidents.unshift({id:'incident-'+investigationDigest(decision.id).slice(0,20),candidateId:c.candidateId,at,kind:'HIGH_CONFIDENCE_FALSE_POSITIVE',rawScore:c.rawScore,recommendation:c.recommendation,possibleCauses:evidence.filter(x=>x.positive).map(x=>x.sourceId).slice(0,10)});inv.incidents=inv.incidents.slice(0,2000);}
  await persist();broadcast('update',{kind:'investigation-decision',candidateId:c.candidateId});return decision;
 }
 async function wait(candidateId){const c=inv.cases.find(x=>x.candidateId===candidateId);if(!c)throw new Error('Investigação não encontrada');if(['CONFIRMED','CONFIRMED_LATE','REJECTED'].includes(c.status))throw new Error('Investigação já finalizada');c.status='WAITING';addTimeline(c,'HUMAN_WAIT',{},now());await persist();broadcast('update',{kind:'investigation',candidateId});return publicCase(inv,c);}
 async function tick(){
  const at=now();for(const c of inv.cases.filter(x=>!['CONFIRMED','CONFIRMED_LATE','REJECTED','EXPIRED'].includes(x.status))){if(at-(c.lastEvidenceAt||c.updatedAt||c.createdAt)>30*MIN){c.status='EXPIRED';addTimeline(c,'INVESTIGATION_EXPIRED',{},at);continue;}if(at>c.investigationModeUntil){if(c.status==='ACTIVE'||c.status==='REOPENED')c.status='WAITING';continue;}if(c.candidateSnapshot&&(!c.lastSourceCheckAt||at-c.lastSourceCheckAt>=MIN))await investigate(c.candidateSnapshot,{forceSources:true});}await persist();}
 async function reconcileConfirmed(snapshot){
  const at=now(),events=(snapshot?.events||[]).filter(e=>/^confirmed_/.test(e.status)&&e.eventType==='appearance'&&Number.isFinite(e.estimatedAt)&&e.estimatedAt>=at-7*DAY);
  let changed=false;for(const event of events){if((event.confirmingSources||[]).includes('whatsapp-group'))continue;if(inv.missed.some(x=>x.eventId===event.id))continue;const detected=inv.cases.some(c=>c.boss===event.boss&&c.world===event.world&&Number.isFinite(c.firstDetectionAt)&&c.firstDetectionAt<=event.estimatedAt+30*MIN&&c.firstDetectionAt>=event.estimatedAt-30*MIN);if(detected)continue;const coverage=coverageAround(state,event.estimatedAt),kind=coverage!=null&&coverage>=80?'MISSED_DETECTION':'COVERAGE_INSUFFICIENT';inv.missed.unshift({id:'missed-'+investigationDigest(event.id).slice(0,24),eventId:event.id,boss:event.boss,world:event.world,eventAt:event.estimatedAt,detectedAt:null,coveragePct:coverage,kind,reason:kind==='MISSED_DETECTION'?'Evento confirmado sem candidato Lunarian durante período com cobertura suficiente.':'Não é possível classificar como falso negativo porque a cobertura Lunarian no período foi insuficiente.',recordedAt:at});changed=true;}if(inv.missed.length>5000)inv.missed.length=5000;if(changed){await persist();broadcast('update',{kind:'missed-detection'});}return changed;
 }
 function publicState(world){
  const at=now();const cases=inv.cases.filter(x=>!world||x.world===world),decisions=inv.decisions.filter(x=>!world||x.world===world),today=new Date(at).toISOString().slice(0,10),todayRows=decisions.filter(x=>new Date(x.decidedAt).toISOString().slice(0,10)===today),high=cases.filter(x=>x.rawScore>=80&&!['CONFIRMED','CONFIRMED_LATE','REJECTED','EXPIRED'].includes(x.status)),conflicts=cases.filter(x=>x.recommendation==='HIGH_CONFLICT'&&!['CONFIRMED','CONFIRMED_LATE','REJECTED'].includes(x.status)),timing=timingMetrics(decisions),backtest=backtestFromSnapshots(inv),learnedSources=profileView(inv.sourceProfiles,inv.outcomes,'sourceId'),reporters=profileView(inv.reporterProfiles,inv.outcomes,'authorHash'),adapterSources=createSourceAdapters(getSnapshot(world),at),learnedMap=new Map(learnedSources.map(x=>[x.id,x])),sources=adapterSources.map(a=>{const learned=learnedMap.get(a.id),oper=a.getReliability(),latency=a.getLatency();return {id:a.id,reliability:learned?.samples?learned.reliability:Math.round(oper.value*1000)/10,samples:learned?.samples||0,operationalSamples:oper.samples,recentSamples:learned?.recentSamples||0,recentAccuracy:learned?.recentAccuracy??null,historicalAccuracy:learned?.historicalAccuracy??null,drift:learned?.drift||false,driftDelta:learned?.driftDelta??null,bossSpecialties:learned?.bossSpecialties||[],health:a.getSourceHealth(),latency};});
  return {version:inv.version,modelRegistry:inv.modelRegistry,policyVersion:inv.policy.version,metrics:{active:cases.filter(x=>['ACTIVE','REOPENED','MANUAL_REVIEW_REQUIRED'].includes(x.status)).length,highConfidence:high.length,conflicts:conflicts.length,waiting:cases.filter(x=>x.status==='WAITING').length,likelyFalse:cases.filter(x=>x.recommendation==='LIKELY_FALSE'&&!['REJECTED'].includes(x.status)).length,confirmedToday:todayRows.filter(x=>x.outcome==='CONFIRMED').length,rejectedToday:todayRows.filter(x=>x.outcome==='REJECTED').length,totalCandidates:cases.length,totalDecisions:decisions.length,confirmationRate:decisions.length?Math.round(decisions.filter(x=>x.outcome==='CONFIRMED').length/decisions.length*1000)/10:null,rejectionRate:decisions.length?Math.round(decisions.filter(x=>x.outcome==='REJECTED').length/decisions.length*1000)/10:null,investigationAccuracy:backtest.confirmRecommendationAccuracy,falsePositiveRate:backtest.falsePositiveRate},timing,calibration:calibrationReport(decisions),backtest,cases:cases.slice(0,300).map(c=>publicCase(inv,c)),sources:sources.slice(0,100),reporters:reporters.slice(0,100),incidents:inv.incidents.filter(x=>!world||cases.some(c=>c.candidateId===x.candidateId)).slice(0,100),missed:inv.missed.filter(x=>!world||x.world===world).slice(0,100),improvementSuggestions:(state.whatsapp?.aliasSuggestions||[]).filter(x=>x.status==='SUGERIDO').slice(0,50).map(x=>({kind:'ALIAS_SUGGESTION',boss:x.boss,alias:x.alias,confirmed:x.confirmed,reporters:x.reporters?.length??x.reporters}))};
 }
 return {investigate,recordDecision,wait,tick,reconcileConfirmed,publicState,backtest:()=>backtestFromSnapshots(inv)};
}
