const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));
const median=a=>{if(!a.length)return null;const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2;};
function weightedMedian(rows){const sorted=[...rows].sort((a,b)=>a.at-b.at),total=sorted.reduce((n,x)=>n+x.weight,0);let c=0;for(const x of sorted){c+=x.weight;if(c>=total/2)return x.at;}return sorted.at(-1)?.at??null;}
export const DEFAULT_INVESTIGATION_POLICY={version:'investigation-policy-v1',weights:{evidence:.48,agreement:.16,diversity:.12,freshness:.08,historical:.08,health:.08},conflictPenalty:.35,anomalyPenalty:.2,coordinationPenalty:.12};

export function historicalContext(candidate,snapshot){
 const at=Number(candidate.estimatedAt)||Number(candidate.firstEvidenceAt),events=(snapshot?.events||[]).filter(e=>e.boss===candidate.boss&&e.world===candidate.world&&/^confirmed_/.test(e.status)&&e.eventType!=='absence'&&Number.isFinite(e.estimatedAt)&&e.estimatedAt<at).sort((a,b)=>a.estimatedAt-b.estimatedAt);
 const prediction=(snapshot?.predictions||[]).find(p=>p.boss===candidate.boss),last=events.at(-1)||null,intervals=[];for(let i=1;i<events.length;i++){const d=events[i].estimatedAt-events[i-1].estimatedAt;if(d>3600000&&d<180*86400000)intervals.push(d);}
 let plausibility=.5,anomaly={level:'UNKNOWN',score:.25,reason:'Histórico insuficiente'},intervalMs=last?at-last.estimatedAt:null;
 if(last&&intervals.length>=5){const med=median(intervals),dev=median(intervals.map(x=>Math.abs(x-med)))||3600000,scale=Math.max(3600000,dev*1.4826),z=Math.abs(intervalMs-med)/scale;plausibility=clamp(Math.exp(-z/3));if(intervalMs<2*3600000)anomaly={level:'HIGH',score:1,reason:'Relato ocorreu menos de 2 horas após o último evento confirmado.'};else if(z>=5)anomaly={level:'HIGH',score:clamp(z/7),reason:'Intervalo muito fora do padrão robusto.'};else if(z>=3)anomaly={level:'MEDIUM',score:clamp(z/6),reason:'Intervalo incomum em relação ao histórico.'};else anomaly={level:'LOW',score:clamp(z/8),reason:'Intervalo compatível com o histórico robusto.'};}
 let predictionCompatibility={level:'UNKNOWN',score:null,reason:'Previsão indisponível ou insuficiente.'};
 if(prediction?.status==='ready'&&Number.isFinite(at)){if(Number.isFinite(prediction.windowStart)&&Number.isFinite(prediction.windowEnd)){const inside=at>=prediction.windowStart&&at<=prediction.windowEnd,span=Math.max(60000,prediction.windowEnd-prediction.windowStart),distance=inside?0:Math.min(Math.abs(at-prediction.windowStart),Math.abs(at-prediction.windowEnd));const score=inside?1:clamp(1-distance/(span*2));predictionCompatibility={level:inside?'HIGH':score>=.5?'MEDIUM':'LOW',score,reason:inside?'Relato dentro da janela prevista.':'Relato fora da janela prevista.'};}}
 return {samples:events.length,lastEventAt:last?.estimatedAt||null,intervalMs,plausibility,anomaly,predictionCompatibility,prediction:prediction?{status:prediction.status,windowStart:prediction.windowStart||null,windowEnd:prediction.windowEnd||null,confidence:prediction.confidence??null}:null};
}
export function consensus(evidence=[]){
 const usable=evidence.filter(x=>x.canConfirm!==false&&['HEALTHY','DEGRADED','STALE'].includes(x.sourceHealth||'HEALTHY')),groups=new Map();
 for(const e of usable){const key=e.independenceKey||e.id,old=groups.get(key);if(!old||e.evidenceStrength>old.evidenceStrength)groups.set(key,e);}
 const independent=[...groups.values()],positive=independent.filter(x=>x.positive),negative=independent.filter(x=>x.negative),rows=positive.filter(x=>Number.isFinite(x.estimatedAt)).map(x=>({at:x.estimatedAt,weight:Math.max(.01,x.evidenceStrength)}));
 const centerAt=rows.length?Math.round(weightedMedian(rows)):null,spreadMs=rows.length>=2?Math.max(...rows.map(x=>x.at))-Math.min(...rows.map(x=>x.at)):0,agreement=rows.length<2?.55:clamp(1-spreadMs/(20*60000));
 const posStrength=positive.reduce((n,x)=>n+x.evidenceStrength,0),negStrength=negative.reduce((n,x)=>n+x.evidenceStrength,0),timeConflict=clamp((spreadMs-2*60000)/(30*60000)),directionConflict=clamp(negStrength/Math.max(.25,posStrength+negStrength)),conflictScore=clamp(Math.max(timeConflict,directionConflict));
 const kinds=new Set(positive.map(x=>x.sourceKind)),reporters=new Set(positive.map(x=>x.authorHash).filter(Boolean)),diversity=clamp((Math.min(3,kinds.size)+Math.min(4,reporters.size))/7),copyGroups=new Map();for(const e of positive){const h=e.detail?.textHash;if(!h)continue;if(!copyGroups.has(h))copyGroups.set(h,[]);copyGroups.get(h).push(e);}let coordinationScore=0;for(const rows of copyGroups.values()){if(rows.length<2||positive.length<2)continue;const times=rows.map(x=>x.observedAt).filter(Number.isFinite),span=times.length>=2?Math.max(...times)-Math.min(...times):Infinity;if(span<=30000)coordinationScore=Math.max(coordinationScore,rows.length/positive.length);}coordinationScore=clamp(coordinationScore);
 return {centerAt,spreadMs,agreement,conflictScore,coordinationScore,positiveStrength:posStrength,negativeStrength:negStrength,independentEvidence:positive.length,independentNegative:negative.length,sourceKinds:kinds.size,reporters:reporters.size,diversity};
}
export function calibrateCandidate(rawScore,decisions=[]){
 const rows=decisions.filter(x=>Number.isFinite(x.rawScore)&&['CONFIRMED','REJECTED'].includes(x.outcome)),lo=Math.floor(rawScore/10)*10,hi=Math.min(101,lo+10),bin=rows.filter(x=>x.rawScore>=lo&&x.rawScore<hi);
 if(bin.length<20)return {value:null,status:'INSUFFICIENT_DATA',samples:bin.length,range:[lo,hi===101?100:hi]};
 const hits=bin.filter(x=>x.outcome==='CONFIRMED').length,priorStrength=10,empirical=(hits+priorStrength*rawScore/100)/(bin.length+priorStrength),blend=Math.min(.8,bin.length/100),value=100*((1-blend)*rawScore/100+blend*empirical);
 return {value:Math.round(value*10)/10,status:'CALIBRATED',samples:bin.length,range:[lo,hi===101?100:hi]};
}
export function assessCandidate({evidence,history,coveragePct=null,decisions=[],policy=DEFAULT_INVESTIGATION_POLICY,safeFailure=false}){
 const c=consensus(evidence),positive=evidence.filter(x=>x.positive&&x.canConfirm!==false),freshness=positive.length?positive.reduce((n,x)=>n+(x.freshness||0),0)/positive.length:.2,healthRows=positive.filter(x=>x.sourceHealth),health=healthRows.length?healthRows.reduce((n,x)=>n+({HEALTHY:1,DEGRADED:.65,STALE:.45,OFFLINE:0,RATE_LIMITED:.2,ERROR:.1}[x.sourceHealth]??.5),0)/healthRows.length:.5,evidenceSignal=clamp(1-Math.exp(-c.positiveStrength/1.25)),coverage=coveragePct==null?.5:clamp(coveragePct/100);
 const w=policy.weights,base=100*(w.evidence*evidenceSignal+w.agreement*c.agreement+w.diversity*c.diversity+w.freshness*freshness+w.historical*(history?.plausibility??.5)+w.health*(.7*health+.3*coverage)),penalty=100*(policy.conflictPenalty*c.conflictScore+policy.anomalyPenalty*(history?.anomaly?.score??.25)+(policy.coordinationPenalty||0)*(c.coordinationScore||0)),rawScore=Math.round(clamp((base-penalty)/100)*1000)/10,calibration=calibrateCandidate(rawScore,decisions);
 let recommendation='WAIT_FOR_MORE_EVIDENCE';if(safeFailure)recommendation='REVIEW_RECOMMENDED';else if(c.conflictScore>=.55)recommendation='HIGH_CONFLICT';else if(c.negativeStrength>c.positiveStrength*1.2&&c.independentNegative>=1)recommendation='LIKELY_FALSE';else if(calibration.value!=null&&calibration.value>=90&&c.independentEvidence>=2&&(history?.anomaly?.level!=='HIGH'))recommendation='CONFIRM_RECOMMENDED';else if(rawScore>=65&&c.independentEvidence>=2)recommendation='REVIEW_RECOMMENDED';
 const factors=[{label:'Evidência independente',value:Math.round(evidenceSignal*100),effect:'positive'},{label:'Concordância temporal',value:Math.round(c.agreement*100),effect:'positive'},{label:'Diversidade',value:Math.round(c.diversity*100),effect:'positive'},{label:'Freshness',value:Math.round(freshness*100),effect:'positive'},{label:'Plausibilidade histórica',value:Math.round((history?.plausibility??.5)*100),effect:'context'},{label:'Conflito',value:Math.round(c.conflictScore*100),effect:'negative'},{label:'Possível coordenação/cópia',value:Math.round((c.coordinationScore||0)*100),effect:'negative'},{label:'Anomalia',value:Math.round((history?.anomaly?.score??.25)*100),effect:'negative'}];
 return {rawScore,calibration,recommendation,consensus:c,factors,coveragePct,policyVersion:policy.version};
}
export function calibrationReport(decisions=[]){
 const rows=decisions.filter(x=>Number.isFinite(x.rawScore)&&['CONFIRMED','REJECTED'].includes(x.outcome)),bins=[[50,60],[60,70],[70,80],[80,90],[90,101]].map(([lo,hi])=>{const a=rows.filter(x=>x.rawScore>=lo&&x.rawScore<hi),confirmed=a.filter(x=>x.outcome==='CONFIRMED').length;return {range:`${lo}–${hi===101?100:hi}%`,samples:a.length,predicted:a.length?Math.round(a.reduce((n,x)=>n+x.rawScore,0)/a.length*10)/10:null,actual:a.length?Math.round(confirmed/a.length*1000)/10:null};});return {samples:rows.length,bins};
}
