import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const root=new URL('../',import.meta.url),out=new URL('./',import.meta.url);await mkdir(out,{recursive:true});
let source=await readFile(new URL('server.mjs',root),'utf8');const imports=source.match(/^import .*;\r?$/gm).filter(s=>!s.includes("'node:http'")&&!s.includes("'node:fs/promises'")&&!s.includes("'node:url'")&&!s.includes("'node:path'"));
source=source.replace(/^import .*;\r?\n/gm,'').replace(/const ROOT = .*;/,"const ROOT = '/app';").replace(/const PORT = .*;/,'const PORT = 4317;').replace(/const ORIGIN = .*;/,'const ORIGIN = context.origin;').replace(/const AUTH_REQUIRED=.*;/,'const AUTH_REQUIRED=false;').replace(/const SITE_PASSWORD=.*;/,"const SITE_PASSWORD='';").replace("if(!ALLOWED_HOSTS.has(String(req.headers.host||'')))","if(req.headers.host!==new URL(ORIGIN).host)");
source=source.replace(/server.listen\([\s\S]*$/,'return {handler:server.handler,poll};');
source=source.replace(/void poll\(\);/g,'await poll();');
source=source.replace("if(url.pathname==='/api/events') {","if(url.pathname==='/api/events') { return json(res,200,{polling:true});");
await writeFile(new URL('server.generated.mjs',out),imports.map(s=>s.replace("from './","from '../")).join('\n')+`\nimport {posix} from 'node:path';\nconst join=posix.join;\nexport async function createHostedServer(context){\nconst {readFile,writeFile,mkdir,rename}=context;\nconst http={createServer(handler){return {handler};}};\n`+source+'\n}\n');
const files=['index.html','styles.css','app.js','character-ui.mjs','intelligence-ui.mjs','discovery-ui.mjs','system-health-ui.mjs','ai-lab-ui.mjs','notification-flow.mjs','group-ui.mjs','whatsapp-ui.mjs','bosstiary.mjs','group-checks.mjs','logic.mjs','sw.js','bosstiary.json','boss-map-ui.mjs',...['manifest.json','adapter.js','collector-core.js','background.js','content.js','popup.html','popup.js','popup.css','LEIA-ME.md'].map(name=>'edge-extension/'+name)];const assets={};
for(const name of files){let bytes=await readFile(new URL(name,root));if(name==='index.html'){let html=bytes.toString().replace('Seu progresso salvo neste computador','Seu progresso salvo na sua hospedagem').replace(/http:\/\/127\.0\.0\.1:4317\//g,'/').replace('o painel local abertos','o site acessível');bytes=Buffer.from(html);}if(name==='app.js'){let js=bytes.toString().replace(/const events=new EventSource\([^\n]+/,'// A hospedagem consulta atualizações por intervalo, sem conexão permanente.');bytes=Buffer.from(js);}if(name==='notification-flow.mjs')bytes=Buffer.from(bytes.toString().replace(/pelo endereço http:\/\/127\.0\.0\.1:4317\//g,'pelo endereço HTTPS deste site').replace(/Abra http:\/\/127\.0\.0\.1:4317\//g,'Abra este site'));assets['/app/'+name]=bytes.toString('base64');}
const catalogue=JSON.parse(await readFile(new URL('data/catalog.json',root),'utf8'));assets['/app/data/catalog.json']=Buffer.from(JSON.stringify(catalogue)).toString('base64');
await writeFile(new URL('assets.generated.mjs',out),'export default '+JSON.stringify(assets)+';\n');console.log('Pacote Cloudflare gerado sem dados pessoais, credenciais ou imagens privadas.');
