let getModel,post,reload,notify,lab=null;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—',pct=v=>Number.isFinite(Number(v))?(Number(v)*100).toFixed(1)+'%':'—',dt=v=>Number.isFinite(Number(v))?new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(Number(v))):'—';
const metric=(v,suffix='')=>Number.isFinite(Number(v))?num(v,1)+suffix:'INSUFFICIENT DATA';
const statusClass=s=>String(s||'UNKNOWN').toLowerCase().replaceAll('_','-');
function modelMetrics(m={}){
 return '<div class="intel-kpis"><article><span>AMOSTRA</span><strong>'+esc(m.samples??0)+'</strong><small>previsões resolvidas</small></article><article><span>MAE</span><strong>'+metric(m.maeMinutes,' min')+'</strong><small>erro absoluto médio</small></article><article><span>ERRO MEDIANO</span><strong>'+metric(m.medianErrorMinutes,' min')+'</strong><small>mediana</small></article><article><span>P95 ERROR</span><strong>'+metric(m.p95ErrorMinutes,' min')+'</strong><small>cauda de erro</small></article><article><span>BRIER</span><strong>'+metric(m.brierScore,'')+'</strong><small>'+(m.brierScore==null?'não medido':'menor é melhor')+'</small></article><article><span>CALIBRAÇÃO</span><strong>'+metric(m.calibrationError,'')+'</strong><small>ECE</small></article></div>';
}
function reliability(rows=[]){
 if(!rows.some(x=>x.samples))return '<p class="muted">INSUFFICIENT DATA para reliability diagram.</p>';
 return '<div class="table-wrap"><table class="ranking-table"><thead><tr><th>Faixa</th><th>Amostras</th><th>Previsto</th><th>Observado</th><th>Gap</th></tr></thead><tbody>'+rows.map(x=>'<tr><td>'+esc(x.range?.[0])+'–'+esc(x.range?.[1])+'%</td><td>'+esc(x.samples)+'</td><td>'+(x.predicted==null?'—':num(x.predicted*100,1)+'%')+'</td><td>'+(x.observed==null?'—':num(x.observed*100,1)+'%')+'</td><td>'+(x.predicted==null||x.observed==null?'—':num((x.observed-x.predicted)*100,1)+' p.p.')+'</td></tr>').join('')+'</tbody></table></div>';
}
function experimentCard(e){
 const h=e.result?.historical||{},live=e.live||{},gate=h.historicalGate||{},hold=gate.holdout||{},canApprove=e.status==='ELIGIBLE_FOR_PROMOTION',canRun=['PROPOSED','FAILED','INCONCLUSIVE'].includes(e.status);
 return '<article class="group-panel ai-exp-card"><div class="sectionhead"><div><span class="health-state '+statusClass(e.status)+'">'+esc(e.status)+'</span><h3>'+esc(e.id)+' · '+esc(e.modelId)+'</h3><p><b>Hipótese:</b> '+esc(e.hypothesis)+'</p><small>'+esc(e.world)+(e.boss?' · '+esc(e.boss):' · GLOBAL')+' · criado '+dt(e.createdAt)+'</small></div><div class="group-buttons">'+
 (canRun?'<button class="primary" data-lab-run="'+esc(e.id)+'">EXECUTAR</button>':'')+
 (canApprove?'<button class="primary" data-lab-approve="'+esc(e.id)+'">APROVAR CANARY</button>':'')+
 (!['REJECTED','PROMOTED','ARCHIVED'].includes(e.status)?'<button class="secondary" data-lab-reject="'+esc(e.id)+'">REJEITAR</button>':'')+
 (e.status!=='ARCHIVED'?'<button class="secondary" data-lab-archive="'+esc(e.id)+'">ARQUIVAR</button>':'')+
 '</div></div>'+
 '<div class="intel-kpis"><article><span>SAMPLE SIZE</span><strong>'+esc(h.sampleSize??e.result?.sampleSize??0)+'</strong><small>histórico temporal</small></article><article><span>HOLDOUT MAE GAIN</span><strong>'+(h.holdoutImprovementPct==null?'—':esc(h.holdoutImprovementPct)+'%')+'</strong><small>fora da amostra</small></article><article><span>95% CI</span><strong>'+(gate.paired?.ci95?esc(gate.paired.ci95.join(' → '))+' min':'—')+'</strong><small>melhoria pareada</small></article><article><span>FDR q-value</span><strong>'+(e.falseDiscoveryQ==null?'—':esc(e.falseDiscoveryQ))+'</strong><small>controle de múltiplos testes</small></article></div>'+
 (h.overfitRisk?.detected?'<div class="notice system-degraded"><b>OVERFIT_RISK</b><p>'+esc(h.overfitRisk.reasons.join(' · '))+'</p></div>':'')+
 '<details><summary>Backtest, walk-forward e holdout</summary><p><b>Temporal:</b> '+esc(h.temporalPassed?'PASS':'FAIL')+' · <b>Leakage audit:</b> '+esc(h.leakagePassed?'PASS':'FAIL')+' · <b>Walk-forward:</b> '+esc(h.walkForward?.status||'—')+' · folds positivos '+esc(h.walkForward?.positiveFolds??0)+'/'+esc(h.walkForward?.totalFolds??0)+'</p><p><b>Gate:</b> '+esc(gate.passed?'PASS':'FAIL')+' · '+esc((gate.reasons||[]).join(' · ')||'sem bloqueios')+'</p><p><b>Champion holdout:</b> MAE '+metric(hold.champion?.maeMinutes,' min')+' · P95 '+metric(hold.champion?.p95ErrorMinutes,' min')+' · Brier '+metric(hold.champion?.brierScore)+'</p><p><b>Challenger holdout:</b> MAE '+metric(hold.challenger?.maeMinutes,' min')+' · P95 '+metric(hold.challenger?.p95ErrorMinutes,' min')+' · Brier '+metric(hold.challenger?.brierScore)+'</p></details>'+
 (live.samples?'<details><summary>Live Shadow · '+esc(live.samples)+' eventos</summary>'+modelMetrics(live.challenger)+'<p><b>Champion live:</b> MAE '+metric(live.champion?.maeMinutes,' min')+' · P95 '+metric(live.champion?.p95ErrorMinutes,' min')+'</p><p><b>Recomendação:</b> '+esc(e.result?.recommendation||'WAIT')+' · gate '+esc(live.gate?.passed?'PASS':'WAIT/FAIL')+'</p><h4>Reliability diagram do Challenger</h4>'+reliability(live.reliabilityDiagram)+'</details>':'<p class="muted">Live Shadow ainda sem amostra suficiente.</p>')+
 '<details><summary>Reprodutibilidade e configuração</summary><pre>'+esc(JSON.stringify({modelId:e.modelId,modelVersion:e.modelVersion,features:e.features,parameters:e.parameters,datasetVersion:e.datasetVersion,featureVersion:e.featureVersion,codeVersion:e.codeVersion,randomSeed:e.randomSeed},null,2))+'</pre></details></article>';
}
function canaryCard(c){
 const m=c.metrics||{};return '<article class="group-panel"><div class="sectionhead"><div><span class="health-state '+statusClass(c.status)+'">'+esc(c.status)+'</span><h3>'+esc(c.id)+' · '+esc(c.modelId)+'</h3><p>'+esc(c.world)+(c.boss?' · '+esc(c.boss):' · GLOBAL')+' · rollout '+esc(c.percentage)+'%</p></div><button class="secondary" data-lab-rollback="'+esc(c.boss||'')+'">ROLLBACK</button></div><p>Amostras do estágio: <b>'+esc(c.samples||0)+'</b> · estágio '+esc((c.stage??0)+1)+'/'+esc(c.stages?.length||0)+'</p>'+(m.challenger?'<p>Challenger MAE '+metric(m.challenger.maeMinutes,' min')+' · P95 '+metric(m.challenger.p95ErrorMinutes,' min')+' | Champion MAE '+metric(m.champion?.maeMinutes,' min')+'</p>':'<p class="muted">Aguardando eventos reais do estágio.</p>')+'</article>';
}
export function renderAILab(data){
 lab=data;const root=$('ai-lab-content');if(!root)return;if(!data){root.innerHTML='<p class="muted">Carregando AI Lab…</p>';return;}
 const c=data.champion||{},cm=c.metrics||{},p=data.policy||{},experiments=data.experiments||[],leader=data.leaderboard?.overall||[],bosses=data.leaderboard?.perBoss||[],features=data.features||{};
 root.innerHTML='<section class="group-panel"><div class="eyebrow">BOSS RADAR AI LAB</div><h2>Experimentação científica sem risco para produção</h2><p>Nova IA não é melhor IA. O laboratório exige evidência temporal fora da amostra, Shadow futuro e aprovação controlada antes de qualquer Canary.</p><div class="notice"><b>Métrica primária:</b> melhoria pareada de MAE temporal. <span>Guardrails: P95/tail risk, calibração, Brier/log loss quando disponíveis, latência, estabilidade, leakage e regressão por boss.</span></div><p><b>Auto model promotion:</b> '+esc(p.auto_model_promotion?'ON':'OFF')+' · mínimo histórico '+esc(p.minHistoricalSamples)+' · mínimo Shadow '+esc(p.minShadowEvents)+' eventos.</p></section>'+
 '<section class="group-panel"><div class="eyebrow">CHAMPION</div><div class="sectionhead"><div><h2>'+esc(c.name||c.modelId||'adaptive_ensemble')+'</h2><p>'+esc(c.modelVersion||'')+' · '+esc(c.scope||'global')+'</p></div></div>'+modelMetrics(cm)+'<details><summary>Model Card</summary><pre>'+esc(JSON.stringify(c.modelCard||{},null,2))+'</pre></details></section>'+
 '<section class="group-panel"><div class="eyebrow">NOVO EXPERIMENTO</div><h2>Hipótese explícita</h2><form id="ai-lab-create" class="add-form"><label>Hipótese<input id="ai-lab-hypothesis" maxlength="500" required placeholder="Ex.: Dar maior peso aos últimos 10 intervalos reduz o MAE de Ferumbras."></label><label>Challenger<select id="ai-lab-model"><option value="robust_interval">Robust Interval</option><option value="empirical_survival">Empirical Survival</option></select></label><label>Boss opcional<input id="ai-lab-boss" maxlength="140" placeholder="Vazio = experimento global"></label><button class="primary">CRIAR EXPERIMENTO</button></form></section>'+
 '<section class="group-panel"><div class="eyebrow">EXPERIMENT REGISTRY</div><h2>Experimentos</h2><p>'+esc(experiments.length)+' registrados · '+esc(data.shadowModels?.length||0)+' Shadow · '+esc(data.challengers?.length||0)+' Challengers.</p></section>'+experiments.map(experimentCard).join('')+
 '<section class="group-panel"><div class="eyebrow">CANARY & ROLLBACK</div><h2>Rollouts aprovados</h2>'+((data.canaries||[]).map(canaryCard).join('')||'<p class="muted">Nenhum Canary ativo ou histórico neste servidor.</p>')+'</section>'+
 '<section class="group-panel"><div class="eyebrow">MODEL LEADERBOARD</div><h2>Overall · sempre com sample size</h2><div class="table-wrap"><table class="ranking-table"><thead><tr><th>Modelo</th><th>n</th><th>MAE</th><th>Mediana</th><th>P95</th><th>Janela</th><th>Brier</th><th>Calibração</th></tr></thead><tbody>'+leader.map(x=>'<tr><td><b>'+esc(x.name)+'</b><small>'+esc(x.version)+'</small></td><td>'+esc(x.samples)+'</td><td>'+metric(x.maeMinutes,' min')+'</td><td>'+metric(x.medianErrorMinutes,' min')+'</td><td>'+metric(x.p95ErrorMinutes,' min')+'</td><td>'+(x.windowAccuracy==null?'—':pct(x.windowAccuracy))+'</td><td>'+metric(x.brierScore)+'</td><td>'+metric(x.calibrationError)+'</td></tr>').join('')+'</tbody></table></div><h3>Melhor modelo por boss</h3><div class="table-wrap"><table class="ranking-table"><thead><tr><th>Boss</th><th>Melhor modelo medido</th><th>n</th><th>MAE</th><th>P95</th></tr></thead><tbody>'+bosses.slice(0,100).map(x=>'<tr><td>'+esc(x.boss)+'</td><td><b>'+esc(x.best?.modelId||'INSUFFICIENT DATA')+'</b></td><td>'+esc(x.best?.samples||0)+'</td><td>'+metric(x.best?.maeMinutes,' min')+'</td><td>'+metric(x.best?.p95ErrorMinutes,' min')+'</td></tr>').join('')+'</tbody></table></div></section>'+
 '<section class="group-panel"><div class="eyebrow">FEATURE ABLATION</div><h2>Features úteis e dispensáveis</h2><p>Bosses medidos por walk-forward ablation: <b>'+esc(features.measuredBosses||0)+'</b>.</p><div class="table-wrap"><table class="ranking-table"><thead><tr><th>Feature útil</th><th>Bosses</th><th>Aumento médio de MAE ao remover</th></tr></thead><tbody>'+((features.topUseful||[]).map(x=>'<tr><td><b>'+esc(x.name)+'</b></td><td>'+esc(x.bosses)+'</td><td>'+metric(x.meanMaeIncreaseHours,' h')+'</td></tr>').join('')||'<tr><td colspan="3">INSUFFICIENT DATA</td></tr>')+'</tbody></table></div><h3>Possivelmente inúteis</h3><p>'+((features.oftenUseless||[]).map(x=>esc(x.name)+' ('+esc(x.bosses)+' bosses)').join(' · ')||'INSUFFICIENT DATA')+'</p></section>'+
 '<section class="group-panel"><div class="eyebrow">EXPERIMENT SUGGESTION ENGINE</div><h2>Próximas hipóteses sugeridas</h2>'+((data.suggestions||[]).map(x=>'<article class="event-row"><div><b>'+esc(x.hypothesis)+'</b><p>'+esc(x.reason)+' · suporte '+esc(x.support)+' · '+esc(x.boss||'GLOBAL')+'</p></div><button class="secondary" data-lab-suggest="'+esc(x.id)+'">CRIAR</button></article>').join('')||'<p class="muted">Ainda não há erros suficientes para sugerir novos experimentos com evidência.</p>')+'</section>'+
 '<section class="group-panel"><div class="eyebrow">EVOLUÇÃO</div><h2>A IA está ficando melhor?</h2><div class="intel-kpis"><article><span>LEARNING VELOCITY</span><strong>'+(data.learningVelocity==null?'INSUFFICIENT DATA':esc(data.learningVelocity)+' p.p.')+'</strong><small>mudança entre promoções validadas</small></article><article><span>DIMINISHING RETURNS</span><strong>'+esc(data.diminishingReturns?'DETECTED':'NÃO DETECTADO / INSUFICIENTE')+'</strong><small>últimas melhorias promovidas</small></article><article><span>DATASET VERSIONS</span><strong>'+esc(data.datasetVersions?.length||0)+'</strong><small>snapshots reproduzíveis</small></article><article><span>FEATURE VERSION</span><strong>'+esc(data.featureVersion||'—')+'</strong><small>code '+esc(data.codeVersion||'—')+'</small></article></div></section>'+
 '<section class="group-panel"><div class="eyebrow">EXPERIMENT KNOWLEDGE BASE</div><h2>O que já foi aprendido</h2><div class="table-wrap"><table class="ranking-table"><thead><tr><th>Experimento</th><th>Hipótese</th><th>Status</th><th>Amostra</th><th>Holdout gain</th></tr></thead><tbody>'+((data.knowledge||[]).map(x=>'<tr><td>'+esc(x.experimentId)+'</td><td>'+esc(x.hypothesis)+'</td><td>'+esc(x.status)+'</td><td>'+esc(x.sampleSize)+'</td><td>'+(x.holdoutImprovementPct==null?'—':esc(x.holdoutImprovementPct)+'%')+'</td></tr>').join('')||'<tr><td colspan="5">Nenhum experimento concluído ainda.</td></tr>')+'</tbody></table></div></section>';
 const form=$('ai-lab-create');if(form)form.addEventListener('submit',e=>{e.preventDefault();void createFromForm();});
}
async function createFromForm(prefill=null){
 const world=getModel().settings.world,hypothesis=prefill?.hypothesis||$('ai-lab-hypothesis')?.value.trim(),modelId=prefill?.modelId||$('ai-lab-model')?.value,boss=prefill?.boss??$('ai-lab-boss')?.value.trim()||null,kind=prefill?.kind||'model';
 if(!hypothesis)throw new Error('Informe uma hipótese.');const d=await post('/api/intelligence/ai-lab/create',{world,hypothesis,modelId,boss,kind,features:prefill?.features||[]});notify(d.duplicate?'Hipótese equivalente já existe no Experiment Registry.':'Experimento criado em PROPOSED.');await loadAILab();
}
export async function loadAILab(){const root=$('ai-lab-content');if(root&&!lab)root.innerHTML='<p class="muted">Carregando AI Lab…</p>';try{const r=await fetch('/api/intelligence/ai-lab',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'AI Lab indisponível');renderAILab(d);return d;}catch(e){if(root)root.innerHTML='<div class="notice">'+esc(e.message)+'</div>';throw e;}}
export function initAILabUI(options){({getModel,post,reload,notify}=options);const root=$('ai-lab-content');if(!root)return;root.addEventListener('click',e=>{const run=e.target.closest('[data-lab-run]'),approve=e.target.closest('[data-lab-approve]'),reject=e.target.closest('[data-lab-reject]'),archive=e.target.closest('[data-lab-archive]'),rollback=e.target.closest('[data-lab-rollback]'),suggest=e.target.closest('[data-lab-suggest]');if(run)void post('/api/intelligence/ai-lab/run',{id:run.dataset.labRun}).then(loadAILab).then(()=>notify('Experimento concluído; gates atualizados.')).catch(x=>notify(x.message));if(approve){const reason=prompt('Motivo da aprovação para Canary:','Gates históricos e Live Shadow aprovados')||'';if(reason)void post('/api/intelligence/ai-lab/decision',{id:approve.dataset.labApprove,decision:'approve',reason}).then(loadAILab).then(()=>notify('Canary iniciado com rollout gradual.')).catch(x=>notify(x.message));}if(reject){const reason=prompt('Motivo da rejeição:','Não atende aos critérios de promoção')||'';if(reason)void post('/api/intelligence/ai-lab/decision',{id:reject.dataset.labReject,decision:'reject',reason}).then(loadAILab).catch(x=>notify(x.message));}if(archive){const reason=prompt('Motivo do arquivamento:','Experimento encerrado')||'';if(reason)void post('/api/intelligence/ai-lab/decision',{id:archive.dataset.labArchive,decision:'archive',reason}).then(loadAILab).catch(x=>notify(x.message));}if(rollback){const reason=prompt('Motivo do rollback:','Regressão ou decisão manual')||'';if(reason)void post('/api/intelligence/ai-lab/rollback',{world:getModel().settings.world,boss:rollback.dataset.labRollback||null,reason}).then(loadAILab).then(()=>notify('Rollback aplicado.')).catch(x=>notify(x.message));}if(suggest){const item=lab?.suggestions?.find(x=>x.id===suggest.dataset.labSuggest);if(item)void createFromForm(item).catch(x=>notify(x.message));}});
}
