const safe=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=n=>n!==null&&n!==undefined&&Number.isFinite(Number(n))?Number(n).toLocaleString('pt-BR'):'Não informado';
const date=n=>Number(n)>0?new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'}).format(new Date(Number(n)*1000)):'Não informado';
const value=v=>v===null||v===undefined||v===''?'Não informado':typeof v==='object'?JSON.stringify(v):String(v);
const row=(label,v)=>`<div class="log-row"><b>${safe(label)}</b><span>${safe(value(v))}</span></div>`;
const list=(items,empty)=>items.length?items.map(x=>row(x.name||x.title||'Registro',x.description||x.comment||x.name||x)).join(''):`<p class="muted">${safe(empty)}</p>`;
const sprite=(p,d)=>`<span class="outfit-sprite" role="img" aria-label="Aparência animada de ${safe(p.name)}"><img src="/api/outfit?name=${encodeURIComponent(p.name)}&direction=${d}" alt="" loading="lazy"></span>`;
export function renderCharacter(result){
 const c=result.character;if(!c)return `<div class="notice">${safe(result.error||'Consultando personagem…')}</div>`;
 const p=c.player,x=c.experience;
 return `${result.error?'<div class="notice">Não foi possível atualizar. Exibindo a última consulta salva.</div>':''}
 <div class="character-hero">${sprite(p,2)}<div><div class="eyebrow">${safe(p.world)}</div><h2>${safe(p.name)}</h2><p>${safe(p.vocation)} · level ${number(p.level)}</p><small>Atualizado ${date(c.fetchedAt/1000)}</small></div></div>
 <div class="character-highlights"><div><small>MAGIC LEVEL</small><b>${number(c.rankings?.rows.find(r=>r.id==='magic'||r.category==='magic')?.value??c.rankings?.rows.find(r=>r.label==='Magic level')?.value)}</b></div><div><small>CONQUISTAS</small><b>${number(p.achievementPoints)}</b></div><div><small>EXPERIÊNCIA</small><b>${number(x?.experience)}</b></div></div>
 <div class="profile-columns"><section><h3>Personagem</h3>${row('Nome',p.name)}${row('Level',number(p.level))}${row('Vocação',p.vocation)}${row('Mundo',p.world)}${row('Sexo',p.sex==='Male'?'Masculino':p.sex==='Female'?'Feminino':p.sex)}${row('Residência',p.residence)}${row('Título',p.title)}${row('Pontos de conquista',number(p.achievementPoints))}${row('Criado em',date(p.created))}${row('Último login',date(p.lastlogin))}${row('VIP até',date(p.vip_time))}${row('Parceiro(a)',p.partner||'Não informado')}${row('Nomes anteriores',p.formerNames?.length?p.formerNames.join(', '):'Nenhum')}${row('Comentário',p.comment||'Nenhum')}${row('Negociado recentemente',p.recentlyTraded?'Sim':'Não')}</section>
 <section><h3>Guilda e casa</h3>${row('Guilda',p.guild?.name)}${row('Cargo',p.guild?.rank)}${row('Apelido',p.guild?.nick||'Não informado')}${row('Casa',p.house?.name)}${row('Tamanho',p.house?.size?`${p.house.size} sqm`:null)}${row('Aluguel',p.house?.rent?`${number(p.house.rent)} gold`:null)}<h3>Conta</h3>${row('Criada em',date(p.account_created))}${row('Lealdade',p.loyalty_points>0?number(p.loyalty_points):'Não informado')}${row('Negociação atual',p.auction||'Nenhuma')}<h3>Experiência</h3>${x?`${row('Total',number(x.experience))}${row('Ganho em 24h',number(x.gain24h))}${row('Ganho em 7 dias',number(x.gain7d))}${row('Ganho em 30 dias',number(x.gain30d))}`:'<p class="muted">Experiência indisponível.</p>'}</section></div>
 <h3>Skills, pontuações e rankings</h3>${c.rankings?`<div class="table-wrap"><table class="ranking-table"><thead><tr><th>Categoria</th><th>Valor</th><th>Posição no mundo</th></tr></thead><tbody>${c.rankings.rows.map(r=>`<tr><td>${safe(r.label)}</td><td>${r.status==='found'?number(r.value):r.status==='unavailable'?'Indisponível':'Não listado'}</td><td>${r.rank?number(r.rank):'—'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Rankings indisponíveis.</p>'}
 <h3>Mortes recentes</h3>${c.deaths.length?c.deaths.map(d=>`<div class="log-row"><b>${date(d.time)}</b><span>Level ${number(d.level)} · ${safe(d.killed_by)} · maior dano: ${safe(d.mostdamage_by)}</span></div>`).join(''):'<p class="muted">Nenhuma morte registrada.</p>'}
 <div class="profile-columns"><section><h3>Conquistas exibidas</h3>${list(c.displayedAchievements,'Nenhuma conquista individual exibida.')}<h3>Badges</h3>${list(c.accountBadges,'Nenhum badge exibido.')}</section><section><h3>Outros personagens</h3>${list(c.otherCharacters,'Nenhum outro personagem informado.')}<h3>Punições</h3>${c.banInfo?row('Registro',c.banInfo):'<p class="muted">Nenhuma punição informada.</p>'}${list(c.banHistory,'')}</section></div>
 <h3>Aparência do personagem</h3><div class="outfit-gallery">${[0,1,2,3].map(d=>sprite(p,d)).join('')}</div><p class="muted">As kills individuais do Bosstiary devem ser preenchidas em Meu progresso com os valores do jogo.</p>`;
}
