import test from 'node:test';
import assert from 'node:assert/strict';
import {makeObservation} from './normalization/observations.mjs';
import {canonicalEvent,captureCanonical,eventsAsOf,horizonLabel} from './discovery/canonical-events.mjs';
import {ensureDiscovery,registerCandidate,sourceSample,addContext,addCoverage,discoveryDashboard} from './discovery/service.mjs';
import {buildCases,signalFeatures,probabilities,runDiscovery} from './discovery/signals.mjs';
import {pairedSign,adjustFDR,probabilityMetrics} from './discovery/statistics.mjs';
import {bossGraph,sourceGraph} from './discovery/graphs.mjs';
import {ensureTemporalKnowledge,refreshTemporalKnowledge,temporalKnowledgeDashboard,queryTemporalKnowledge,noveltyConfidenceGuard} from './discovery/temporal-knowledge.mjs';
import {historicalReplay,liveProbability,predictability} from './discovery/live.mjs';
import {consensusForEvidence} from './consensus/engine.mjs';
import {recomputeEvent} from './deduplication/events.mjs';
import {createIntelligence} from './intelligence/service.mjs';
import {discoveryHtml,historicalHtml} from './discovery-ui.mjs';
import {spawnDistribution} from './discovery/distribution.mjs';
import {predictionErrorRelationshipAnalysis,confirmationLatencyAnalysis} from './discovery/context-analysis.mjs';
import {causalDiscoveryLab} from './discovery/causal-lab.mjs';
import {reviewCandidate,evaluateSources} from './discovery/service.mjs';
import {learnFromEvent} from './learning/reliability.mjs';
import {digest} from './mlops/feature-store.mjs';
const H=3600000,T=Date.parse('2025-01-01T00:00:00Z');
function event(i,boss='A'){const at=T+i*H;return {id:boss+i,boss,world:'World',eventType:'appearance',startAt:at,endAt:at,estimatedAt:at,updatedAt:at+1000,status:'confirmed_auto',qualityStatus:'CONFIRMADO',confidence:.95,evidence:[{evidenceId:'ev'+boss+i,boss,world:'World',sourceId:'s1',eventType:'appearance',startAt:at,endAt:at,estimatedAt:at,precision:'minute',confidence:.95,collectedAt:at+1000,processedAt:at+1000,reportedAt:at+1000,quality:{status:'CONFIRMADO',traceable:true,eligibleForLearning:true,score:95}}]};}
function intelligence(){const s={events:[],sources:{}};ensureDiscovery(s,T);return s;}
function history(n=160){const s=intelligence();for(let i=0;i<n;i++){s.events.push(event(i*12));captureCanonical(s,T+i*12*H+1000);}s.discovery.analysisAsOf=T+n*12*H;for(let j=0;j<n*12;j+=24){const endAt=T+Math.min(j+24,n*12)*H;addCoverage(s.discovery,{boss:'A',world:'World',startAt:T+j*H,endAt,sourceRef:'verified-monitor',verified:true,continuous:true},endAt)};return s;}
test('Timestamp separation preserves unknown publication and detection instead of using spawn',()=>{const o=makeObservation({evidenceId:'x',boss:'A',world:'World',sourceId:'s1',precision:'minute',estimatedAt:T,processedAt:T+H});assert.equal(o.detectedAt,null);assert.equal(o.publishedAt,null);assert.equal(o.confirmedAt,null);assert.equal(o.estimatedAt,T);assert.throws(()=>makeObservation({...o,publishedAt:T+2*H}),/Timestamp/);});
test('Canonical identity survives correction and retains censoring and timestamp uncertainty',()=>{const e=event(1);e.startAt-=55000;e.endAt+=55000;e.evidence[0].detectedAt=e.endAt+60000;const a=canonicalEvent(e,{},T+4*H);assert.equal(a.spawn.uncertaintyMs,55000);assert.equal(a.spawn.censored,true);assert.equal(a.firstPublicationAt,null);assert.equal(a.firstDetectionAt,e.endAt+60000);e.estimatedAt+=2000;assert.equal(canonicalEvent(e,{},T+5*H).id,a.id);});
test('Death-only evidence is never assigned a precise spawn in discovery',()=>{const e=event(1);e.eventType='kill';e.evidence[0].eventType='kill';assert.equal(canonicalEvent(e,{},T+2*H).status,'QUARENTENA');});
test('Historical versions hide future corrections, removals and late imports',()=>{const s=intelligence();s.events=[event(1)];captureCanonical(s,T+2*H);assert.equal(eventsAsOf(s.discovery,'World',T+H).length,0);s.events[0].estimatedAt=T+H+100;s.events[0].startAt+=100;s.events[0].endAt+=100;s.events[0].updatedAt=T+4*H;captureCanonical(s,T+4*H);assert.equal(eventsAsOf(s.discovery,'World',T+3*H)[0].spawn.estimate,T+H);s.events=[];captureCanonical(s,T+6*H);assert.equal(eventsAsOf(s.discovery,'World',T+5*H).length,1);assert.equal(eventsAsOf(s.discovery,'World',T+7*H).length,0);});
test('Negative labels need continuous coverage, not a passed forecast or isolated empty check',()=>{const events=[canonicalEvent(event(1),{},T+2*H)];assert.equal(horizonLabel(events,[],'A','World',T+3*H,H,T+6*H).value,null);const coverage=[{boss:'A',world:'World',startAt:T+3*H,endAt:T+4*H,knownAt:T+5*H,verified:true}];assert.equal(horizonLabel(events,coverage,'A','World',T+3*H,H,T+6*H).value,0);assert.equal(horizonLabel(events,coverage,'A','World',T+3*H,H,T+4*H).value,null);});
test('Censored intervals crossing horizon cannot become invented positives or negatives',()=>{const e=canonicalEvent(event(1),{},T+3*H);e.spawn={lower:T+.5*H,upper:T+1.5*H,estimate:T+H};assert.equal(horizonLabel([e],[],'A','World',T,H,T+4*H).value,null);});
test('Regular horizon cases use only event versions available at the anchor',()=>{const s=history(80),cases=buildCases(s.discovery,'World','A');assert.ok(cases.length>50);assert.ok(cases.some(c=>c.y===0));assert.ok(cases.some(c=>c.y===1));const earliest=cases[0];assert.equal(earliest.features.elapsed,'0');assert.ok(cases.every(c=>c.knownAt>c.at));});
test('Context events cannot masquerade as information known before collection',()=>{const s=intelligence();addContext(s.discovery,{type:'update',world:'World',startAt:T+H,sourceRef:'https://example.org/update'},T+10*H);assert.equal(signalFeatures([],s.discovery.context,'A',T+5*H).regime,'unknown');assert.notEqual(signalFeatures([],s.discovery.context,'A',T+11*H).regime,'unknown');assert.throws(()=>addContext(s.discovery,{type:'update',world:'World',startAt:T+11*H,sourceRef:'x'},T+10*H),/inválido/);});
test('Duplicate confirmations from one source cannot raise fusion confidence',()=>{const e=event(1),one=structuredClone(e.evidence[0]);const single=consensusForEvidence([one],{}),many=consensusForEvidence(Array.from({length:20},(_,i)=>({...one,evidenceId:'spam'+i})),{});assert.equal(single.confidence,many.confidence);e.evidence=[one];recomputeEvent(e,{});const before=e.confidence;e.evidence=Array.from({length:20},(_,i)=>({...one,evidenceId:'spam'+i}));recomputeEvent(e,{});assert.equal(e.confidence,before);assert.notEqual(e.status,'confirmed_auto');});
test('Declared dependent sources count as one evidence group in fusion',()=>{const one=event(1).evidence[0],sources={a:{dependencyGroup:'g'},b:{dependencyGroup:'g'},c:{dependencyGroup:'g'}};const result=consensusForEvidence(['a','b','c'].map(sourceId=>({...one,sourceId})),sources);assert.equal(result.independentSourceCount,1);assert.notEqual(result.status,'CONFIRMADO');});
test('Source dependency analysis uses publication order and identical payload, not collection delay',()=>{const events=Array.from({length:35},(_,i)=>{const e=canonicalEvent(event(i),{},T+100*H);e.evidence=[{sourceId:'a',publishedAt:T+i*H,payloadHash:'h'+i},{sourceId:'b',publishedAt:T+i*H+60000,payloadHash:'h'+i}];return e;});const graph=sourceGraph(events);assert.equal(graph.edges[0].status,'DEPENDENCIA_SUSPEITA');assert.equal(graph.edges[0].copyEvidenceRate,1);assert.equal(graph.edges[0].weightApplied,false);delete events[0].evidence[0].publishedAt;assert.equal(sourceGraph(events).edges[0].samples,34);});
test('Shadow source samples remain isolated and cannot confirm events or send alerts',()=>{const s=intelligence(),c=registerCandidate(s.discovery,{name:'New',url:'https://example.org/public'},T);sourceSample(s.discovery,{sourceId:c.id,boss:'A',world:'World',spawnLower:T,spawnUpper:T,detectedAt:T+H},T+2*H);assert.equal(s.events.length,0);assert.equal(c.status,'TESTE');assert.equal(c.productionEligible,false);assert.throws(()=>registerCandidate(s.discovery,{name:'Private',url:'https://127.0.0.1/'},T));});
test('Exact sign test and FDR reject chance discoveries across all attempted hypotheses',()=>{const zero=pairedSign(Array.from({length:30},(_,i)=>({at:T+i*24*H,baseline:.5,signal:.5,y:i%2})));assert.equal(zero.p,1);const experiments=Array.from({length:100},(_,i)=>({test:{p:i===0?.01:1}}));adjustFDR(experiments,'test');assert.equal(experiments[0].test.q,1);const good=pairedSign(Array.from({length:20},(_,i)=>({at:T+i*24*H,baseline:.5,signal:i%2?.9:.1,y:i%2})));assert.ok(good.p<.001);});
test('Walk-forward discovery persists negative results and never promotes a feature',()=>{const s=history(150),r=runDiscovery(s.discovery,'World',s.discovery.analysisAsOf);assert.ok(r.results.length>0);assert.ok(r.results.every(x=>!x.productionEligible));assert.ok(r.results.some(x=>['REJEITADO','AMOSTRA_INSUFICIENTE'].includes(x.status)));const count=s.discovery.experiments.length;runDiscovery(s.discovery,'World',s.discovery.analysisAsOf);assert.equal(s.discovery.experiments.length,count);assert.ok(r.results.every(x=>x.ablation.removedFeature===x.signal));});
test('Relationships without independent observation coverage do not claim occurrence probabilities',()=>{const events=Array.from({length:10},(_,i)=>canonicalEvent(event(i,i%2?'B':'A'),{},T+20*H));const g=bossGraph(events,[],[],'World',T+20*H);assert.ok(g.edges.every(e=>e.windows.every(w=>w.probability==null)));assert.ok(g.edges.every(e=>!e.productionEligible));});
test('Live ranking excludes uncalibrated probabilities and predictability abstains',()=>{const s=history(5);assert.equal(liveProbability(s.discovery,'World','A',s.discovery.analysisAsOf).probability,null);const dashboard=discoveryDashboard(s,'World',s.discovery.analysisAsOf);assert.equal(dashboard.nextBestBoss.length,0);assert.equal(predictability([]).length,0);});
test('Historical simulator cannot view future versions or emit actual alerts',()=>{const s=intelligence();s.events=[event(2)];captureCanonical(s,T+3*H);const result=historicalReplay(s.discovery,'World',T,T+5*H,60);assert.equal(result.timeline[2].events.length,0);assert.equal(result.timeline[3].events.length,1);assert.ok(result.timeline.every(t=>t.alerts.length===0&&t.events.every(e=>e.availableAt<=t.at)));assert.throws(()=>historicalReplay(s.discovery,'World',T,T+25*H,60));});
test('Empty operational datasets display insufficiency and dashboard escapes source content',()=>{const s=intelligence();registerCandidate(s.discovery,{name:'<script>',url:'https://example.org'},T);const d=discoveryDashboard(s,'World',T);assert.equal(d.canonicalEventCount,0);assert.equal(d.experiments.length,0);assert.match(discoveryHtml(d),/&lt;script&gt;/);assert.doesNotMatch(discoveryHtml(d),/<script>/);assert.match(historicalHtml(historicalReplay(s.discovery,'World',T,T+H,60)),/Reprodução/);});
test('Runtime persists discovery independently while preserving legacy API',async()=>{const state={checks:[]};let saves=0;const service=createIntelligence({state,persist:async()=>{saves++;}});assert.equal(typeof service.snapshot,'function');await service.discoveryWrite('candidate',{name:'Public',url:'https://example.org'});assert.equal(saves,1);assert.equal(state.intelligence.events.length,0);assert.equal(service.discovery('World').candidates[0].status,'DESCOBERTA');});
test('Probability metrics quantify prediction rather than descriptive correlation',()=>{const m=probabilityMetrics([{y:1,p:.8},{y:0,p:.2}],'p');assert.ok(Math.abs(m.brier-.04)<1e-10);assert.ok(m.logLoss>0);assert.equal(m.recall,1);assert.equal(probabilities([],{},'weekday').baseline,.5);});
test('A removed spawn cannot create a negative training label before removal became known',()=>{const s=history(10),removed=s.events.find(e=>e.estimatedAt===T+24*H);s.events=s.events.filter(e=>e!==removed);const removalAt=T+110*H;captureCanonical(s,removalAt);const row=buildCases(s.discovery,'World','A').find(r=>r.at===T+18*H);assert.equal(row.y,0);assert.ok(row.knownAt>=removalAt);});
test('Censored empirical curves remain bounded and are never advertised as calibrated',()=>{const s=history(30),events=eventsAsOf(s.discovery,'World',s.discovery.analysisAsOf-11*H),r=spawnDistribution(events,'A',s.discovery.analysisAsOf-11*H);assert.equal(r.status,'EXPERIMENTAL_NAO_CALIBRADO');assert.ok(r.cumulative.every((p,i)=>p.lower>=0&&p.upper<=1&&p.lower<=p.upper&&(!i||p.lower>=r.cumulative[i-1].lower)));assert.equal(spawnDistribution(events,'A',s.discovery.analysisAsOf+100*H).status,'CAUDA_INSUFICIENTE');});
test('One source cannot multiply reputation updates by repeating confirmations',()=>{const e=event(1),a=e.evidence[0];e.evidence=Array.from({length:20},(_,i)=>({...a,evidenceId:'repeat'+i}));e.evidence.push({...a,sourceId:'s2'});const sources={s1:{alpha:4,beta:4,baseWeight:.5},s2:{alpha:4,beta:4,baseWeight:.5}};learnFromEvent(e,sources);assert.equal(sources.s1.alpha+sources.s1.beta,9);});
test('Candidate state transitions reject unvalidated activation and false positives need coverage',()=>{const s=intelligence(),c=registerCandidate(s.discovery,{name:'Candidate',url:'https://example.org/status'},T);reviewCandidate(s.discovery,{sourceId:c.id,status:'EM_ANALISE'},T+H);assert.equal(c.status,'EM_ANALISE');assert.throws(()=>reviewCandidate(s.discovery,{sourceId:c.id,status:'ATIVA'},T+H),/produção/);assert.throws(()=>reviewCandidate(s.discovery,{sourceId:c.id,status:'VALIDADA'},T+H),/50/);sourceSample(s.discovery,{sourceId:c.id,boss:'A',world:'World',spawnLower:T+H,spawnUpper:T+H,detectedAt:T+2*H},T+3*H);assert.equal(evaluateSources(s.discovery,[],T+4*H).find(x=>x.id===c.id).precision,null);addCoverage(s.discovery,{boss:'A',world:'World',startAt:T,endAt:T+3*H,sourceRef:'independent',verified:true,continuous:true},T+3*H);assert.equal(evaluateSources(s.discovery,[],T+4*H).find(x=>x.id===c.id).precision,0);});
test('Monitoring a shadow candidate does not generate negative ground truth',()=>{const s=intelligence(),c=s.discovery.candidates[0];addCoverage(s.discovery,{boss:'A',world:'World',startAt:T,endAt:T+H,sourceRef:'shadow-monitor',candidateId:c.id,verified:true,continuous:true},T+2*H);assert.equal(horizonLabel([],s.discovery.coverage,'A','World',T,H,T+3*H).value,null);});
test('Historical snapshots show only forecasts issued by then and hide appended outcomes',()=>{const s=intelligence(),r={world:'World',boss:'A',forecastId:'f',mode:'Champion',asOf:T+2*H,output:{windowStart:T+4*H,windowEnd:T+6*H,confidence:80},features:{},weights:[],rawPrediction:{},datasetId:'d',actualAt:T+5*H};r.immutableHash=digest({output:r.output,features:r.features,weights:r.weights,rawPrediction:r.rawPrediction,datasetId:r.datasetId,asOf:r.asOf});const result=historicalReplay(s.discovery,'World',T,T+4*H,60,[r]);assert.equal(result.timeline[1].predictions.length,0);assert.equal(result.timeline[2].predictions.length,1);assert.equal(result.timeline[2].predictions[0].actualAt,undefined);r.output.confidence=99;assert.throws(()=>historicalReplay(s.discovery,'World',T,T+4*H,60,[r]),/alterado/);});
test('Legacy identifier collisions across bosses cannot merge their canonical histories',()=>{const s=intelligence(),a=event(1,'A'),b=event(1,'B');b.id=a.id;s.events=[a,b];captureCanonical(s,T+2*H);assert.equal(eventsAsOf(s.discovery,'World',T+3*H).length,2);s.events=[b];captureCanonical(s,T+4*H);assert.deepEqual(eventsAsOf(s.discovery,'World',T+5*H).map(e=>e.boss),['B']);});


test('Boss relationship discovery requires baseline, reports lift and controls false discovery',()=>{
 const asOf=T+50*48*H+12*H,events=[];for(let i=0;i<45;i++){const a=T+i*48*H,b=a+4*H;events.push({id:'ga'+i,boss:'A',world:'World',status:'CONFIRMADO',spawn:{lower:a,upper:a,estimate:a},availableAt:a+1000,evidence:[]});events.push({id:'gb'+i,boss:'B',world:'World',status:'CONFIRMADO',spawn:{lower:b,upper:b,estimate:b},availableAt:b+1000,evidence:[]});}
 events.sort((a,b)=>a.spawn.estimate-b.spawn.estimate);const coverage=[{boss:'B',world:'World',startAt:T,endAt:asOf,knownAt:asOf,verified:true,continuous:true},{boss:'A',world:'World',startAt:T,endAt:asOf,knownAt:asOf,verified:true,continuous:true}],g=bossGraph(events,coverage,[],'World',asOf),edge=g.edges.find(x=>x.from==='A'&&x.to==='B'),w=edge.windows.find(x=>x.fromHours===3&&x.toHours===6);
 assert.ok(g.numberOfTests>0);assert.ok(w.samples>=40);assert.ok(w.baselineSamples>=30);assert.ok(w.conditionalProbability>w.baselineProbability);assert.ok(w.lift>2);assert.ok(Number.isFinite(w.test.q));assert.equal(w.status,'CANDIDATE_RELATIONSHIP');assert.equal(edge.causalityProven,false);
});
test('Temporal Knowledge registry versions relationships and keeps graph features out of production',()=>{
 const s=intelligence(),asOf=T+50*48*H+12*H,events=[];for(let i=0;i<45;i++){const a=T+i*48*H,b=a+4*H;events.push({id:'ka'+i,boss:'A',world:'World',status:'CONFIRMADO',spawn:{lower:a,upper:a,estimate:a},availableAt:a+1000,evidence:[]});events.push({id:'kb'+i,boss:'B',world:'World',status:'CONFIRMADO',spawn:{lower:b,upper:b,estimate:b},availableAt:b+1000,evidence:[]});}
 s.discovery.versions=events.flatMap(e=>[{at:e.availableAt,event:e,hash:'h'+e.id}]);s.discovery.coverage=[{boss:'A',world:'World',startAt:T,endAt:asOf,knownAt:asOf,verified:true,continuous:true},{boss:'B',world:'World',startAt:T,endAt:asOf,knownAt:asOf,verified:true,continuous:true}];ensureTemporalKnowledge(s.discovery,T);const run=refreshTemporalKnowledge(s,'World',asOf),d=temporalKnowledgeDashboard(s,'World',asOf),feature=d.features.find(x=>x.sourceBoss==='A'&&x.targetBoss==='B');
 assert.ok(run.relationshipTests>0);assert.ok(d.counts.discovered>0);assert.ok(feature);assert.equal(feature.status,'DISCOVERED');assert.equal(feature.productionEligible,false);const q=queryTemporalKnowledge(s,'World',{kind:'before',boss:'B'},asOf);assert.ok(q.answer.some(x=>x.sourceEntity.id==='A'));assert.equal(q.evidenceRequired,true);
});


test('As-known-at relationship queries use the relationship version available at that instant',()=>{
 const s=intelligence(),k=ensureTemporalKnowledge(s.discovery,T);k.relationshipRegistry.r1={id:'r1',kind:'boss_to_boss',world:'World',sourceEntity:{type:'Boss',id:'A'},targetEntity:{type:'Boss',id:'B'},window:{fromHours:3,toHours:6},status:'VALIDATED',validFrom:T+H,validUntil:null,discoveredAt:T+H,lastValidated:T+4*H,lastUpdatedAt:T+4*H,metrics:{sampleSize:100,lift:3},lineage:{anchorEventIds:[],targetEventIds:[]},versions:[{version:1,at:T+2*H,status:'DISCOVERED',metrics:{sampleSize:20,lift:1.5}},{version:2,at:T+4*H,status:'VALIDATED',metrics:{sampleSize:100,lift:3}}]};
 const past=temporalKnowledgeDashboard(s,'World',T+3*H),future=temporalKnowledgeDashboard(s,'World',T+5*H);
 assert.equal(past.topRelationships[0].status,'DISCOVERED');assert.equal(past.topRelationships[0].metrics.sampleSize,20);assert.equal(past.topRelationships[0].metrics.lift,1.5);
 assert.equal(future.topRelationships[0].status,'VALIDATED');assert.equal(future.topRelationships[0].metrics.sampleSize,100);assert.equal(future.topRelationships[0].metrics.lift,3);
});


test('Sequence mining compares conditional probability with a baseline and controls false discovery',()=>{
 const events=[];let n=0;for(let cycle=0;cycle<30;cycle++)for(const boss of ['A','B','C','X','B','D']){const at=T+n++*H;events.push({id:'seq-'+n,boss,world:'World',status:'CONFIRMADO',spawn:{lower:at,upper:at,estimate:at},availableAt:at+1000,evidence:[]});}
 const g=bossGraph(events,[],[],'World',T+n*H+H),seq=g.sequences.find(x=>x.pattern==='A → B');
 assert.ok(seq);assert.ok(seq.samples>=30);assert.ok(seq.probability>seq.baselineProbability);assert.ok(seq.lift>2);assert.ok(Number.isFinite(seq.test.q));assert.equal(seq.status,'DISCOVERED');assert.equal(seq.productionEligible,false);assert.equal(seq.causalityProven,false);
});

test('Novel State guard reduces only confidence and abstains when historical states are insufficient',()=>{
 const insufficient=noveltyConfidenceGuard({status:'INSUFFICIENT_HISTORY',samples:4,noveltyScore:.9,similarStates:[],policy:{minHistoricalStates:10,novelStateThreshold:.45,maxConfidencePenalty:40,minConfidenceCap:60}},88);
 assert.equal(insufficient.applied,false);assert.equal(insufficient.adjustedConfidence,88);assert.equal(insufficient.reason,'insufficient_historical_states');
 const known=noveltyConfidenceGuard({status:'KNOWN_STATE',samples:20,noveltyScore:.2,similarStates:[{similarity:.8}],policy:{minHistoricalStates:10,novelStateThreshold:.45,maxConfidencePenalty:40,minConfidenceCap:60}},88);
 assert.equal(known.applied,false);assert.equal(known.adjustedConfidence,88);
 const novel=noveltyConfidenceGuard({status:'NOVEL_STATE',samples:20,noveltyScore:.8,similarStates:[{similarity:.2}],policy:{minHistoricalStates:10,novelStateThreshold:.45,maxConfidencePenalty:40,minConfidenceCap:60}},88);
 assert.equal(novel.applied,true);assert.ok(novel.adjustedConfidence<88);assert.ok(novel.confidenceCap>=60);assert.equal(novel.reason,'novel_server_state');
});

test('Graph Contribution reports paired MAE only for promoted graph holdouts with enough samples',()=>{
 const s=intelligence();ensureTemporalKnowledge(s.discovery,T);s.mlops={lab:{experiments:{
  good:{id:'good',world:'World',boss:'B',kind:'graph_feature',status:'PROMOTED',createdAt:T,promotedAt:T+H,result:{historical:{holdoutImprovementPct:25,historicalGate:{holdout:{champion:{samples:40,maeMinutes:20},challenger:{samples:40,maeMinutes:15}}}}}},
  weak:{id:'weak',world:'World',boss:'C',kind:'graph_feature',status:'PROMOTED',createdAt:T,promotedAt:T+H,result:{historical:{holdoutImprovementPct:50,historicalGate:{holdout:{champion:{samples:5,maeMinutes:20},challenger:{samples:5,maeMinutes:10}}}}}}
 }}};
 const d=temporalKnowledgeDashboard(s,'World',T+2*H);
 assert.equal(d.graphContribution.promotedGraphExperiments,2);assert.equal(d.graphContribution.pairedSamples,40);assert.equal(d.graphContribution.championWithoutGraphMaeMinutes,20);assert.equal(d.graphContribution.graphCandidateMaeMinutes,15);assert.equal(d.graphContribution.validatedMaeGainMinutes,5);assert.equal(d.graphContribution.experiments.length,1);
});

test('Before-Spawn contrastive signals enter Feature Store only as governed hypotheses',()=>{
 const s=intelligence(),asOf=T+46*48*H,events=[];
 for(let i=0;i<45;i++){const b=T+i*48*H+8*H,a=b-4*H;events.push({id:'pre-a'+i,boss:'A',world:'World',status:'CONFIRMADO',spawn:{lower:a,upper:a,estimate:a},availableAt:a+1000,evidence:[]});events.push({id:'pre-b'+i,boss:'B',world:'World',status:'CONFIRMADO',spawn:{lower:b,upper:b,estimate:b},availableAt:b+1000,evidence:[]});}
 events.sort((a,b)=>a.spawn.estimate-b.spawn.estimate);s.discovery.versions=events.map(e=>({at:e.availableAt,event:e,hash:'h'+e.id}));s.discovery.coverage=[{boss:'A',world:'World',startAt:T,endAt:asOf,knownAt:T,verified:true,continuous:true},{boss:'B',world:'World',startAt:T,endAt:asOf,knownAt:T,verified:true,continuous:true}];
 ensureTemporalKnowledge(s.discovery,T);const run=refreshTemporalKnowledge(s,'World',asOf),d=temporalKnowledgeDashboard(s,'World',asOf),feature=d.features.find(x=>x.kind==='before_spawn_contrastive'&&x.sourceBoss==='A'&&x.targetBoss==='B'&&x.windowHours===6),hypothesis=d.hypotheses.find(x=>x.featureId===feature?.id);
 assert.ok(run.beforeSpawnFeatures>0);assert.ok(feature);assert.equal(feature.status,'DISCOVERED');assert.equal(feature.productionEligible,false);assert.ok(feature.metrics.lift>1.5);assert.ok(feature.lineage.positive.length>=20);assert.ok(Number.isFinite(feature.medianDelayHours));assert.equal(d.graphHealth.orphanFeatures,0);
 assert.ok(hypothesis);assert.equal(hypothesis.status,'UNVALIDATED_HYPOTHESIS');assert.equal(hypothesis.modelId,'graph_context_interval');assert.equal(hypothesis.origin,'before_spawn_contrastive');assert.equal(hypothesis.eligibleForExperiment,true);
 const q=queryTemporalKnowledge(s,'World',{kind:'before',boss:'B'},asOf);assert.ok(Array.isArray(q.answer));assert.ok(q.answer.some(x=>x.sourceEntity.id==='A'));assert.ok(q.contrastiveSignals.some(x=>x.sourceBoss==='A'));assert.ok(q.featureHypotheses.some(x=>x.featureId===feature.id));
});

test('Prediction Error graph compares contexts against background without causal or production claims',()=>{
 const s=intelligence();s.forecasts=[];s.mlops={errors:{}};
 for(let i=0;i<80;i++){const risky=i<40,id='errf'+i,resolvedAt=T+(i+1)*H,errorMinutes=risky?(i<30?240:40):(i<45?240:40);s.forecasts.push({id,boss:'Boss',world:'World',resolvedAt,activeModel:risky?'risky_model':'stable_model',drift:{score:risky?55:10},noveltySafety:{status:risky?'NOVEL_STATE':'KNOWN_STATE'},graphContext:{graphApplied:false},operationalSafety:{level:'NORMAL'},selfCritique:{reasons:risky?['drift']:[]}});s.mlops.errors[id]={id:'error_'+id,forecastId:id,boss:'Boss',world:'World',errorMinutes,resolvedAt,causes:risky?['drift']:['unexplained_interval_variation']};}
 const d=predictionErrorRelationshipAnalysis(s,'World',T+100*H),r=d.relationships.find(x=>x.dimension==='model'&&x.value==='risky_model');
 assert.equal(d.status,'MEASURED');assert.equal(d.samples,80);assert.ok(d.baselineLargeErrorRate>.4&&d.baselineLargeErrorRate<.5);assert.ok(r);assert.equal(r.status,'CANDIDATE_ASSOCIATION');assert.ok(r.riskRatio>3);assert.ok(r.test.q<=.05);assert.equal(r.productionEligible,false);assert.equal(r.causalityProven,false);assert.equal(r.direction,'HIGHER_ERROR_RISK');assert.ok(r.lineage.largeErrorForecastIds.length>=20);
});

test('Relationship evolution exposes lift decay and status transitions without production claims',()=>{
 const s=intelligence(),k=ensureTemporalKnowledge(s.discovery,T);k.relationshipRegistry.evo={id:'evo',kind:'boss_to_boss',world:'World',sourceEntity:{type:'Boss',id:'A'},targetEntity:{type:'Boss',id:'B'},window:{fromHours:0,toHours:6},status:'DEGRADED',validFrom:T,validUntil:null,discoveredAt:T,lastValidated:T+3*H,lastUpdatedAt:T+3*H,metrics:{sampleSize:80,lift:1.2,driftScore:.4},lineage:{anchorEventIds:[],targetEventIds:[]},versions:[{version:1,at:T+H,status:'DISCOVERED',metrics:{sampleSize:40,lift:2.4,driftScore:0}},{version:2,at:T+2*H,status:'VALIDATED',metrics:{sampleSize:60,lift:2.0,driftScore:.1}},{version:3,at:T+3*H,status:'DEGRADED',metrics:{sampleSize:80,lift:1.2,driftScore:.4}}]};
 const d=temporalKnowledgeDashboard(s,'World',T+4*H),row=d.relationshipEvolution.find(x=>x.id==='evo'),q=queryTemporalKnowledge(s,'World',{kind:'drift'},T+4*H);
 assert.ok(row);assert.equal(row.driftDetected,true);assert.equal(row.currentStatus,'DEGRADED');assert.ok(row.recentLiftChangePct<=-40);assert.ok(row.liftChangeFromFirstPct<=-50);assert.equal(row.productionEligible,false);assert.equal(row.causalityProven,false);assert.ok(Array.isArray(q.answer));assert.ok(q.evolution.some(x=>x.id==='evo'));
});

test('Confirmation Latency graph finds slow sources without changing source weights',()=>{
 const s=intelligence();s.sources={fast:{name:'Fast'},slow:{name:'Slow'}};s.events=[];
 for(let i=0;i<40;i++){const at=T+i*3*H,fastDelay=i<2?90:10,slowDelay=i<35?120:20;s.events.push({id:'lat'+i,boss:'Boss',world:'World',estimatedAt:at,status:'confirmed_auto',eventType:'appearance',qualityStatus:'CONFIRMADO',evidence:[{evidenceId:'fast'+i,sourceId:'fast',collectedAt:at+fastDelay*60000,processedAt:at+fastDelay*60000,reportedAt:at+fastDelay*60000,quality:{traceable:true,status:'CONFIRMADO'}},{evidenceId:'slow'+i,sourceId:'slow',collectedAt:at+slowDelay*60000,processedAt:at+slowDelay*60000,reportedAt:at+slowDelay*60000,quality:{traceable:true,status:'CONFIRMADO'}}]});}
 const d=confirmationLatencyAnalysis(s,'World',T+200*H),slow=d.sources.find(x=>x.sourceId==='slow'),q=queryTemporalKnowledge(s,'World',{kind:'confirmations'},T+200*H);
 assert.equal(d.status,'MEASURED');assert.equal(d.samples,80);assert.ok(slow);assert.equal(slow.status,'SLOW_ASSOCIATION');assert.ok(slow.riskRatio>10);assert.ok(slow.test.q<=.05);assert.equal(slow.productionEligible,false);assert.equal(slow.weightAdjustment,null);assert.equal(slow.causalityProven,false);assert.ok(q.answer.some(x=>x.sourceId==='slow'));
});

test('Temporal Causal Lab requires matching, balance, FDR, reverse placebo and stability before CAUSAL_CANDIDATE',()=>{
 const s=intelligence(),events=[],asOf=T+130*24*H;
 for(let i=0;i<40;i++){const a=T+24*H+i*72*H;events.push({id:'ca'+i,boss:'A',world:'World',status:'CONFIRMADO',spawn:{lower:a,upper:a,estimate:a},availableAt:a+1000,evidence:[]});if(i<32){const b=a+4*H;events.push({id:'cb'+i,boss:'B',world:'World',status:'CONFIRMADO',spawn:{lower:b,upper:b,estimate:b},availableAt:b+1000,evidence:[]});}}
 events.sort((a,b)=>a.spawn.estimate-b.spawn.estimate);s.discovery.versions=events.map(e=>({at:e.availableAt,event:e,hash:'c'+e.id}));s.discovery.coverage=[{boss:'A',world:'World',startAt:T,endAt:asOf,knownAt:T,verified:true,continuous:true},{boss:'B',world:'World',startAt:T,endAt:asOf,knownAt:T,verified:true,continuous:true}];
 const relation={id:'causal-rel',world:'World',sourceEntity:{type:'Boss',id:'A'},targetEntity:{type:'Boss',id:'B'},window:{fromHours:3,toHours:6},status:'DISCOVERED',metrics:{sampleSize:40,direction:'POSITIVE',adjustedSignificance:.001,qualityScore:95}};
 const lab=causalDiscoveryLab(s,'World',asOf,{relationships:[relation],maxRelations:1,caliper:.35}),r=lab.results[0];
 assert.ok(r);assert.ok(r.matchedPairs>=20);assert.ok(r.matchRate>=.6);assert.ok(r.balance.maxAbsSmd<=.25);assert.ok(r.averageTreatmentEffectOnTreated>.5);assert.ok(r.causalTest.q<=.05);assert.ok(r.placeboTest.q>.05);assert.ok(r.stability.passed);assert.equal(r.status,'CAUSAL_CANDIDATE');assert.equal(r.evidenceLevel,'MATCHED_OBSERVATIONAL_WITH_PLACEBO');assert.equal(r.causalityProven,false);assert.equal(r.productionEligible,false);assert.equal(r.aiLabPromotionEligible,false);assert.equal(r.identificationAssumptions.unmeasuredConfoundingResolved,false);
});

