const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=n=>n==null?'Indisponível':(100*n).toFixed(1)+'%';
const time=n=>n==null?'Desconhecido':new Date(n).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'});
const table=(head,rows)=>'<div class="table-wrap"><table class="ranking-table intelligence-table"><thead><tr>'+head.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
function completionHtml(d){
 const policies=d.policies||[],sourceOptions=(d.candidates||[]).map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join('');
 return '<h3>Coleta pública e governança</h3><p>Coleta respeita acesso público e robots.txt. Publicações sobre manutenção permanecem anúncios até confirmação de execução. Token do Discord fica no ambiente do servidor.</p>'+
 '<div class="simulation-controls"><button class="secondary" data-intel-action="discovery-collect">Pesquisar fontes públicas</button><button class="secondary" data-intel-action="discovery-automatic">Ativar coleta pública a cada hora</button><button class="secondary" data-intel-action="discovery-stop">Pausar coleta automática</button><label>Fonte para coletor<select id="completion-source">'+sourceOptions+'</select></label><label>Formato<select id="completion-collector"><option value="public_page">Página pública</option><option value="public_boss_json">JSON de spawns explícitos</option></select></label><label><input id="completion-public" type="checkbox">Verifiquei que o acesso é público e permitido</label><button class="secondary" data-intel-action="discovery-collector">Configurar coleta</button></div>'+
 '<div class="simulation-controls"><label>Política<select id="completion-policy">'+policies.map(p=>'<option value="'+esc(p.id)+'">'+esc((p.boss||p.sourceId)+' · '+p.status)+'</option>').join('')+'</select></label><button class="secondary" data-intel-action="discovery-advance">Avaliar próxima etapa</button><label>Hora do server save (Brasília, 0–23.99)<input id="completion-save" type="number" min="0" max="23.99" step="0.01"></label><label>Origem verificada<input id="completion-save-ref"></label><button class="secondary" data-intel-action="discovery-schedule">Registrar ciclo conhecido</button><label>Canal Discord autorizado<input id="completion-channel" inputmode="numeric"></label><label><input id="completion-authorized" type="checkbox">Integração autorizada neste canal</label><button class="secondary" data-intel-action="discovery-discord">Registrar integração</button><button class="secondary" data-intel-action="discovery-discord-collect">Coletar mensagens autorizadas</button></div>'+
 table(['Política','Tipo','Boss / fonte','Etapa','Canário','Produção'],policies.map(p=>[p.id,p.kind,p.boss||p.sourceId,p.status,pct(p.percentage/100),p.productionEligible?'Elegível':'Aguarda gates']))+
 '<p>Previsões prospectivas emitidas: '+esc(d.prospectiveSummary?.issued||0)+' · resolvidas com cobertura: '+esc(d.prospectiveSummary?.resolved||0)+'</p>'+
 '<h3>Regimes e breakpoints</h3>'+table(['Boss','Mudança histórica','Detectada em','Mediana antes / depois','q'],(d.regimes?.breakpoints||[]).map(p=>[p.boss,time(p.breakAt),time(p.detectedAt),p.medianBeforeHours.toFixed(2)+' / '+p.medianAfterHours.toFixed(2)+' h',p.test.q.toFixed(4)]))+
 '<h3>Clusters descritivos</h3>'+table(['Grupo','Representante','Bosses','Variabilidade'],(d.clusters?.clusters||[]).map(c=>[c.id,c.representative,c.members.join(', '),c.variability.toFixed(3)]))+
 '<h3>Ablação multivariada</h3>'+table(['Boss','Feature removida','Brier completo','Brier sem feature'],(d.experiments||[]).flatMap(e=>Array.isArray(e.ablation)?e.ablation.map(a=>[e.boss,a.feature,a.withBrier?.toFixed(4)??'—',a.withoutBrier?.toFixed(4)??'—']):[]))+
 '<h3>Distribuição calibrada por horizonte</h3>'+(d.survivalForecasts||[]).slice(0,30).map(p=>'<details><summary>'+esc(p.boss)+' · '+esc(p.status)+'</summary>'+table(['Horizonte','Probabilidade acumulada','Amostra','Status'],(p.horizons||[]).map(h=>[h.hours+'h',pct(h.probability),h.samples,h.status]))+(p.bins?.length?'<svg viewBox="0 0 720 180" role="img" aria-label="Distribuição probabilística calibrada" style="width:100%;max-height:180px">'+p.bins.map((b,i)=>'<rect x="'+(i*110+10)+'" y="'+(160-b.probability*140)+'" width="85" height="'+(b.probability*140)+'" fill="currentColor"><title>'+esc(time(b.from)+' – '+time(b.to)+' · '+pct(b.probability))+'</title></rect>').join('')+'</svg><p>Massa restante após 72h: '+pct(p.remainingMass)+'</p>':'<p>Aguardando calibração e cobertura suficientes.</p>')+'</details>').join('')+
 '<h3>Informações públicas encontradas</h3>'+table(['Publicado','Disponível ao sistema','Categoria','Informação'],(d.publications||[]).map(p=>[time(p.publishedAt||p.publishedLower),time(p.availableAt),p.category,p.title]))+
 '<h3>Knowledge Graph</h3><p>'+esc(d.knowledge?.totalNodes||0)+' nós · '+esc(d.knowledge?.totalEdges||0)+' conexões de proveniência.</p>'+table(['Tipo','Identificador'],(d.knowledge?.nodes||[]).map(n=>[n.type,n.key]))+
 '<h3>Red Team</h3><button class="secondary" data-intel-action="discovery-red-team">Executar ataques em cópia isolada</button><p>'+esc(d.redTeam?.status||'Aguardando execução com histórico real')+'</p>'+table(['Ataque','Resultado'],(d.redTeam?.checks||[]).map(c=>[c.name,c.passed?'Resistiu':'Falhou']))+
 '<h3>Coletas recentes</h3>'+table(['Data','Resultados'],(d.collectionRuns||[]).map(r=>[time(r.at),r.results.map(x=>x.status+(x.reason?' · '+x.reason:'')).join('; ')]));
}
function graph(g){const nodes=(g.nodes||[]).slice(0,30);if(!nodes.length)return '<p>Amostra insuficiente para construir o grafo.</p>';const width=720,height=Math.max(180,nodes.length*35),pos=new Map(nodes.map((n,i)=>[n,{x:160+(i%2)*400,y:35+Math.floor(i/2)*60}]));
 const edges=(g.edges||[]).filter(e=>pos.has(e.from)&&pos.has(e.to)).slice(0,100);return '<svg viewBox="0 0 '+width+' '+height+'" role="img" aria-label="Grafo de relações em avaliação" style="width:100%;max-height:500px"><defs><marker id="discovery-arrow-'+nodes.length+'" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="currentColor"/></marker></defs>'+edges.map(e=>{const a=pos.get(e.from),b=pos.get(e.to);return '<path d="M'+a.x+','+a.y+' Q360,'+(a.y+b.y)/2+' '+b.x+','+b.y+'" fill="none" stroke="currentColor" opacity=".3" marker-end="url(#discovery-arrow-'+nodes.length+')"><title>'+esc(e.from+' → '+e.to+' · '+(e.status||'DESCRITIVO'))+'</title></path>';}).join('')+nodes.map(n=>{const p=pos.get(n);return '<g><circle cx="'+p.x+'" cy="'+p.y+'" r="8" fill="currentColor"/><text x="'+(p.x+12)+'" y="'+(p.y+4)+'" font-size="12" fill="currentColor">'+esc(n)+'</text></g>';}).join('')+'</svg><p class="muted">Até 30 nós exibidos. Setas representam hipóteses; aprovação preditiva consta na tabela.</p>';}
export function discoveryHtml(d){
 return '<h3>DATA INTELLIGENCE · '+esc(d.world)+'</h3><p>'+esc(d.canonicalEventCount)+' spawns canônicos elegíveis · '+esc(d.coverageSessions)+' sessões de cobertura verificada.</p>'+completionHtml(d)+'<h3>Top descobertas</h3>'+(d.topDiscoveries?.length?'<ul>'+d.topDiscoveries.map(x=>'<li>'+esc(x.text)+'</li>').join('')+'</ul>':'<p>Nenhuma melhoria comprovada fora da amostra.</p>')+
 '<h3>Sinais, comparação e ablação</h3>'+table(['Boss','Sinal','Status','Amostras','Brier sem / com','Ganho no teste','FDR q','Ablação Δ Brier'],(d.experiments||[]).slice(0,200).map(e=>[e.boss,e.signal,e.status,e.samples,(e.test.without.brier?.toFixed(4)??'—')+' / '+(e.test.withSignal.brier?.toFixed(4)??'—'),pct(e.test.gain),e.test.q?.toFixed(4),e.ablation?.lossIncrease?.toFixed(4)??'—']))+
 '<h3>Boss Relationship Graph</h3>'+graph(d.bossGraph||{})+table(['Relação','Janela','Ocorrências / amostra','Baseline','Condicional','Lift','FDR q','Status'],(d.bossGraph?.edges||[]).slice(0,100).flatMap(e=>e.windows.map(w=>[e.from+' → '+e.to,w.fromHours+'–'+w.toHours+'h',w.occurrences+' / '+w.samples,pct(w.baselineProbability),pct(w.conditionalProbability),w.lift==null?'—':Number(w.lift).toFixed(2)+'x',w.test?.q==null?'—':Number(w.test.q).toFixed(4),w.status])))+
 '<h3>Sequências em pesquisa</h3>'+table(['Sequência','Ocorrências','Status'],(d.bossGraph?.sequences||[]).slice(0,100).map(s=>[s.pattern,s.occurrences,s.status]))+
 '<h3>Source Dependency Graph</h3><label>Relação em Shadow<select id="completion-dependency">'+(d.dependencyPolicies||[]).map(p=>'<option value="'+esc(p.id)+'">'+esc(p.from+' → '+p.to+' · '+p.status)+'</option>').join('')+'</select></label><button class="secondary" data-intel-action="discovery-dependency">Avaliar limite conjunto de evidência</button>'+graph(d.sourceGraph||{})+table(['Relação','Amostra','Conteúdo idêntico','Atraso médio','Status','Peso aplicado'],(d.sourceGraph?.edges||[]).slice(0,100).map(e=>[e.from+' → '+e.to,e.samples,pct(e.copyEvidenceRate),e.meanLagMinutes==null?'Desconhecido':e.meanLagMinutes.toFixed(2)+' min',e.status,e.weightApplied?'Sim':'Não; aguarda validação']))+
 '<h3>Latência das fontes</h3>'+table(['Fonte','Amostras precisas','Média','Mediana'],(d.sourceGraph?.latencies||[]).map(s=>[s.sourceId,s.samples,s.meanMinutes.toFixed(2)+' min',s.medianMinutes.toFixed(2)+' min']))+
 '<h3>Fontes candidatas em Shadow</h3>'+table(['Fonte','URL','Status','Amostras','Correspondências independentes','Pendentes','Precisão'],(d.candidates||[]).map(s=>[s.name,s.url,s.status,s.samples,s.independentlyMatched,s.unresolved,pct(s.precision)]))+
 '<div class="simulation-controls"><label>Fonte<select id="discovery-candidate">'+(d.candidates||[]).map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join('')+'</select></label><label>Estado<select id="discovery-candidate-state">'+['EM_ANALISE','TESTE','VALIDADA','BAIXA_QUALIDADE','BLOQUEADA','DESCARTADA'].map(s=>'<option>'+esc(s)+'</option>').join('')+'</select></label><button class="secondary" data-intel-action="source-review">Registrar avaliação</button></div>'+
 '<h3>Registrar informação verificada</h3><p>Horários de Brasília. Cobertura significa observação contínua, sem lacunas; uma checagem isolada não serve.</p><div class="simulation-controls"><label>Boss<input id="discovery-boss" maxlength="140"></label><label>Início / spawn mínimo<input id="discovery-start" type="datetime-local"></label><label>Fim / spawn máximo<input id="discovery-end" type="datetime-local"></label><label>Origem<input id="discovery-ref" maxlength="500"></label><label>Tipo de contexto<select id="discovery-context-type">'+['server_save','restart','maintenance','update','hotfix','special_event','reset'].map(s=>'<option>'+s+'</option>').join('')+'</select></label><button class="secondary" data-intel-action="context-register">Registrar acontecimento</button><label><input id="discovery-continuous" type="checkbox">Confirmo cobertura contínua, verificada e independente das fontes em teste</label><button class="secondary" data-intel-action="coverage-register">Registrar cobertura</button><label>Primeira detecção da fonte<input id="discovery-detected" type="datetime-local"></label><button class="secondary" data-intel-action="sample-register">Adicionar amostra à fonte selecionada em Shadow</button></div>'+
 '<h3>Bosses mais prováveis · próximas 6h</h3>'+(d.nextBestBoss?.length?table(['Boss','Probabilidade calibrada','Amostras'],d.nextBestBoss.map(p=>[p.boss,pct(p.probability),p.samples])):'<p>Ranking indisponível: calibração fora da amostra ainda insuficiente.</p>')+
 '<h3>Live Probability · avaliação</h3>'+table(['Boss','Status','Probabilidade','Amostras de calibração'],(d.live||[]).map(p=>[p.boss,p.status,pct(p.probability),p.calibrationSamples??0]))+
 '<h3>Distribuição temporal com incerteza</h3>'+(d.distributions||[]).slice(0,30).map(p=>'<details><summary>'+esc(p.boss)+' · '+esc(p.status)+'</summary><p>'+esc(p.reason||'Amostra insuficiente')+'</p>'+(p.cumulative?.length?'<svg viewBox="0 0 720 180" role="img" aria-label="Limites de probabilidade empírica acumulada" style="width:100%;max-height:180px"><polyline fill="none" stroke="currentColor" stroke-width="2" points="'+p.cumulative.map(v=>(10+v.hours/72*690)+','+(160-v.lower*140)).join(' ')+'"/><polyline fill="none" stroke="currentColor" stroke-dasharray="5 4" points="'+p.cumulative.map(v=>(10+v.hours/72*690)+','+(160-v.upper*140)).join(' ')+'"/><text x="10" y="177" fill="currentColor" font-size="12">Agora → 72h · limite inferior contínuo / superior tracejado</text></svg>':'')+'</details>').join('')+
 '<h3>Predictability Score</h3>'+table(['Boss','Score de skill / 100','Status','Horizonte útil'],(d.predictability||[]).map(p=>[p.boss,p.score??'Indisponível',p.status,p.usefulHorizonHours==null?'Não comprovado':p.usefulHorizonHours+'h']))+
 '<h3>Eventos canônicos e timestamps</h3>'+table(['Boss','Spawn / intervalo','Primeira detecção','Publicação','Coleta','Confirmação','Fontes / independentes'],(d.events||[]).slice(-30).reverse().map(e=>[e.boss,time(e.spawn.lower)+' – '+time(e.spawn.upper),time(e.firstDetectionAt),time(e.firstPublicationAt),time(e.firstCollectionAt),time(e.firstConfirmationAt),e.sourceCount+' / '+e.independentSourceCount]))+
 '<h3>Limitações atuais</h3><ul>'+(d.limitations||[]).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';
}
export function historicalHtml(r){return '<h3>Reprodução histórica</h3><p>'+esc(r.limitation)+'</p>'+table(['Instante','Eventos disponíveis','Previsões já emitidas','Probabilidades elegíveis','Alertas'],r.timeline.map(t=>[time(t.at),t.events.length,t.predictions?.length??0,t.probabilities.filter(p=>p.status==='CALIBRADO').length,t.alertsStatus]));}
