import {parseGroupText,brasiliaDate} from './group-checks.mjs';
import {status} from './logic.mjs';
const $=id=>document.getElementById(id),safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let getModel,getBosses,post,reload,notify,rows=[],batchId=null,selectedWorld=null;
const choices=(values,selected)=>values.map(([v,label])=>`<option value="${v}" ${v===selected?'selected':''}>${label}</option>`).join('');
export function groupNote(pattern){if(!pattern)return '';const r=pattern.recommended;return `<div class="group-note"><b>Checagens do grupo</b><span>${pattern.found} encontros em ${pattern.total} períodos checados · ${pattern.days} dias.</span>${r?`<strong>Priorize ${String(r.start).padStart(2,'0')}h–${String(r.end).padStart(2,'0')}h nas próximas checagens.</strong>`:'<small>Coletando dados para comparar horários.</small>'}</div>`;}
export function initGroupUI(options){({getModel,getBosses,post,reload,notify}=options);$('group-date').value=brasiliaDate();
 $('group-parse').addEventListener('click',()=>{try{rows=parseGroupText($('group-text').value,getBosses().map(b=>b.name),{date:$('group-date').value,time:$('group-time').value,result:$('group-default').value}).map(enrich);batchId=crypto.randomUUID();renderPreview();}catch(e){notify(e.message);}});
 $('group-favorable').addEventListener('click',()=>{const added=getBosses().filter(b=>status(b.prediction)==='high').map(b=>enrich({boss:b.name,text:b.name,result:'',date:$('group-date').value,time:$('group-time').value,favorable:'unknown'}));rows.push(...added.filter(a=>!rows.some(r=>r.boss===a.boss&&r.date===a.date&&r.time===a.time)));batchId=crypto.randomUUID();renderPreview();if(!added.length)notify('Nenhum boss está em dia favorável neste mundo agora.');});
 $('group-add').addEventListener('click',()=>{const name=$('group-boss').value.trim();if(!name)return;rows.push(enrich({boss:name,text:name,result:'',date:$('group-date').value,time:$('group-time').value,favorable:'unknown'}));$('group-boss').value='';batchId=crypto.randomUUID();renderPreview();});
 $('group-preview').addEventListener('change',e=>{const i=Number(e.target.dataset.row),field=e.target.dataset.groupField;if(!field)return;rows[i][field]=e.target.value;batchId=crypto.randomUUID();updateSave();});
 $('group-preview').addEventListener('click',e=>{const b=e.target.closest('[data-remove-group]');if(!b)return;rows.splice(Number(b.dataset.removeGroup),1);batchId=crypto.randomUUID();renderPreview();});
 for(const [id,result] of [['group-all-empty','vazio'],['group-all-found','encontrado']])$(id).addEventListener('click',()=>{rows=rows.map(r=>({...r,result}));batchId=crypto.randomUUID();renderPreview();});
 $('group-world').addEventListener('change',()=>{selectedWorld=$('group-world').value;batchId=crypto.randomUUID();rows=rows.map(r=>({...r,favorable:'unknown'}));renderPreview();});
 $('group-save').addEventListener('click',async()=>{const button=$('group-save');button.disabled=true;try{const result=await post('/api/group-checks',{batchId,world:selectedWorld||getModel().settings.world,rows});rows=[];batchId=null;$('group-text').value='';renderPreview();await reload();notify(`${result.added} checagens salvas${result.duplicates?' · '+result.duplicates+' repetidas ignoradas':''}. Suas kills foram mantidas.`);}catch(e){notify(e.message);}finally{updateSave();}});
 $('group-clear').addEventListener('click',()=>{rows=[];batchId=null;$('group-text').value='';renderPreview();});
 $('group-history').addEventListener('click',async e=>{const b=e.target.closest('[data-undo-group]');if(!b)return;b.disabled=true;try{await post('/api/group-checks/undo',{batchId:b.dataset.undoGroup});await reload();notify('Rodada desfeita e padrões recalculados.');}catch(e){notify(e.message);b.disabled=false;}});
 $('group-export').addEventListener('click',async()=>{try{const r=await fetch('/api/group-checks');if(!r.ok)throw new Error('Histórico indisponível');const data=await r.json(),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='checagens-do-grupo.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){notify(e.message);}});
}
function enrich(row){const m=getModel(),b=getBosses().find(b=>b.name===row.boss);return {...row,favorable:row.date===brasiliaDate()&&(selectedWorld||m.settings.world)===m.settings.world&&!m.error&&status(b?.prediction)==='high'?'yes':row.favorable||'unknown'};}
function updateSave(){const names=getBosses().map(b=>b.name);$('group-save').disabled=!rows.length||rows.some(r=>!names.includes(r.boss)||!r.result||!r.date);$('group-preview-count').textContent=rows.length?`${rows.length} checagens para conferir. Não encontrado significa que foi checado, não que deixou de aparecer no dia.`:'';}
function renderPreview(){
 $('group-preview-wrap').hidden=!rows.length;$('group-preview').innerHTML=rows.map((r,i)=>`<tr><td><input list="group-boss-names" data-row="${i}" data-group-field="boss" aria-label="Boss da linha ${i+1}" value="${safe(r.boss||r.text)}">${!r.boss?'<small class="unmatched">Confira o nome ou remova esta linha</small>':''}</td><td><select data-row="${i}" data-group-field="result" aria-label="Resultado da linha ${i+1}">${choices([['','Escolher'],['vazio','Não estava'],['encontrado','Estava']],r.result)}</select></td><td><input type="date" data-row="${i}" data-group-field="date" value="${safe(r.date)}" aria-label="Data da linha ${i+1}"><input type="time" data-row="${i}" data-group-field="time" value="${safe(r.time)}" aria-label="Horário da linha ${i+1}"></td><td><select data-row="${i}" data-group-field="favorable" aria-label="Dia favorável da linha ${i+1}">${choices([['unknown','Não sei'],['yes','Sim'],['no','Não']],r.favorable)}</select></td><td><button class="secondary" data-remove-group="${i}" aria-label="Remover linha ${i+1}">×</button></td></tr>`).join('');updateSave();
}
export function renderGroupUI(){const m=getModel();if(!selectedWorld)selectedWorld=m.settings.world;$('group-world').innerHTML=m.worlds.map(w=>`<option ${w===selectedWorld?'selected':''}>${safe(w)}</option>`).join('');$('group-boss-names').innerHTML=getBosses().map(b=>`<option value="${safe(b.name)}">`).join('');
 $('group-patterns').innerHTML=(m.groupPatterns||[]).length?`<div class="table-wrap"><table class="ranking-table"><thead><tr><th>Boss</th><th>Encontros / períodos checados</th><th>Em dias favoráveis</th><th>Em outros dias</th><th>Horário para priorizar</th></tr></thead><tbody>${m.groupPatterns.map(p=>`<tr><td>${safe(p.boss)}<small>${p.days} dias observados</small></td><td>${p.found} / ${p.total}</td><td>${p.favorable.found} / ${p.favorable.total}</td><td>${p.notFavorable.found} / ${p.notFavorable.total}</td><td>${p.recommended?`${p.recommended.start}h–${p.recommended.end}h`:'Ainda sem comparação suficiente'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Os padrões aparecerão depois da primeira rodada salva.</p>';
 const batches=new Map();for(const c of m.groupChecks||[]){if(!batches.has(c.batchId))batches.set(c.batchId,[]);batches.get(c.batchId).push(c);} $('group-history').innerHTML=[...batches].slice(0,20).map(([id,checks])=>`<div class="group-round"><div><b>${safe(checks[0].world)} · ${safe(checks[0].date)}</b><p>${checks.map(c=>`${safe(c.boss)}: ${c.result==='encontrado'?'estava':'não estava'}${c.time?' às '+safe(c.time):' · sem horário'}`).join(' · ')}</p></div><button class="secondary" data-undo-group="${safe(id)}">Desfazer rodada</button></div>`).join('')||'<p class="muted">Nenhuma rodada do grupo salva.</p>';
}
