import {discoveryHtml,historicalHtml} from './discovery-ui.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dt=v=>Number.isFinite(Number(v))?new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(Number(v))):'—';
const sourceRefHtml=(ref,fallback='')=>{const raw=String(ref||'').trim(),known=raw&& !/^(?:unknown|n\/a)$/i.test(raw);if(!known)return '<strong class="source-error">ORIGEM NÃO RASTREÁVEL · QUARENTENA</strong>';if(/^https?:\/\//i.test(raw))return '<a href="'+esc(raw)+'" target="_blank" rel="noreferrer noopener">'+esc(raw)+'</a>';return '<code>'+esc(raw||fallback)+'</code>';};
const duration=ms=>{if(!Number.isFinite(ms))return '—';const d=ms/86400000;if(d>=2)return d.toFixed(1)+' dias';const h=ms/3600000;if(h>=2)return h.toFixed(1)+' h';return Math.round(ms/60000)+' min';};
const eventLabel={confirmed_manual:'CONFIRMADO MANUAL',confirmed_auto:'CONFIRMADO AUTO',probable:'PROVÁVEL',unconfirmed:'NÃO CONFIRMADO'};
const sourceState=s=>!s.active?'PREPARADO':s.circuitState==='OPEN'?'QUARENTENA':s.circuitState==='HALF_OPEN'?'RECUPERAÇÃO':s.lastAttempt&&Date.now()-s.lastAttempt<15*60000?(s.lastError?'ERRO':'ONLINE'):s.lastSuccess?'SEM CONSULTA RECENTE':'AGUARDANDO';
const periods=[['days7','7 dias'],['days30','30 dias'],['days90','90 dias'],['all','Histórico total']];
function mlopsHtml(d){return '<h3>Registro de modelos</h3><div class="table-wrap"><table class="ranking-table"><thead><tr><th>Modelo</th><th>Versão</th><th>Status</th><th>Amostras</th><th>Erro médio</th><th>Gate</th></tr></thead><tbody>'+(d.registry||[]).map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+esc(x.version)+'</td><td>'+esc(x.status)+'</td><td>'+esc(x.metrics?.samples??0)+'</td><td>'+esc(x.metrics?.maeMinutes==null?'Indisponível':x.metrics.maeMinutes.toFixed(1)+' min')+'</td><td>'+esc(x.lastGate?.reasons?.join(' · ')||'Aguardando validação')+'</td></tr>').join('')+'</tbody></table></div><p>Datasets registrados: '+esc(d.datasets?.length||0)+' · propostas de aprendizado: '+esc(d.pendingUpdates||0)+'</p><h3>Relatório de inteligência</h3><p>Maior problema atual: '+esc(d.report?.largestProblem)+'</p><h3>Features e horizontes por boss</h3>'+(d.bosses||[]).slice(0,50).map(x=>'<details><summary>'+esc(x.boss)+' · '+esc(x.features.samples)+' eventos rastreáveis</summary><p>Drift: '+esc(x.features.driftScore)+' · importância: '+esc(x.importance.status)+'</p><p>'+(x.survival.horizons||[]).map(h=>'Próximas '+esc(h.hours)+'h: '+esc((h.probability*100).toFixed(1))+'% (intervalo '+esc((h.ci95[0]*100).toFixed(1))+'–'+esc((h.ci95[1]*100).toFixed(1))+'%)').join(' · ')+'</p><p>'+esc(x.survival.status==='ready'?'Probabilidade condicional à ausência de nova confirmação.':'Probabilidade por horizonte indisponível: '+x.survival.status)+'</p><p>'+esc((x.patterns||[]).map(p=>p.description+' · '+p.status).join(' · '))+'</p></details>').join('')+'<h3>Features documentadas</h3><dl>'+Object.entries(d.features||{}).map(([k,v])=>'<dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd>').join('')+'</dl><h3>Causas prováveis dos erros</h3><p>'+esc(Object.entries(d.errorCauses||{}).map(([k,v])=>k+': '+v).join(' · ')||'Sem erros resolvidos')+'</p><h3>Timeline de aprendizado</h3><ul>'+(d.timeline||[]).slice(-20).reverse().map(x=>'<li>'+esc(dt(x.at))+' · '+esc(x.type)+' · '+esc(x.boss||x.modelId||'')+'</li>').join('')+'</ul>';}
export function renderIntelligence(model){
 const root=document.getElementById('intelligence-content');if(!root)return;
 const intel=model.intelligence||{},m=intel.metrics||{},perf=intel.performance||{},perfAll=intel.performanceAllVersions||{},preds=intel.predictions||[],sources=intel.sources||[],events=intel.events||[],models=intel.models||[],trust=intel.trustCenter||{},quality=trust.quality||{},cal=trust.calibration||{},obs=intel.observability||{};
 root.innerHTML=`
 <section class="group-panel"><div class="eyebrow">DESCOBERTA DE SINAIS</div><h2>DATA INTELLIGENCE</h2><p>Investigar informações anteriores ao spawn. Novos sinais permanecem em avaliação.</p><div class="card-actions"><button class="secondary" data-intel-action="discovery">Atualizar painel</button><button class="secondary" data-intel-action="discover">Pesquisar sinais</button></div><div class="simulation-controls"><label>Fonte candidata<input id="discovery-source-name" maxlength="140" placeholder="Nome da fonte"></label><label>URL pública<input id="discovery-source-url" type="url" placeholder="https://"></label><button class="secondary" data-intel-action="candidate">Registrar em Shadow</button></div><div class="simulation-controls"><label>Dia histórico<input id="discovery-day" type="date"></label><button class="secondary" data-intel-action="historical">Reproduzir dia</button></div><div id="discovery-content"><p>Carregue o painel para consultar evidências reais e amostras insuficientes.</p></div><div id="discovery-historical"></div></section>
 <section class="group-panel"><div class="eyebrow">CENTRAL DE INTELIGÊNCIA</div><h2>Modelos, datasets e aprendizado controlado</h2><p class="muted">Modelos novos começam em Shadow. A promoção exige comparação temporal e qualidade comprovada.</p><div class="card-actions"><button class="secondary" data-intel-action="mlops">Atualizar Central de Inteligência</button><button class="secondary" data-intel-action="experiment" data-model="robust_interval">Testar intervalo robusto</button><button class="secondary" data-intel-action="experiment" data-model="empirical_survival">Testar sobrevivência</button></div><div id="intel-mlops"><p class="muted">Carregue a central para consultar os resultados reais.</p></div></section>
 <section class="intel-kpis">
  <article><span>CONFIANÇA MÉDIA</span><strong>${m.averageConfidence==null?'—':esc(m.averageConfidence)+'%'}</strong><small>${esc(m.bossesModeled||0)} bosses modelados</small></article>
  <article><span>ACERTO · 30 DIAS</span><strong>${m.windowAccuracy==null?'—':esc(m.windowAccuracy)+'%'}</strong><small>${esc(m.backtestSamples||0)} previsões avaliadas</small></article>
  <article><span>ERRO MÉDIO · 30 DIAS</span><strong>${m.maeMinutes==null?'—':'±'+esc(m.maeMinutes)+' min'}</strong><small>Comparação previsão × aparição real</small></article>
  <article><span>EVENTOS APRENDIDOS</span><strong>${events.length}</strong><small>Eventos recentes carregados neste mundo</small></article>
 </section>
 <section class="group-panel trust-center"><div class="eyebrow">CENTRAL DE CONFIABILIDADE</div><h2>Qualidade, calibração e governança</h2>
 <div class="intel-kpis">
  <article><span>QUALIDADE DOS DADOS</span><strong>${quality.averageScore==null?'—':esc(quality.averageScore)+'/100'}</strong><small>${esc(quality.traceable||0)} rastreáveis · ${esc(quality.untraceable||0)} sem origem · ${quality.traceabilityRate==null?'—':esc(quality.traceabilityRate)+'%'} rastreabilidade</small></article>
  <article><span>CONFLITOS</span><strong>${esc(trust.conflicts||0)}</strong><small>${esc(trust.quarantined||0)} em quarentena</small></article>
  <article><span>CALIBRAÇÃO</span><strong>${cal.ece==null?'—':esc(cal.ece)+' p.p.'}</strong><small>Erro de calibração esperado</small></article>
  <article><span>DRIFT</span><strong>${esc((trust.drifts||[]).length)}</strong><small>Bosses com mudança de padrão</small></article>
 </div>
 <p class="muted">Engine ${esc(trust.engineVersion||'—')} · modelo ${esc(trust.modelVersion||'—')} · ledger ${trust.ledger?.valid?'íntegro':'ATENÇÃO'} (${esc(trust.ledger?.entries||0)} eventos imutáveis).</p>
 <p class="muted">Métricas atuais usam somente a versão ativa. 30 dias: ${perf.days30?.predictions||0} previsões · ${perf.days30?.windowAccuracy==null?'—':esc(perf.days30.windowAccuracy)+'%'} acerto · ${perf.days30?.maeMinutes==null?'—':'±'+esc(perf.days30.maeMinutes)+' min'}. Histórico de todas as versões: ${perfAll.days30?.predictions||0} previsões · ${perfAll.days30?.windowAccuracy==null?'—':esc(perfAll.days30.windowAccuracy)+'%'}.</p>
 ${(trust.algorithmChanges||[]).length?'<details><summary>Últimas mudanças do algoritmo</summary>'+(trust.algorithmChanges||[]).map(x=>'<p>'+dt(x.at)+' · '+esc(x.payload?.fromEngine||'inicial')+' / '+esc(x.payload?.fromModel||'inicial')+' → <b>'+esc(x.payload?.toEngine||'—')+' / '+esc(x.payload?.toModel||'—')+'</b></p>').join('')+'</details>':''}
 ${(trust.alerts||[]).length?'<div class="trust-alerts">'+trust.alerts.map(a=>'<div class="notice"><b>'+esc(a.severity?.toUpperCase()||'ALERTA')+'</b> · '+esc(a.message)+'</div>').join('')+'</div>':'<p class="muted">Nenhum alerta interno de confiança ativo.</p>'}
 <h3>Calibração da confiança</h3><p class="muted">ECE: ${cal.ece==null?'—':esc(cal.ece)+' p.p.'} · MCE: ${cal.mce==null?'—':esc(cal.mce)+' p.p.'} · Brier: ${cal.brier==null?'—':esc(cal.brier)}</p><div class="table-wrap"><table class="ranking-table intelligence-table"><thead><tr><th>Faixa prevista</th><th>Amostras</th><th>Confiança média</th><th>Acerto real</th><th>Diferença</th></tr></thead><tbody>
 ${(cal.bins||[]).map(b=>'<tr><td>'+esc(b.range)+'</td><td>'+esc(b.samples)+'</td><td>'+(b.expected==null?'—':esc(b.expected)+'%')+'</td><td>'+(b.actual==null?'—':esc(b.actual)+'%')+'</td><td>'+(b.gap==null?'—':esc(b.gap)+' p.p.')+'</td></tr>').join('')||'<tr><td colspan="5">Ainda não há previsões resolvidas suficientes para calibrar a confiança.</td></tr>'}
 </tbody></table></div>
 <h3>Champion / Challenger</h3><div class="table-wrap"><table class="ranking-table intelligence-table"><thead><tr><th>Boss</th><th>Champion</th><th>Amostras</th><th>MAE</th><th>Melhor challenger</th><th>Promoção</th></tr></thead><tbody>
 ${(trust.governance||[]).slice(0,100).map(g=>{const c=g.champion||{},ch=(g.challengers||[])[0]||{};return '<tr><td>'+esc(g.boss)+'</td><td><b>'+esc(c.name||'adaptive_ensemble')+'</b></td><td>'+esc(c.samples||0)+'</td><td>'+(c.mae==null?'—':'±'+esc(c.mae)+' min')+'</td><td>'+esc(ch.name||'—')+(ch.mae==null?'':' · ±'+esc(ch.mae)+' min')+'</td><td>'+esc(g.promotionRecommended||'Sem promoção estatisticamente comprovada')+'</td></tr>';}).join('')||'<tr><td colspan="6">Aguardando pelo menos 50 previsões pareadas e ganho material para recomendação.</td></tr>'}
 </tbody></table></div>
 ${(trust.insufficientBosses||[]).length?'<h3>Dados insuficientes</h3><div class="audit-list">'+trust.insufficientBosses.slice(0,100).map(x=>'<div class="log-row"><b>'+esc(x.boss)+'</b><span>'+esc(x.reason)+'</span></div>').join('')+'</div>':''}
 <h3>Autoavaliação · últimas 100 previsões resolvidas</h3>
 ${(()=>{const a=trust.autoEvaluation||{};return '<div class="table-wrap"><table class="ranking-table intelligence-table"><tbody><tr><td>Previsões</td><td>'+esc(a.predictions??0)+'</td><td>Com horário preciso</td><td>'+esc(a.precisePredictions??0)+'</td></tr><tr><td>Acerto da janela</td><td>'+(a.windowAccuracy==null?'—':esc(a.windowAccuracy)+'%')+'</td><td>Erro médio / mediano</td><td>'+(a.maeMinutes==null?'—':'±'+esc(a.maeMinutes)+' / ±'+esc(a.medianErrorMinutes)+' min')+'</td></tr><tr><td>Melhor boss</td><td>'+(a.bestBoss?esc(a.bestBoss.boss)+' · ±'+esc(a.bestBoss.mae)+' min ('+esc(a.bestBoss.samples)+')':'Amostra insuficiente')+'</td><td>Pior boss</td><td>'+(a.worstBoss?esc(a.worstBoss.boss)+' · ±'+esc(a.worstBoss.mae)+' min ('+esc(a.worstBoss.samples)+')':'Amostra insuficiente')+'</td></tr><tr><td>Fonte mais confiável</td><td>'+(a.bestSource?esc(a.bestSource.name)+' · '+esc(a.bestSource.reliability)+'%':'Amostra insuficiente')+'</td><td>Fonte menos confiável</td><td>'+(a.worstSource?esc(a.worstSource.name)+' · '+esc(a.worstSource.reliability)+'%':'Amostra insuficiente')+'</td></tr><tr><td>Melhor método</td><td>'+(a.bestMethod?esc(a.bestMethod.name)+' · ±'+esc(a.bestMethod.mae)+' min ('+esc(a.bestMethod.samples)+')':'Amostra insuficiente')+'</td><td>Drifts / anomalias</td><td>'+esc(a.drifts??0)+' / '+esc(a.anomalies??0)+'</td></tr></tbody></table></div>';})()}
 <h3>Observabilidade da IA</h3><div class="table-wrap"><table class="ranking-table intelligence-table"><tbody>
 <tr><td>prediction_latency</td><td>${obs.prediction_latency==null?'—':esc(obs.prediction_latency)+' ms'}</td><td>prediction_error_minutes</td><td>${obs.prediction_error_minutes==null?'—':'±'+esc(obs.prediction_error_minutes)+' min'}</td></tr>
 <tr><td>confidence_calibration_error · ECE</td><td>${obs.confidence_calibration_error==null?'—':esc(obs.confidence_calibration_error)+' p.p.'}</td><td>confidence_calibration_max_gap · MCE</td><td>${obs.confidence_calibration_max_gap==null?'—':esc(obs.confidence_calibration_max_gap)+' p.p.'}</td></tr>
 <tr><td>confidence_brier_score</td><td>${obs.confidence_brier_score==null?'—':esc(obs.confidence_brier_score)}</td><td>raw_calibration_error</td><td>${cal.rawEce==null?'—':esc(cal.rawEce)+' p.p.'}</td></tr>
 <tr><td>data_quality_score</td><td>${obs.data_quality_score==null?'—':esc(obs.data_quality_score)+'/100'}</td><td>data_quality_traceability_rate</td><td>${obs.data_quality_traceability_rate==null?'—':esc(obs.data_quality_traceability_rate)+'%'}</td></tr><tr><td>data_quality_untraceable</td><td>${esc(obs.data_quality_untraceable??0)}</td><td>drift_score</td><td>${esc(obs.drift_score??0)}</td></tr>
 <tr><td>anomaly_rate</td><td>${esc(obs.anomaly_rate??0)}%</td><td>prediction_volume</td><td>${esc(obs.prediction_volume??0)}</td></tr>
 </tbody></table></div>
 </section>
 <section class="group-panel"><div class="sectionhead"><div><div class="eyebrow">DIAGNÓSTICO TÉCNICO</div><h2>Health, backtest e simulação</h2></div></div>
 <div class="card-actions"><button class="secondary" data-intel-action="health">Atualizar health check</button><button class="secondary" data-intel-action="backtest">Executar backtest histórico</button></div>
 <div id="intel-health"><p class="muted">Health check ainda não consultado nesta sessão.</p></div>
 <div id="intel-backtest"><p class="muted">Backtest histórico ainda não executado nesta sessão.</p></div>
 <div class="simulation-controls"><label>Boss<select id="intel-sim-boss">${preds.map(p=>'<option value="'+esc(p.boss)+'">'+esc(p.boss)+'</option>').join('')}</select></label><button class="secondary" data-intel-action="simulate" ${preds.length?'':'disabled'}>Inspecionar previsão</button></div>
 <div id="intel-simulation"><p class="muted">Selecione um boss para visualizar os dados reais usados pelo motor.</p></div>
 </section>
 <section class="group-panel"><div class="eyebrow">EVOLUÇÃO DA PRECISÃO</div><h2>7, 30 e 90 dias</h2>
 <div class="table-wrap"><table class="ranking-table intelligence-table"><thead><tr><th>Período</th><th>Previsões avaliadas</th><th>Acerto da janela</th><th>Erro médio</th><th>Corretas</th><th>Incorretas</th></tr></thead><tbody>
 ${periods.map(([k,label])=>{const x=perf[k]||{};return '<tr><td><b>'+label+'</b></td><td>'+(x.predictions||0)+'</td><td>'+(x.windowAccuracy==null?'—':x.windowAccuracy+'%')+'</td><td>'+(x.maeMinutes==null?'—':'±'+x.maeMinutes+' min')+'</td><td>'+(x.correct||0)+'</td><td>'+(x.incorrect||0)+'</td></tr>';}).join('')}
 </tbody></table></div>
 ${perf.deterioration?.detected?'<div class="notice"><b>⚠ '+esc(perf.deterioration.message)+'</b><p>Queda de acerto: '+esc(perf.deterioration.accuracyDrop)+' p.p. · razão do erro médio: '+esc(perf.deterioration.maeRatio)+'×</p><p>Possíveis causas a investigar: '+(perf.deterioration.possibleCauses||[]).map(esc).join(' · ')+'</p></div>':''}
 <h3>Curva de aprendizado</h3><div class="table-wrap"><table class="ranking-table intelligence-table"><thead><tr><th>Faixa</th><th>Amostras com horário</th><th>Erro médio</th><th>Acerto da janela</th></tr></thead><tbody>
 ${(perf.learningCurve||[]).map(x=>'<tr><td><b>'+esc(x.label)+'</b></td><td>'+esc(x.preciseSamples||0)+'</td><td>'+(x.maeMinutes==null?'Dados insuficientes':'±'+esc(x.maeMinutes)+' min')+'</td><td>'+(x.windowAccuracy==null?'—':esc(x.windowAccuracy)+'%')+'</td></tr>').join('')||'<tr><td colspan="4">Nenhuma previsão com horário preciso foi resolvida ainda.</td></tr>'}
 </tbody></table></div></section>
 <section class="group-panel"><div class="sectionhead"><div><div class="eyebrow">PREVISÃO EXPLICÁVEL</div><h2>Motor inteligente adaptativo</h2></div></div>
 <p class="muted">Cada boss combina métodos diferentes. O sistema aprende quais métodos funcionam melhor para aquele boss e reduz o peso dos que erram mais.</p>
 <div class="table-wrap"><table class="ranking-table intelligence-table"><thead><tr><th>Boss</th><th>Última aparição</th><th>Próxima janela</th><th>Maior probabilidade</th><th>Probabilidade</th><th>Confiança</th><th>Tendência</th></tr></thead><tbody>
 ${preds.length?preds.map(p=>`<tr><td><b>${esc(p.boss)}</b><details><summary>Por quê?</summary>${(p.explain||[]).map(x=>'<p>'+esc(x)+'</p>').join('')}<p>Intervalos: mínimo ${duration(p.intervalMinMs)} · histórico ${duration(p.intervalAverageMs)} · recente ${duration(p.intervalRecentMs)} · máximo ${duration(p.intervalMaxMs)}.</p><p><b>Score:</b> ${esc(p.predictionScore??0)}/100 · ${esc(p.scoreLabel||'—')} · <b>qualidade dos dados:</b> ${esc(p.dataQualityScore??'—')}/100.</p><p><b>Métodos:</b> ${(p.methods||[]).map(x=>esc(x.name)+' · peso '+esc(x.normalizedWeight??x.weight)+(x.learnedErrorMinutes==null?'':' · erro ±'+esc(x.learnedErrorMinutes)+' min')+(x.learnedHitRate==null?'':' · acerto '+esc(x.learnedHitRate)+'%')+(x.learnedSamples?' · n='+esc(x.learnedSamples):'')).join(' | ')||'—'}</p><p><b>Fontes usadas:</b> ${(p.sourceUsage||[]).map(x=>esc(x.name||x.sourceId)+' · '+esc(x.records)+' registros · qualidade '+(x.averageQuality==null?'—':esc(x.averageQuality)+'/100')+' · reputação '+(x.reliability==null?'—':esc(x.reliability)+'%')+((x.sourceRefs||[]).length?' · '+(x.sourceRefs||[]).map(r=>sourceRefHtml(r,x.sourceId)).join(', '):'')).join(' | ')||'—'}</p><p><b>Excluídos:</b> anomalias '+esc(p.excluded?.anomalies||0)+' · conflitos '+esc(p.excluded?.conflicts||0)+' · suspeitos/quarentena '+esc(p.excluded?.suspect||0)+'.</p><p><b>Distribuição condicional dentro da janela:</b> ${(p.probabilityDistribution||[]).map(x=>dt(x.from)+'–'+dt(x.to)+' '+esc(x.probability)+'%').join(' | ')||'Dados insuficientes'}</p></details></td><td>${dt(p.lastAt)}</td><td>${p.status==='ready'?dt(p.windowStart)+' – '+dt(p.windowEnd)+'<small class="countdown" data-countdown="'+(p.likelyAt||p.windowStart)+'"></small>':'Dados insuficientes'}</td><td>${p.likelyAt?dt(p.likelyAt):'Sem minuto confiável'}</td><td>${p.probability||0}%</td><td><span class="confidence-pill">${p.confidence||0}%</span></td><td>${esc(p.trend||'—')}</td></tr>`).join(''):'<tr><td colspan="7">Ainda não há histórico confirmado suficiente para modelar este mundo.</td></tr>'}
 </tbody></table></div></section>
 <section class="group-panel"><div class="eyebrow">APRENDIZADO POR BOSS</div><h2>Desempenho dos métodos</h2>
 <p class="muted">O erro é aprendido separadamente para cada boss. Um método pode ser ótimo para um boss e pouco útil para outro.</p>
 <div class="table-wrap"><table class="ranking-table intelligence-table"><thead><tr><th>Boss</th><th>Previsões avaliadas</th><th>Método</th><th>Erro médio aprendido</th><th>Taxa de acerto</th><th>Amostras</th></tr></thead><tbody>
 ${models.length?models.flatMap(x=>(x.methods||[]).map((method,i)=>'<tr><td>'+(i===0?'<b>'+esc(x.boss)+'</b>':'')+'</td><td>'+(i===0?(x.resolved||0):'')+'</td><td>'+esc(method.name)+'</td><td>'+(method.emaErrorMinutes==null?'—':'±'+esc(method.emaErrorMinutes)+' min')+'</td><td>'+(method.emaHitRate==null?'—':esc(method.emaHitRate)+'%')+'</td><td>'+(method.count||0)+'</td></tr>')).join(''):'<tr><td colspan="6">Os pesos aprendidos aparecerão depois que previsões forem comparadas com aparições reais.</td></tr>'}
 </tbody></table></div></section>
 <section class="group-panel"><div class="eyebrow">SAÚDE E PESO DINÂMICO</div><h2>Fontes de dados</h2><div class="table-wrap"><table class="ranking-table intelligence-table"><thead><tr><th>Fonte</th><th>Status</th><th>Reputação</th><th>Acurácia recente</th><th>Erro temporal</th><th>Duplicados</th><th>Registros</th><th>Latência média</th><th>Última consulta</th></tr></thead><tbody>
 ${sources.map(s=>`<tr><td><b>${esc(s.name)}</b><small class="muted">${esc(s.note||'')}</small></td><td><span class="source-state">${sourceState(s)}</span>${s.circuitReason?'<small>motivo: '+esc(s.circuitReason)+(s.circuitState==='HALF_OPEN'&&s.circuitReason==='quality'?' · recuperação '+esc(s.qualityRecoverySuccesses||0)+'/3':'')+'</small>':''}</td><td>${s.reliability}%</td><td>${s.recentAccuracy==null?'—':s.recentAccuracy+'%'}<small>${s.recentSamples||0} recentes</small></td><td>${s.averageErrorMinutes==null?'—':'±'+s.averageErrorMinutes+' min'}<small>${s.preciseEvaluatedRecords||0} precisos</small></td><td>${s.duplicates||0}</td><td>${s.records||0}</td><td>${s.averageLatencyMs?Math.round(s.averageLatencyMs)+' ms':'—'}</td><td>${s.lastAttempt?dt(s.lastAttempt):'—'}${s.lastError?'<small class="source-error">'+esc(s.lastError)+'</small>':''}</td></tr>`).join('')}
 </tbody></table></div></section>
 <section class="group-panel"><div class="eyebrow">EVIDÊNCIAS CONSOLIDADAS</div><h2>Eventos recentes</h2><div id="intelligence-events">
 ${events.slice(0,80).map(e=>`<article class="event-row"><div><b>${esc(e.boss)}</b><span class="badge ${e.status==='confirmed_auto'||e.status==='confirmed_manual'?'high':e.status==='probable'?'medium':'unknown'}">${eventLabel[e.status]||esc(e.status)}</span><p>${dt(e.estimatedAt)} · confiança ${e.confidence}% · qualidade ${e.dataQualityScore??'—'}/100 · ${esc(e.qualityStatus||'SEM CLASSIFICAÇÃO')} · ${e.sourceCount||0} fontes</p>${e.anomaly?'<p class="source-error">⚠ '+esc(e.anomaly.message)+'</p>':''}<details><summary>Ver origem e evidências</summary>${(e.evidence||[]).map(x=>`<p><b>${esc(x.sourceId)}</b> · ${esc(x.precision)} · ${dt(x.estimatedAt)} · qualidade ${esc(x.quality?.score??'—')}/100<br><small>Origem: ${sourceRefHtml(x.sourceRef,'identificador interno '+x.sourceId)} · coleta: ${esc(x.collectionMethod||'não informado')} · coletado ${dt(x.collectedAt)} · processado ${dt(x.processedAt)}${x.confirmedBy?' · confirmado por '+esc(x.confirmedBy):''}</small></p>`).join('')}</details></div><button class="secondary" data-correct-event="${esc(e.id)}" data-current-at="${e.estimatedAt}">Corrigir horário</button></article>`).join('')||'<div class="empty">Nenhum evento consolidado.</div>'}
 </div></section>
 <section class="group-panel"><div class="eyebrow">AUDITORIA</div><h2>Atividade recente</h2><div class="audit-list">${(intel.audit||[]).slice(0,100).map(a=>`<div class="log-row"><b>${esc(a.type)}</b><span>${esc(a.boss||a.sourceId||'sistema')} ${a.errorMinutes!=null?'· erro '+esc(a.errorMinutes)+' min':''}${a.confidence!=null?' · '+a.confidence+'%':''}</span><small>${dt(a.at)}</small></div>`).join('')||'<div class="empty">Nenhuma atividade registrada.</div>'}</div></section>`;
}
function refreshCountdowns(){for(const el of document.querySelectorAll('[data-countdown]')){const delta=Number(el.dataset.countdown)-Date.now();if(!Number.isFinite(delta)){el.textContent='';continue;}if(delta<=0){el.textContent='Janela/horário alcançado';continue;}const h=Math.floor(delta/3600000),m=Math.floor(delta%3600000/60000),sec=Math.floor(delta%60000/1000);el.textContent='Faltam '+String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(sec).padStart(2,'0');}}
function healthHtml(h){const services=Object.entries(h.services||{});return '<h3>Estado dos serviços</h3><div class="table-wrap"><table class="ranking-table intelligence-table"><thead><tr><th>Serviço</th><th>Status</th><th>Detalhes</th></tr></thead><tbody>'+services.map(([name,v])=>'<tr><td><b>'+esc(name)+'</b></td><td>'+esc(v.status||'—')+'</td><td>'+esc(Object.entries(v).filter(([k])=>k!=='status'&&k!=='pendingJobs').map(([k,x])=>k+': '+(x??'—')).join(' · '))+'</td></tr>').join('')+'</tbody></table></div><p class="muted">Fontes online: '+(h.sources?.online||0)+' · offline: '+(h.sources?.offline||0)+' · erros nas últimas 24h: '+(h.errors24h||0)+'</p>';}
function backtestHtml(r){return '<h3>Resultado do backtest walk-forward</h3><p>'+esc(r.eventsEvaluated||0)+' eventos históricos avaliados · '+esc(r.predictionsEvaluated||0)+' previsões de modelos comparadas.</p><div class="table-wrap"><table class="ranking-table intelligence-table"><thead><tr><th>Modelo</th><th>Amostras</th><th>Erro médio</th><th>Erro mediano</th><th>Acerto da janela</th></tr></thead><tbody>'+(r.overallModels||[]).map(x=>'<tr><td><b>'+esc(x.model)+'</b></td><td>'+esc(x.samples)+'</td><td>'+(x.maeMinutes==null?'—':'±'+esc(x.maeMinutes)+' min')+'</td><td>'+(x.medianErrorMinutes==null?'—':'±'+esc(x.medianErrorMinutes)+' min')+'</td><td>'+(x.windowAccuracy==null?'—':esc(x.windowAccuracy)+'%')+'</td></tr>').join('')+'</tbody></table></div><h3>Melhor modelo por boss</h3><div class="table-wrap"><table class="ranking-table intelligence-table"><thead><tr><th>Boss</th><th>Eventos testados</th><th>Melhor modelo</th><th>Erro médio</th></tr></thead><tbody>'+(r.perBoss||[]).slice(0,100).map(x=>{const best=(x.models||[]).find(m=>m.model===x.bestModel);return '<tr><td>'+esc(x.boss)+'</td><td>'+esc(x.testedEvents)+'</td><td><b>'+esc(x.bestModel||'Dados insuficientes')+'</b></td><td>'+(best?.maeMinutes==null?'—':'±'+esc(best.maeMinutes)+' min')+'</td></tr>';}).join('')+'</tbody></table></div>';}
function simulationHtml(r){const p=r.prediction||{},ints=r.intervals||[];return '<h3>'+esc(r.boss)+' · inspeção real do motor</h3><p>Eventos confirmados utilizados: '+esc(r.events?.length||0)+' · intervalos exibidos: '+esc(ints.length)+'</p><p>Janela: '+(p.windowStart?dt(p.windowStart)+' – '+dt(p.windowEnd):'Dados insuficientes')+' · centro interno do modelo: '+(p.predictedCenterAt?dt(p.predictedCenterAt):'—')+' · confiança: '+esc(p.confidence||0)+'%</p><p><b>Confiança:</b> '+(p.confidenceBreakdown?Object.entries(p.confidenceBreakdown).map(([k,v])=>esc(k)+' '+esc(v)).join(' · '):'indisponível')+'</p><p><b>Modelos:</b> '+(p.methods||[]).map(m=>esc(m.name)+' → '+dt(m.predictedAt)+' (peso '+esc(m.weight)+')').join(' | ')+'</p><details><summary>Últimos intervalos</summary>'+(ints.slice(-30).map(x=>'<p>'+dt(x.from)+' → '+dt(x.to)+' · '+duration(x.ms)+'</p>').join('')||'<p>Sem intervalos suficientes.</p>')+'</details>';}
export function initIntelligenceUI({getModel,post,reload,notify}){
 const root=document.getElementById('intelligence-content');if(!root)return;setInterval(refreshCountdowns,1000);
 root.addEventListener('click',e=>{const b=e.target.closest('[data-correct-event]');if(b){const current=Number(b.dataset.currentAt),local=new Date(current-3*3600000).toISOString().slice(0,16),value=prompt('Informe a data e hora corretas no horário de Brasília (AAAA-MM-DDTHH:MM):',local);if(!value)return;const at=Date.parse(value+':00-03:00');if(!Number.isFinite(at)){notify('Data/hora inválida.');return;}const reason=prompt('Justificativa da correção (opcional):','Correção manual após confirmação no jogo/grupo')||'';void post('/api/intelligence/correct',{eventId:b.dataset.correctEvent,at,reason}).then(reload).then(()=>notify('Evento corrigido e registrado na auditoria.')).catch(err=>notify(err.message));return;}
  const action=e.target.closest('[data-intel-action]');if(!action)return;const type=action.dataset.intelAction;action.disabled=true;
  const done=()=>{action.disabled=false;};
  if(type==='discovery'||type==='discover'){void (type==='discover'?post('/api/intelligence/discovery/run',{world:getModel().settings.world}):Promise.resolve()).then(()=>fetch('/api/intelligence/discovery')).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha no painel');return d;}).then(d=>{document.getElementById('discovery-content').innerHTML=discoveryHtml(d);}).catch(err=>notify(err.message)).finally(done);}
  if(type.startsWith('discovery-')){
 const v=id=>document.getElementById(id)?.value,world=getModel().settings.world;let operation=type.slice(10),input={world};
 if(operation==='automatic'||operation==='stop'){input.enabled=operation==='automatic';operation='automatic';}
 if(operation==='collector')input={world,sourceId:v('completion-source'),collector:v('completion-collector'),publicAccessApproved:document.getElementById('completion-public').checked};
 if(operation==='advance')input.id=v('completion-policy');
 if(operation==='dependency')input.id=v('completion-dependency');
 if(operation==='schedule')input={world,hour:Number(v('completion-save')),sourceRef:v('completion-save-ref'),validFrom:Date.now()};
 if(operation==='discord')input={world,channelId:v('completion-channel'),authorized:document.getElementById('completion-authorized').checked};
 void post('/api/intelligence/discovery/'+operation,input).then(()=>notify('Operação concluída. Atualize o painel para consultar resultados e gates.')).catch(err=>notify(err.message)).finally(done);
 }
 if(type==='candidate'){void post('/api/intelligence/discovery/candidate',{name:document.getElementById('discovery-source-name').value,url:document.getElementById('discovery-source-url').value}).then(()=>notify('Fonte candidata registrada em Shadow.')).catch(err=>notify(err.message)).finally(done);}
  if(type==='historical'){const day=document.getElementById('discovery-day').value,startAt=Date.parse(day+'T00:00:00-03:00');void post('/api/intelligence/discovery/historical',{world:getModel().settings.world,startAt,endAt:startAt+86400000-1,stepMinutes:60}).then(d=>{document.getElementById('discovery-historical').innerHTML=historicalHtml(d);}).catch(err=>notify(err.message)).finally(done);}
  if(['source-review','context-register','coverage-register','sample-register'].includes(type)){const value=id=>document.getElementById(id)?.value,at=id=>Date.parse(value(id)+':00-03:00'),world=getModel().settings.world,boss=value('discovery-boss'),startAt=at('discovery-start'),endAt=at('discovery-end'),sourceRef=value('discovery-ref');let operation,input;if(type==='source-review'){operation='review';input={sourceId:value('discovery-candidate'),status:value('discovery-candidate-state')};}else if(type==='context-register'){operation='context';input={world,type:value('discovery-context-type'),startAt,endAt,sourceRef};}else if(type==='coverage-register'){operation='coverage';const verified=document.getElementById('discovery-continuous').checked;input={world,boss,startAt,endAt,sourceRef,verified,continuous:verified};}else{operation='sample';input={world,boss,sourceId:value('discovery-candidate'),spawnLower:startAt,spawnUpper:endAt,detectedAt:at('discovery-detected')};}void post('/api/intelligence/discovery/'+operation,input).then(()=>notify('Informação registrada para avaliação. Atualize o painel.')).catch(err=>notify(err.message)).finally(done);}
  if(type==='health'){void fetch('/api/health').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Health indisponível');const el=document.getElementById('intel-health');if(el)el.innerHTML=healthHtml(d);}).catch(err=>notify(err.message)).finally(done);}
  if(type==='mlops'){void fetch('/api/intelligence/mlops').then(r=>{if(!r.ok)throw new Error('Falha ao carregar a central');return r.json();}).then(d=>{const el=document.getElementById('intel-mlops');if(el)el.innerHTML=mlopsHtml(d);}).catch(err=>notify(err.message)).finally(done);}
  if(type==='experiment'){void post('/api/intelligence/experiment',{world:getModel().settings.world,modelId:e.target.closest('[data-model]')?.dataset.model}).then(d=>{const el=document.getElementById('intel-mlops');if(el)el.innerHTML='<h3>Experimento temporal</h3><p>'+esc(d.samples)+' previsões avaliadas. Validação: '+esc(d.temporalPassed?'aprovada':'não aprovada')+'</p><p>'+esc(d.test?.reasons?.join(' · ')||'Sem resultados suficientes')+'</p>';}).catch(err=>notify(err.message)).finally(done);}
  if(type==='backtest'){void post('/api/intelligence/backtest',{world:getModel().settings.world}).then(d=>{const el=document.getElementById('intel-backtest');if(el)el.innerHTML=backtestHtml(d);}).catch(err=>notify(err.message)).finally(done);}
  if(type==='simulate'){const boss=document.getElementById('intel-sim-boss')?.value;if(!boss){done();return;}void post('/api/intelligence/simulate',{boss,world:getModel().settings.world}).then(d=>{const el=document.getElementById('intel-simulation');if(el)el.innerHTML=simulationHtml(d);}).catch(err=>notify(err.message)).finally(done);}
 });
}
