import test from 'node:test';
import assert from 'node:assert/strict';
import {buildFeatures,knownRows,availableAt,digest} from './mlops/feature-store.mjs';
import {datasetSnapshot,verifyDataset,survivalCurve,qualityGate,candidatePrediction} from './mlops/models.mjs';
import {ensureMLOps,recordPrediction,replayPrediction,resolveMLOps,evaluateModel,dashboard} from './mlops/service.mjs';
import {temporalExperiment} from './mlops/backtest.mjs';
import {selfCritique,poisoningSignal,featureImportance,sourceRelationships} from './mlops/analysis.mjs';
import {modelsForPrediction,monitorCanary,proposeOnlineUpdate} from './mlops/online-learning.mjs';
import {predictAdaptive} from './prediction/adaptive-engine.mjs';
import {resolveForecasts} from './learning/model-performance.mjs';
import {TaskQueue} from './runtime/task-queue.mjs';
const H=3600000,T=Date.parse('2025-01-01T00:00:00Z');
function event(i,overrides={}){const at=T+i*72*H;return {id:'e'+i,boss:'Boss',world:'World',estimatedAt:at,startAt:at,endAt:at,updatedAt:at+60000,eventType:'appearance',status:'confirmed_auto',qualityStatus:'CONFIRMADO',dataQualityScore:95,confidence:.95,consensus:{confidence:.95},evidence:[{evidenceId:'x'+i,sourceId:'rubinot-official',sourceRef:'https://example.org/event/'+i,collectionMethod:'official_json',boss:'Boss',world:'World',eventType:'appearance',estimatedAt:at,startAt:at,endAt:at,precision:'minute',confidence:.95,collectedAt:at+60000,reportedAt:at+60000,processedAt:at+60000,quality:{version:'2.0.0',status:'CONFIRMADO',score:95,traceable:true,eligibleForLearning:true}}],...overrides};}
const rows=n=>Array.from({length:n},(_,i)=>event(i));
function intel(n=25){return {events:rows(n),models:{},sources:{},forecasts:[],ledger:[]};}
function forecast(s,id='f1'){const asOf=availableAt(s.events.at(-1))+1,p=predictAdaptive(s.events,'Boss','World',{},asOf);return {id,boss:'Boss',world:'World',baseEventId:p.baseEventId,baseEventAt:p.baseEventAt,createdAt:asOf,predictedCenterAt:p.predictedCenterAt,windowStart:p.windowStart,windowEnd:p.windowEnd,confidence:p.confidence,sampleSize:p.sampleSize,methods:p.methods,drift:p.drift,calibration:{samples:0}};}
test('Feature Store excludes late knowledge, future observations, quarantine and future corrections',()=>{const es=rows(20),asOf=availableAt(es[10])+1;assert.equal(buildFeatures(es,'Boss','World',asOf).values.samples,11);es[2].updatedAt=asOf+100;es[3].evidence[0].processedAt=asOf+100;es[4].qualityStatus='SUSPEITO';assert.equal(knownRows(es,'Boss','World',asOf).length,8);assert.equal(buildFeatures(es,'Boss','World',asOf).values.mean5,72);});
test('Dataset identity is deterministic, immutable and changes on configuration or correction',()=>{const es=rows(20),asOf=availableAt(es.at(-1))+1,f=buildFeatures(es,'Boss','World',asOf),store={},a=datasetSnapshot(store,f,{weights:{x:1}}),b=datasetSnapshot(store,f,{weights:{x:1}});assert.equal(a.id,b.id);es[0].estimatedAt+=123;assert.ok(verifyDataset(a));assert.notEqual(datasetSnapshot(store,f,{weights:{x:2}}).id,a.id);a.events[0].estimatedAt++;assert.equal(verifyDataset(a),false);});
test('Shadow predictions are persisted separately and replay survives current history changes',()=>{const s=intel(),f=forecast(s),asOf=f.createdAt;const result=recordPrediction(s,f,asOf);assert.equal(s.mlops.runs.filter(x=>x.mode==='Shadow').length,2);assert.equal(s.mlops.registry.robust_interval.status,'Shadow');assert.ok(result.datasetId);const replay=replayPrediction(s,f.id);assert.equal(replay.rawPrediction.predictedCenterAt,f.predictedCenterAt);s.events[0].estimatedAt+=H;s.models={};assert.equal(replayPrediction(s,f.id).verified,true);assert.equal(s.forecasts.length,0);});
test('Replay rejects changes to prediction and dataset independently',()=>{const s=intel(),f=forecast(s);recordPrediction(s,f,f.createdAt);s.mlops.runs[0].output.confidence++;assert.throws(()=>replayPrediction(s,f.id),/Snapshot/);});
test('Controlled resolution measures outcomes without changing active method weights',()=>{const s=intel(),f=forecast(s),next=event(25);s.forecasts=[f];const prior=digest(s.models);const resolved=resolveForecasts(s.forecasts,next,s.models,{controlled:true});assert.equal(resolved.length,1);assert.deepEqual(s.models['World|boss'].methods,{});resolveMLOps(s,f,next);assert.equal(s.mlops.updates[f.id].status,'pending_validation');assert.ok(s.mlops.errors[f.id]);resolveMLOps(s,f,next);assert.equal(Object.keys(s.mlops.errors).length,1);assert.equal(proposeOnlineUpdate(s,'Boss','World').status,'insufficient');});
test('Quarantined outcomes cannot update the forecast book',()=>{const s=intel(),f=forecast(s),bad=event(25,{qualityStatus:'SUSPEITO'});assert.equal(resolveForecasts([f],bad,s.models,{controlled:true}).length,0);assert.equal(f.resolvedAt,undefined);});
test('Quality gate requires significant paired gain, calibration, temporal audit and each boss',()=>{const a=Array.from({length:60},(_,i)=>({pairId:String(i),boss:'A',world:'World',errorMinutes:100,windowHit:true,confidence:100,latencyMs:1})),b=a.map(x=>({...x,errorMinutes:70}));assert.ok(qualityGate(a,b,{temporalPassed:true,leakagePassed:true}).passed);assert.equal(qualityGate(a,b).passed,false);const worse=b.map((x,i)=>i<20?{...x,boss:'B',errorMinutes:120}:x),base=a.map((x,i)=>i<20?{...x,boss:'B'}:x);assert.equal(qualityGate(base,worse,{temporalPassed:true,leakagePassed:true}).passed,false);assert.equal(qualityGate(a,b.map(x=>({...x,confidence:null})),{temporalPassed:true,leakagePassed:true}).passed,false);});
test('Survival conditional horizons are monotonic, bounded and abstain on unsupported tails',()=>{const f=buildFeatures(rows(30),'Boss','World',availableAt(event(29))+1),curve=survivalCurve(f);assert.equal(curve.status,'ready');assert.ok(curve.horizons.every((h,i)=>h.probability>=0&&h.probability<=1&&(!i||h.probability>=curve.horizons[i-1].probability)));f.values.elapsedHours=100;assert.equal(survivalCurve(f).status,'insufficient_tail');assert.equal(survivalCurve(buildFeatures(rows(3),'Boss','World',T+1000*H)).status,'insufficient');});
test('Temporal experiments exclude hindsight and record exactly available datasets',()=>{const s=intel(35),r=temporalExperiment(s,'World','robust_interval',T+4000*H);assert.ok(r.samples>0);assert.ok(r.leakagePassed);assert.equal(r.temporalPassed,false);for(const ds of Object.values(s.mlops.datasets))assert.ok(ds.events.every(e=>availableAt(e)<=ds.asOf));for(const e of s.events)e.updatedAt=T+5000*H;assert.equal(temporalExperiment(s,'World','robust_interval',T+6000*H).samples,0);});
test('Self critique requests confirmation on conflict and suppresses exact time',()=>{const s=intel(),f=buildFeatures(s.events,'Boss','World',T+2000*H),c=selfCritique({boss:'Boss',world:'World',confidence:90,probability:80,excluded:{conflicts:1},calibration:{samples:0}},f);assert.ok(c.needsConfirmation);assert.equal(c.canPublishExact,false);assert.ok(c.confidenceCap<90);});
test('Poisoning detector ignores day-only repetition and flags precise source bursts',()=>{const es=rows(15),obs=es[0].evidence[0];for(const e of es){e.evidence[0].estimatedAt=obs.estimatedAt;e.evidence[0].processedAt=obs.processedAt;}assert.equal(poisoningSignal({...obs,evidenceId:'new'},es).kind,'repeated_precise_timestamp');assert.equal(poisoningSignal({...obs,precision:'day'},es),null);});
test('Feature importance is measured only after enough temporal folds',()=>{assert.equal(featureImportance(rows(20),'Boss','World',T+3000*H).status,'insufficient');const r=featureImportance(rows(60),'Boss','World',T+6000*H);assert.equal(r.status,'no_positive_gain');assert.equal(r.productionEligible,false);assert.ok(r.features.every(x=>x.importance==null));});
test('Canary selection is deterministic and regression rolls back',()=>{const s=intel();ensureMLOps(s);s.mlops.rollouts['World|boss']={id:'u',status:'canary',models:{candidate:true},percentage:5,stage:0,stageStartedAt:1,gate:{champion:{maeMinutes:10,windowAccuracy:1}}};assert.deepEqual(modelsForPrediction(s,'Boss','World','same'),modelsForPrediction(s,'Boss','World','same'));s.forecasts=Array.from({length:20},(_,i)=>({boss:'Boss',world:'World',createdAt:2,resolvedAt:3,errorMinutes:20,windowHit:false,rollout:{id:'u',selected:true}}));assert.equal(monitorCanary(s,'Boss','World',4).status,'rolled_back');assert.equal(modelsForPrediction(s,'Boss','World','same').models,s.models);});
test('Queue retries only declared idempotent jobs and preserves dead letters while processing recovers',async()=>{const letters=[],q=new TaskQueue({deadLetters:letters});assert.throws(()=>q.enqueue('unsafe',async()=>{}, {maxAttempts:2}),/idempotente/);let attempts=0;await assert.rejects(q.enqueue('bad',async()=>{attempts++;throw new Error('failure');},{idempotent:true,maxAttempts:3,payload:{eventId:'e'}}));assert.equal(attempts,3);assert.equal(letters[0].attempts,3);assert.equal(letters[0].payload.eventId,'e');assert.equal(await q.enqueue('good',async()=>42),42);assert.equal(q.stats().deadLetterCount,1);});
test('Registry and dashboard preserve Champion and show unavailable metrics honestly',()=>{const s=intel(0),d=dashboard(s,'World',T);assert.equal(d.champion.status,'Champion');assert.equal(d.shadowModels.length,2);assert.equal(d.report.precision.maeMinutes,null);assert.equal(evaluateModel(s,'robust_interval','World',T).passed,false);assert.equal(s.mlops.registry.robust_interval.status,'Shadow');});
