let getModel,post,reload,notify,sortBy='priority',filterState='all';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(n,d=0)=>Number.isFinite(Number(n))?Number(n).toFixed(d):'—';
const pct=n=>Number.isFinite(Number(n))?num(n,1)+'%':'—';
const dt=n=>Number.isFinite(Number(n))?new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(n)):'—';
function risk(n){return !Number.isFinite(Number(n))?'UNKNOWN':n>=70?'HIGH':n>=40?'MEDIUM':'LOW';}
function interval(ms){if(!Number.isFinite(Number(ms)))return '—';const s=Math.round(ms/1000);return s<120?s+'s':Math.round(s/60)+'min';}
function card(row){
 const why=(row.whyNow||[]).map(x=>'<li>'+esc(x.factor)+'</li>').join('')||'<li>Sem fator dominante.</li>',up=(row.whatWouldChange?.up||[]).map(x=>'<li>'+esc(x)+'</li>').join(''),down=(row.whatWouldChange?.down||[]).map(x=>'<li>'+esc(x)+'</li>').join(''),curve=(row.probabilityCurve||[]).slice(0,12).map(x=>'<span title="'+dt(x.from)+'–'+dt(x.to)+'">'+esc(num(x.probability,1))+'%</span>').join('');
 return '<article class="ops-card"><div class="ops-card-head"><div><div class="eyebrow">'+esc(row.state)+'</div><h3>'+esc(row.boss)+'</h3></div><div class="ops-priority"><strong>'+esc(row.priorityScore??'—')+'</strong><small>PRIORITY</small></div></div><div class="ops-kpis"><span>Probability<b>'+pct(row.modelProbability)+'</b></span><span>Decision confidence<b>'+pct(row.decisionConfidence)+'</b></span><span>Miss risk<b>'+esc(risk(row.missedDetectionRisk))+' · '+num(row.missedDetectionRisk)+'</b></span><span>Info gap<b>'+num(row.informationGapScore)+'/100</b></span><span>Peak<b>'+dt(row.peakProbabilityTime)+'</b></span><span>Polling<b>'+interval(row.polling?.intervalMs)+'</b></span></div><p class="muted">Janela '+dt(row.windowStart)+' → '+dt(row.windowEnd)+' · cobertura '+pct(row.detectionCoverage)+' · velocity '+num(row.probabilityVelocity,1)+' p.p./h.</p><div class="ops-curve">'+curve+'</div><div class="notice"><b>Next Best Action:</b> '+esc(row.nextBestAction?.action||'NO_ACTION')+(row.nextBestAction?.sourceId?' · '+esc(row.nextBestAction.sourceId):'')+'<br><b>Next Best Source:</b> '+esc(row.nextBestSource?.name||'INSUFFICIENT DATA')+(row.nextBestSource?.valueOfInformation!=null?' · VOI '+num(row.nextBestSource.valueOfInformation)+'/100':'')+'</div><details><summary>Por que observar agora?</summary><ul>'+why+'</ul></details><details><summary>O que faria esta prioridade mudar?</summary><b>Subiria se</b><ul>'+up+'</ul><b>Cairia se</b><ul>'+down+'</ul></details><details><summary>Ranking de fontes</summary><div class="table-wrap"><table class="ranking-table"><thead><tr><th>Fonte</th><th>VOI</th><th>Health</th><th>Reliability</th><th>1ª detecção</th><th>Delay</th></tr></thead><tbody>'+(row.sourceRanking||[]).map(s=>'<tr><td>'+esc(s.name)+'</td><td>'+num(s.valueOfInformation)+'</td><td>'+esc(s.status)+'</td><td>'+pct(s.reliability)+'</td><td>'+pct(s.firstDetectionRate)+'</td><td>'+num(s.averageDelayMinutes,1)+' min</td></tr>').join('')+'</tbody></table></div></details><div class="group-buttons"><button class="secondary" data-ops-action="ACKNOWLEDGE" data-boss="'+encodeURIComponent(row.boss)+'">ACKNOWLEDGE</button><button class="secondary" data-ops-action="SNOOZE" data-boss="'+encodeURIComponent(row.boss)+'">SNOOZE 60min</button><button class="primary" data-ops-action="'+(row.attention?.followClosely?'UNFOLLOW':'FOLLOW_CLOSELY')+'" data-boss="'+encodeURIComponent(row.boss)+'">'+(row.attention?.followClosely?'PARAR DE ACOMPANHAR':'ACOMPANHAR')+'</button></div></article>';
}
export function renderOperations(model){
 const root=$('operations-content');if(!root)return;
 const o=model.operations||{},metrics=o.metrics||{},rows=[...(o.bosses||[])].filter(x=>filterState==='all'||x.state===filterState);
 const sorters={priority:(a,b)=>(b.priorityScore??-1)-(a.priorityScore??-1),probability:(a,b)=>(b.modelProbability??-1)-(a.modelProbability??-1),peak:(a,b)=>(a.peakProbabilityTime??Infinity)-(b.peakProbabilityTime??Infinity),miss:(a,b)=>(b.missedDetectionRisk??-1)-(a.missedDetectionRisk??-1),uncertainty:(a,b)=>(b.uncertaintyScore??-1)-(a.uncertaintyScore??-1)};
 rows.sort(sorters[sortBy]||sorters.priority);
 const states=[...new Set((o.bosses||[]).map(x=>x.state))].sort();
 const statesHtml=states.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('');
 const investigationsHtml=(o.activeInvestigations||[]).map(x=>'<div class="event-row"><div><b>'+esc(x.boss)+'</b><p>'+esc(x.status)+' · Priority '+num(x.priorityScore)+' · Gap '+num(x.informationGapScore)+' · budget '+esc(x.resourceBudget)+' / '+esc(x.sourceBudget)+' fontes</p></div><strong>'+interval(x.timeBudgetMs)+'</strong></div>').join('')||'<p class="muted">Nenhuma investigação intensiva necessária agora.</p>';
 const cardsHtml=rows.map(card).join('')||'<div class="empty">Nenhum boss corresponde ao filtro operacional.</div>';
 const metricsNote=metrics.status==='INSUFFICIENT_DATA'?'Métricas prospectivas ainda sem amostra suficiente. Nenhum valor é inventado para preencher o painel.':'Métricas calculadas apenas a partir de rankings gravados prospectivamente pelo Decision Engine.';
 const headerHtml='<div class="sectionhead"><div><div class="eyebrow">REAL-TIME DECISION INTELLIGENCE</div><h2>Boss Command Center</h2></div><div><button id="ops-refresh" class="secondary">↻ Recalcular</button></div></div><p class="muted">O Decision Engine decide onde concentrar atenção. Ele não altera a probabilidade produzida pelo Prediction Engine.</p>';
 const kpisHtml='<div class="intel-kpis"><article><span>TOP PRIORITY</span><strong>'+esc(o.topPriority?.[0]?.priorityScore??'—')+'</strong><small>'+esc(o.topPriority?.[0]?.boss||'INSUFFICIENT DATA')+'</small></article><article><span>ACTIVE INVESTIGATIONS</span><strong>'+esc((o.activeInvestigations||[]).length)+'</strong><small>planos operacionais ativos/planejados</small></article><article><span>TOP-3 HIT RATE</span><strong>'+pct(metrics.top3HitRate)+'</strong><small>'+esc(metrics.status||'INSUFFICIENT_DATA')+'</small></article><article><span>QUERY REDUCTION</span><strong>'+pct(metrics.adaptivePolling?.queryReductionPct)+'</strong><small>vs baseline global de 4 min</small></article></div>';
 const toolbarHtml='<div class="toolbar"><select id="ops-sort"><option value="priority">Priority</option><option value="probability">Probability</option><option value="peak">Time to Peak</option><option value="miss">Miss Risk</option><option value="uncertainty">Uncertainty</option></select><select id="ops-filter"><option value="all">Todos os estados</option>'+statesHtml+'</select></div>';
 const modelEval=metrics.decisionModels||{},champion=modelEval.champion||{},challengers=modelEval.challengers||[],daily=o.dailyReview||model.dailyReview||{};
 const modelHtml='<section class="group-panel"><div class="eyebrow">DECISION CHAMPION / CHALLENGER</div><h3>'+esc(champion.modelId||o.champion?.id||'decision_rules_v1')+'</h3><p class="muted">Champion de produção explicável. Challengers permanecem em Shadow Mode e não alteram prioridades exibidas.</p><div class="table-wrap"><table class="ranking-table"><thead><tr><th>Modelo</th><th>Status</th><th>n</th><th>Top-1</th><th>Top-3</th><th>Top-5</th><th>Miss</th></tr></thead><tbody><tr><td>'+esc(champion.modelId||'decision_rules_v1')+'</td><td>CHAMPION</td><td>'+esc(champion.metrics?.samples||0)+'</td><td>'+pct(champion.metrics?.top1)+'</td><td>'+pct(champion.metrics?.top3)+'</td><td>'+pct(champion.metrics?.top5)+'</td><td>'+pct(champion.metrics?.missRate)+'</td></tr>'+challengers.map(x=>'<tr><td>'+esc(x.modelId)+'</td><td>'+esc(x.status)+'</td><td>'+esc(x.metrics?.samples||0)+'</td><td>'+pct(x.metrics?.top1)+'</td><td>'+pct(x.metrics?.top3)+'</td><td>'+pct(x.metrics?.top5)+'</td><td>'+pct(x.metrics?.missRate)+'</td></tr>').join('')+'</tbody></table></div><p class="muted">Decisão: '+esc(modelEval.decision||'INSUFFICIENT_DATA')+' · promoção automática: NÃO.</p></section>';
 const dailyHtml='<section class="group-panel"><div class="eyebrow">DAILY OPERATIONS REVIEW</div><p>Alertas: <b>'+esc(daily.alerts?.total??0)+'</b> · investigações: <b>'+esc(daily.activeInvestigations??0)+'</b> · early warning: <b>'+(daily.earlyWarningMinutes==null?'—':num(daily.earlyWarningMinutes,1)+' min')+'</b>.</p><p class="muted">Status: '+esc(daily.status||'INSUFFICIENT_DATA')+'. First Signal e Decisive Signal são derivados do caminho real da investigação; não são inferidos quando a evidência não existe.</p><div class="table-wrap"><table class="ranking-table"><thead><tr><th>Boss</th><th>First Signal</th><th>Decisive Signal</th><th>Confirmação</th></tr></thead><tbody>'+((daily.detectionPaths||[]).slice(0,20).map(x=>'<tr><td>'+esc(x.boss)+'</td><td>'+esc(x.firstSignal?.sourceId||'—')+'</td><td>'+esc(x.decisiveSignal?.sourceId||'—')+'</td><td>'+dt(x.confirmedAt)+'</td></tr>').join('')||'<tr><td colspan="4">INSUFFICIENT DATA</td></tr>')+'</tbody></table></div></section>';
 const operationalMetricsHtml='<section class="group-panel"><div class="eyebrow">OPERATIONAL METRICS</div><div class="ops-metrics-grid"><span>Top-1<b>'+pct(metrics.top1HitRate)+'</b></span><span>Top-3<b>'+pct(metrics.top3HitRate)+'</b></span><span>Top-5<b>'+pct(metrics.top5HitRate)+'</b></span><span>Alert precision<b>'+pct(metrics.alertPrecision)+'</b></span><span>Alert recall<b>'+pct(metrics.alertRecall)+'</b></span><span>False alarm<b>'+pct(metrics.falseAlarmRate)+'</b></span><span>Missed boss<b>'+pct(metrics.missedBossRate)+'</b></span><span>Early warning<b>'+(metrics.meanEarlyWarningMinutes==null?'—':num(metrics.meanEarlyWarningMinutes,1)+' min')+'</b></span></div><p class="muted">'+esc(metricsNote)+'</p></section>';
 const investigationsPanel='<section class="group-panel"><div class="eyebrow">ACTIVE INVESTIGATION PLANS</div>'+investigationsHtml+'</section>';
 const replayHtml='<section class="group-panel"><div class="eyebrow">DECISION REPLAY</div><h3>Reproduzir um dia</h3><div class="group-buttons"><input id="ops-replay-date" type="date"><button id="ops-replay" class="secondary">REPLAY</button></div><div id="ops-replay-result"></div></section>';
 root.innerHTML=headerHtml+kpisHtml+toolbarHtml+operationalMetricsHtml+modelHtml+dailyHtml+investigationsPanel+'<div class="ops-grid">'+cardsHtml+'</div>'+replayHtml;
 $('ops-sort').value=sortBy;$('ops-filter').value=filterState;
}
export function initOperationsUI(options){
 ({getModel,post,reload,notify}=options);const root=$('operations-content');if(!root)return;root.addEventListener('change',e=>{if(e.target.id==='ops-sort'){sortBy=e.target.value;renderOperations(getModel());}if(e.target.id==='ops-filter'){filterState=e.target.value;renderOperations(getModel());}});
 root.addEventListener('click',e=>{if(e.target.closest('#ops-refresh')){void reload();return;}const b=e.target.closest('[data-ops-action]');if(b){const boss=decodeURIComponent(b.dataset.boss),action=b.dataset.opsAction;void post('/api/operations/action',{world:getModel().settings.world,boss,action,minutes:60}).then(()=>reload()).catch(x=>notify(x.message));return;}if(e.target.closest('#ops-replay')){const value=$('ops-replay-date').value;if(!value){notify('Informe uma data.');return;}const startAt=new Date(value+'T00:00:00-03:00').getTime(),endAt=startAt+86400000-1;void post('/api/operations/replay',{world:getModel().settings.world,startAt,endAt}).then(d=>{$('ops-replay-result').innerHTML='<p><b>'+esc(d.snapshots?.length||0)+' snapshots · '+esc(d.timeline?.length||0)+' decisões · '+esc(d.alerts?.length||0)+' alertas.</b></p><pre>'+esc(JSON.stringify({timeline:(d.timeline||[]).slice(0,100),alerts:(d.alerts||[]).slice(0,50)},null,2))+'</pre>';}).catch(x=>notify(x.message));}});
}
