let getModel,post,reload,notify;
const $=id=>document.getElementById(id),safe=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),dt=v=>Number.isFinite(Number(v))?new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(Number(v))):'—',duration=ms=>Number.isFinite(Number(ms))?(Number(ms)<60000?Math.round(Number(ms)/1000)+'s':Math.round(Number(ms)/60000)+' min'):'—';
export function initWhatsAppUI(options){({getModel,post,reload,notify}=options);
 $('wa-boss-search').oninput=renderIdentified;
 $('wa-code-button').onclick=async()=>{try{const r=await post('/api/whatsapp/pair-code',{});$('wa-code').textContent=r.code;$('wa-code-wrap').hidden=false;notify('Código válido por 10 minutos. Cole somente na sua extensão.');}catch(e){notify(e.message);}};
 $('wa-copy').onclick=async()=>{try{await navigator.clipboard.writeText($('wa-code').textContent);notify('Código copiado.');}catch{notify('Selecione e copie o código exibido.');}};
 $('wa-disconnect').onclick=async()=>{try{await post('/api/whatsapp/disconnect',{});$('wa-code-wrap').hidden=true;await reload();notify('Extensão desconectada. Seu histórico foi mantido.');}catch(e){notify(e.message);}};
 $('wa-pending').onclick=async e=>{const b=e.target.closest('[data-wa-dismiss]');if(!b)return;try{await post('/api/whatsapp/dismiss',{id:b.dataset.waDismiss});await reload();}catch(e){notify(e.message);}};
 $('wa-candidates').onclick=handleCandidate;
 $('wa-health').onclick=async e=>{const b=e.target.closest('[data-wa-alias]');if(!b)return;try{await post('/api/whatsapp/alias-approve',{boss:b.dataset.waBoss,alias:b.dataset.waAlias});await reload();notify('Alias aprovado e será sincronizado pelo dicionário versionado.');}catch(err){notify(err.message);}};
 $('wa-investigation').onclick=async e=>{const b=e.target.closest('[data-investigation-backtest]');if(!b)return;try{const r=await post('/api/investigation/backtest',{});notify('Backtest investigativo: '+r.samples+' decisões históricas avaliadas.');await reload();}catch(err){notify(err.message);}};
}
export function renderWhatsAppUI(){
 const w=getModel().whatsapp||{},m=w.metrics||{},cov=w.coverage||{},health=w.health||{};
 $('wa-status').textContent=w.connected?`${w.group} · ${w.world} · ${w.status}${w.updateAvailable?' · UPDATE AVAILABLE':''}`:w.statusMessage||w.status||'Não conectado';
 $('wa-disconnect').hidden=!w.connected;
 $('wa-marker').textContent=w.checkpoint?`Checkpoint: ${dt(w.checkpoint.at)}.`:'O checkpoint será criado pelo Collector sem importar o histórico já carregado.';
 const d=w.diagnostics;
 $('wa-diagnostics').textContent=d?`Grupo detectado: ${d.detected||'não localizado'} · ${d.visible} mensagens visíveis · ${d.relevant} relevantes · DOM ${d.domOk?'OK':'não validado'}${d.gapDetected?' · COLLECTION GAP detectado':''}.`:'Aguardando diagnóstico do WhatsApp Web.';
 $('wa-health').innerHTML=`<div class="intel-kpis"><article><span>COLLECTOR</span><strong>${safe(w.status||'DISCONNECTED')}</strong><small>Extensão ${safe(w.extensionVersion||'—')} · latest ${safe(w.latestExtensionVersion||'—')}</small></article><article><span>UPTIME · 24H</span><strong>${cov.uptimePct==null?'—':safe(cov.uptimePct)+'%'}</strong><small>Browser ${health.browserConnected?'YES':'NO'} · WhatsApp ${health.whatsappDetected?'YES':'NO'} · Grupo alvo ${(health.targetGroupDetected??health.lunarianDetected)?'YES':'NO'}</small></article><article><span>COBERTURA DO GRUPO · 24H</span><strong>${cov.coveragePct==null?'—':safe(cov.coveragePct)+'%'}</strong><small>${safe(cov.gapMinutes||0)} min em gaps</small></article><article><span>LATÊNCIA EXTENSÃO → BACKEND</span><strong>${m.backendDeliveryLatency?.p95==null?'—':Math.round(m.backendDeliveryLatency.p95)+' ms'}</strong><small>P50 ${m.backendDeliveryLatency?.p50==null?'—':Math.round(m.backendDeliveryLatency.p50)+' ms'} · P99 ${m.backendDeliveryLatency?.p99==null?'—':Math.round(m.backendDeliveryLatency.p99)+' ms'} · mensagem→captura aprox. ${m.messageCaptureApproxLatency?.p95==null?'—':Math.round(m.messageCaptureApproxLatency.p95)+' ms'}</small></article></div><div class="table-wrap"><table class="ranking-table"><tbody><tr><td>Mensagens vistas</td><td>${safe(m.messagesSeen||0)}</td><td>Filtradas localmente</td><td>${safe(m.messagesFiltered||0)}</td></tr><tr><td>Boss matches</td><td>${safe(m.bossMatches||0)}</td><td>Exact/Alias</td><td>${safe(m.exactMatches||0)}</td></tr><tr><td>Fuzzy</td><td>${safe(m.fuzzyMatches||0)}</td><td>Candidatos</td><td>${safe(m.candidateEvents||0)}</td></tr><tr><td>Fila</td><td>${safe(m.queueSize||0)}</td><td>Duplicidade</td><td>${safe(m.duplicateRate||0)}%</td></tr><tr><td>Erros</td><td>${safe(m.errorRate||0)}%</td><td>DOM adapter errors</td><td>${safe(m.domAdapterErrors||0)}</td></tr></tbody></table></div><p class="muted">Heartbeat: ${dt(w.lastHeartbeat)} · última mensagem relevante: ${dt(w.lastRelevantMessage)} · dicionário ${safe(w.dictionaryVersion||'—')}.</p>${(w.aliasSuggestions||[]).length?'<details><summary>Aliases sugeridos para aprovação</summary>'+(w.aliasSuggestions||[]).map(a=>'<p><b>'+safe(a.boss)+'</b> ← '+safe(a.alias)+' · '+safe(a.confirmed)+' confirmações · '+safe(a.reporters)+' reporters <button class="secondary" data-wa-alias="'+safe(a.alias)+'" data-wa-boss="'+safe(a.boss)+'">APROVAR ALIAS</button></p>').join('')+'</details>':''}`;
 renderInvestigation(getModel().investigation||{});
 renderCandidates(w.candidates||[]);
 renderIdentified();
 $('wa-images').innerHTML=(w.images||[]).slice(0,100).map(i=>`<figure><a href="${safe(i.url)}" target="_blank" rel="noreferrer"><img src="${safe(i.url)}" alt="Imagem relevante do grupo Fatal - Bosses Nemesis" loading="lazy"></a><figcaption><b>Fatal - Bosses Nemesis</b><small>${safe(i.world)} ${dt(i.at)}</small></figcaption></figure>`).join('')||'<p class="muted">Nenhuma imagem relevante importada.</p>';
 $('wa-pending').innerHTML=(w.pending||[]).slice(0,50).map(p=>`<div class="group-round"><div><b>${safe(p.bosses?.join(', ')||'Mensagem legada a revisar')}</b><p>${safe(p.date)} ${safe(p.time)} · ${safe(p.reason)}</p></div><button class="secondary" data-wa-dismiss="${safe(p.id)}">Resolvido / ignorar</button></div>`).join('')||'<p class="muted">Nenhuma mensagem legada pendente.</p>';
}
function renderInvestigation(inv){
 const root=$('wa-investigation');if(!root)return;const m=inv.metrics||{},t=inv.timing||{},cal=inv.calibration||{},bt=inv.backtest||{},cases=inv.cases||[],active=cases.filter(x=>!['CONFIRMED','CONFIRMED_LATE','REJECTED','EXPIRED'].includes(x.status));
 const top=active.slice(0,20).map(c=>'<div class="group-round"><div><b>'+safe(c.boss)+' · '+safe(c.status)+'</b><p>Score '+safe(c.rawScore??'—')+'/100 · Candidate Confidence '+(c.calibratedConfidence==null?'INSUFFICIENT DATA':safe(c.calibratedConfidence)+'%')+' · '+safe(c.recommendation||'—')+'</p><small>Primeira detecção '+dt(c.firstDetectionAt)+' · '+safe(c.consensus?.independentEvidence||0)+' evidências independentes · conflito '+safe(Math.round(100*(c.consensus?.conflictScore||0)))+'%</small></div></div>').join('');
 const sourceRows=(inv.sources||[]).slice(0,20).map(x=>'<tr><td>'+safe(x.name||x.id)+'<small>'+safe(x.id)+'</small></td><td>'+safe(x.health||'—')+'</td><td>'+safe(x.reliability)+'%</td><td>'+safe(x.samples)+'</td><td>'+(x.falsePositiveRate==null?'—':safe(x.falsePositiveRate)+'%')+'</td><td>'+(x.firstDetectionRate==null?'—':safe(x.firstDetectionRate)+'%')+'</td><td>'+duration(x.latency?.investigationAverageMs??x.latency?.averageMs)+'</td><td>'+(x.drift?'⚠ '+safe(x.driftDelta)+' p.p.':'OK')+'</td></tr>').join('');
 const reporterRows=(inv.reporters||[]).slice(0,20).map(x=>'<tr><td>#'+safe(x.id)+'</td><td>'+safe(x.reliability)+'%</td><td>'+safe(x.samples)+'</td><td>'+safe(x.correctRecords||0)+' / '+safe(x.incorrectRecords||0)+'</td><td>'+(x.falsePositiveRate==null?'—':safe(x.falsePositiveRate)+'%')+'</td><td>'+(x.firstDetectionRate==null?'—':safe(x.firstDetectionRate)+'%')+'</td><td>'+duration(x.averageLatencyMs)+'</td><td>'+(x.drift?'⚠ '+safe(x.driftDelta)+' p.p.':'OK')+'</td></tr>').join('');
 root.innerHTML='<div class="intel-kpis"><article><span>ATIVAS</span><strong>'+safe(m.active||0)+'</strong><small>'+safe(m.highConfidence||0)+' score alto · '+safe(m.conflicts||0)+' conflitos</small></article><article><span>DECISÕES</span><strong>'+safe(m.totalDecisions||0)+'</strong><small>confirmadas '+(m.confirmationRate==null?'—':safe(m.confirmationRate)+'%')+' · rejeitadas '+(m.rejectionRate==null?'—':safe(m.rejectionRate)+'%')+'</small></article><article><span>TIME TO INVESTIGATE</span><strong>'+duration(t.timeToInvestigate?.p50Ms)+'</strong><small>P95 '+duration(t.timeToInvestigate?.p95Ms)+'</small></article><article><span>CALIBRAÇÃO</span><strong>'+(cal.samples>=20?'ATIVA':'INSUFFICIENT DATA')+'</strong><small>'+safe(cal.samples||0)+' decisões resolvidas</small></article></div><div class="card-actions"><button class="secondary" data-investigation-backtest>Executar backtest investigativo</button></div>'+(top||'<p class="muted">Nenhuma investigação ativa.</p>')+'<details><summary>Source Intelligence</summary><div class="table-wrap"><table class="ranking-table"><thead><tr><th>Fonte</th><th>Health</th><th>Reliability</th><th>Amostra</th><th>False +</th><th>1ª detecção</th><th>Latência</th><th>Drift</th></tr></thead><tbody>'+(sourceRows||'<tr><td colspan="8">INSUFFICIENT DATA</td></tr>')+'</tbody></table></div></details><details><summary>Reporter Intelligence</summary><div class="table-wrap"><table class="ranking-table"><thead><tr><th>Reporter</th><th>Reliability</th><th>Amostra</th><th>OK / erro</th><th>False +</th><th>1ª detecção</th><th>Latência</th><th>Drift</th></tr></thead><tbody>'+(reporterRows||'<tr><td colspan="8">INSUFFICIENT DATA</td></tr>')+'</tbody></table></div></details><details><summary>Falhas, incidentes e missed detections</summary><p>Incidentes: '+safe((inv.incidents||[]).length)+' · missed/coverage: '+safe((inv.missed||[]).length)+' · falso positivo forte: '+(m.falsePositiveRate==null?'INSUFFICIENT DATA':safe(m.falsePositiveRate)+'%')+'</p><p>Backtest temporal: '+safe(bt.samples||0)+' decisões · accuracy de CONFIRM_RECOMMENDED '+(bt.confirmRecommendationAccuracy==null?'INSUFFICIENT DATA':safe(bt.confirmRecommendationAccuracy)+'%')+'</p>'+(inv.missed||[]).slice(0,20).map(x=>'<p><b>'+safe(x.kind)+'</b> · '+safe(x.boss)+' · '+dt(x.eventAt)+' · coverage '+(x.coveragePct==null?'—':safe(Math.round(x.coveragePct))+'%')+'<br>'+safe(x.reason)+'</p>').join('')+'</details>';
}
function dossierHtml(c){
 if(!c)return '<p class="muted">Investigação ainda não iniciou.</p>';const center=c.consensus?.centerAt,spread=c.consensus?.spreadMs,external=(c.evidence||[]).filter(x=>!['whatsapp-group','historical-analysis','prediction-engine'].includes(x.sourceId)),confidence=c.calibratedConfidence==null?'INSUFFICIENT DATA':safe(c.calibratedConfidence)+'%';
 return '<div class="investigation-dossier"><div class="intel-kpis"><article><span>STATUS</span><strong>'+safe(c.status)+'</strong><small>'+safe(c.recommendation||'—')+'</small></article><article><span>CANDIDATE SCORE</span><strong>'+safe(c.rawScore??'—')+'/100</strong><small>policy '+safe(c.policyVersion||'—')+'</small></article><article><span>CANDIDATE CONFIDENCE</span><strong>'+confidence+'</strong><small>'+safe(c.calibrationSamples||0)+' amostras na faixa</small></article><article><span>HORÁRIO PROVÁVEL</span><strong>'+dt(center)+'</strong><small>'+(spread==null?'—':'dispersão '+duration(spread))+'</small></article></div><p><b>Primeira detecção:</b> '+safe(c.firstDetectionSource||'—')+' · '+dt(c.firstDetectionAt)+' · <b>evidências independentes:</b> '+safe(c.consensus?.independentEvidence||0)+' · <b>fontes externas:</b> '+safe(external.length)+'</p><p><b>Historical Plausibility:</b> '+safe(c.historicalPlausibility??'—')+'% · <b>Anomaly:</b> '+safe(c.anomaly?.level||'UNKNOWN')+' · <b>Prediction Compatibility:</b> '+safe(c.predictionCompatibility?.level||'UNKNOWN')+' · <b>Coverage:</b> '+(c.coveragePct==null?'—':safe(c.coveragePct)+'%')+'</p><details><summary>Por que este score?</summary>'+(c.factors||[]).map(x=>'<p>'+safe(x.effect==='negative'?'−':'+' )+' '+safe(x.label)+': '+safe(x.value)+'</p>').join('')+'</details><details><summary>Timeline da investigação</summary>'+(c.timeline||[]).slice(-40).map(x=>'<p>'+dt(x.at)+' · <b>'+safe(x.type)+'</b>'+(x.sourceId?' · '+safe(x.sourceId):'')+(x.to!=null?' · score '+safe(x.to):'')+'</p>').join('')+'</details><details><summary>Evidence Graph</summary>'+(c.graph?.nodes||[]).map(n=>'<p>'+safe(n.type)+' · '+safe(n.label)+'</p>').join('')+'</details><details><summary>Casos semelhantes</summary><p>'+safe(c.similarCases?.samples||0)+' casos · '+safe(c.similarCases?.confirmed||0)+' confirmados · '+safe(c.similarCases?.rejected||0)+' rejeitados</p><p>Challenger '+safe(c.shadowModel?.id||'—')+' · '+(c.shadowModel?.prediction==null?'INSUFFICIENT DATA':safe(c.shadowModel.prediction)+'%')+' · '+safe(c.shadowModel?.status||'SHADOW_MODE')+'</p></details></div>';
}
function renderCandidates(rows){
 const pending=rows.filter(x=>x.status==='PENDING'),cases=new Map((getModel().investigation?.cases||[]).map(x=>[x.candidateId,x]));
 $('wa-candidates').innerHTML=pending.length?pending.slice(0,100).map(c=>{const inv=cases.get(c.id);return `<article class="event-row"><div><b>🔥 POSSÍVEL ${safe(c.boss)}</b><p>${dt(c.firstEvidenceAt)} · ${safe(c.messages||0)} mensagens · ${safe(c.participants||0)} participantes · score local de detecção ${safe(c.score||0)}/99</p><p>Investigação: ${safe(inv?.status||c.investigation?.status||'PENDING')} · recomendação ${safe(inv?.recommendation||'aguardando')} · Candidate Confidence ${inv?.calibratedConfidence==null?'INSUFFICIENT DATA':safe(inv.calibratedConfidence)+'%'}</p><details><summary>VER EVIDÊNCIAS DO GRUPO</summary>${(c.evidence||[]).map(x=>`<p><b>${safe(x.contextClassification)}</b> · ${dt(x.messageTimestamp)} · ${safe(x.bossCandidates?.[0]?.matchType||'—')} ${Math.round(100*(x.bossCandidates?.[0]?.similarity||0))}% · reporter ${safe(x.authorHash?.slice(0,8)||'não identificado')}<br>${safe(x.text)}</p>`).join('')}</details><details open><summary>DOSSIÊ DA INVESTIGAÇÃO</summary>${dossierHtml(inv)}</details></div><div class="group-buttons"><button class="primary" data-wa-action="confirm" data-id="${safe(c.id)}">CONFIRMAR</button><button class="secondary" data-wa-action="correct" data-id="${safe(c.id)}">CORRIGIR E CONFIRMAR</button><button class="secondary" data-wa-action="wait" data-id="${safe(c.id)}">AGUARDAR</button><button class="secondary" data-wa-action="reject" data-id="${safe(c.id)}">REJEITAR</button></div></article>`;}).join(''):'<p class="muted">Nenhum candidato aguardando sua confirmação.</p>';
}
async function handleCandidate(e){
 const b=e.target.closest('[data-wa-action]');if(!b)return;const id=b.dataset.id,action=b.dataset.waAction;
 try{
  if(action==='reject'){const reason=prompt('Motivo da rejeição (opcional):','Falso positivo / mensagem não confirma spawn')||'';await post('/api/whatsapp/candidate-reject',{id,reason});}
  if(action==='wait')await post('/api/investigation/wait',{id});
  if(action==='confirm')await post('/api/whatsapp/candidate-confirm',{id});
  if(action==='correct'){const c=(getModel().whatsapp?.candidates||[]).find(x=>x.id===id);if(!c)return;const local=new Date((c.estimatedAt||Date.now())-3*3600000).toISOString().slice(0,16),value=prompt('Horário correto em Brasília (AAAA-MM-DDTHH:MM):',local);if(!value)return;const at=Date.parse(value+':00-03:00');if(!Number.isFinite(at))throw new Error('Horário inválido');const boss=prompt('Boss confirmado:',c.boss)||c.boss;await post('/api/whatsapp/candidate-confirm',{id,at,boss});}
  await reload();
 }catch(err){notify(err.message);}
}
function renderIdentified(){const all=getModel().whatsapp?.identified||[],query=$('wa-boss-search').value.trim().toLowerCase(),rows=all.filter(r=>r.boss.toLowerCase().includes(query));$('wa-identified').innerHTML=`<p class="muted">${all.length} bosses identificados · ${rows.length} nesta busca</p>`+(rows.length?`<div class="table-wrap"><table class="ranking-table"><thead><tr><th>Boss</th><th>Estava</th><th>Não estava</th><th>Para revisar</th><th>Último relato</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${safe(r.boss)}</td><td>${r.found}</td><td>${r.empty}</td><td>${r.pending}</td><td>${r.lastAt?new Date(r.lastAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Data não reconhecida'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Nenhum boss reconhecido nesta busca. Verifique o grupo e o diagnóstico da leitura acima.</p>');}
