let getModel,post,reload,notify;
const $=id=>document.getElementById(id),safe=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function initWhatsAppUI(options){({getModel,post,reload,notify}=options);
 $('wa-boss-search').oninput=renderIdentified;
 $('wa-code-button').onclick=async()=>{try{const r=await post('/api/whatsapp/pair-code',{});$('wa-code').textContent=r.code;$('wa-code-wrap').hidden=false;notify('Código válido por 10 minutos. Cole somente na sua extensão.');}catch(e){notify(e.message);}};
 $('wa-copy').onclick=async()=>{try{await navigator.clipboard.writeText($('wa-code').textContent);notify('Código copiado.');}catch{notify('Selecione e copie o código exibido.');}};
 $('wa-disconnect').onclick=async()=>{try{await post('/api/whatsapp/disconnect',{});$('wa-code-wrap').hidden=true;await reload();notify('Extensão desconectada. Seu histórico foi mantido.');}catch(e){notify(e.message);}};
 $('wa-pending').onclick=async e=>{const b=e.target.closest('[data-wa-dismiss]');if(!b)return;try{await post('/api/whatsapp/dismiss',{id:b.dataset.waDismiss});await reload();}catch(e){notify(e.message);}};
}
export function renderWhatsAppUI(){const w=getModel().whatsapp||{};$('wa-status').textContent=w.connected?`${w.group} · ${w.world} · ${w.status}`:w.status||'Não conectado';$('wa-disconnect').hidden=!w.connected;$('wa-marker').textContent=w.checkpoint?`Última mensagem confirmada: ${new Date(w.checkpoint.at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}.`: 'O marcador será criado na primeira leitura. A primeira conexão começa pelas mensagens já carregadas.';
 renderIdentified();const d=w.diagnostics;$('wa-diagnostics').textContent=d?`Grupo detectado: ${d.detected||'não localizado'} · ${d.visible} mensagens carregadas · ${d.relevant} mensagens relacionadas a bosses · ${d.withoutDate} sem data reconhecida.`:'Após a próxima leitura, serão exibidos o grupo detectado e a quantidade de mensagens reconhecidas.';
 $('wa-images').innerHTML=(w.images||[]).slice(0,100).map(i=>`<figure><a href="${safe(i.url)}" target="_blank" rel="noreferrer"><img src="${safe(i.url)}" alt="Imagem do grupo: ${safe(i.bosses.join(', ')||'boss a identificar')}" loading="lazy"></a><figcaption><b>${safe(i.bosses.join(', ')||'Boss a identificar')}</b><small>${safe(i.world)} ${i.at?new Date(i.at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):''}</small></figcaption></figure>`).join('')||'<p class="muted">Nenhuma imagem importada ainda. Atualize a extensão para a versão 1.2 e faça uma leitura com as fotos carregadas no grupo.</p>';
 $('wa-pending').innerHTML=(w.pending||[]).slice(0,50).map(p=>`<div class="group-round"><div><b>${safe(p.bosses.join(', ')||'Checagem a revisar')}</b><p>${safe(p.date)} ${safe(p.time)} · ${safe(p.reason)} Registre o resultado confirmado na Rodada do grupo abaixo.</p></div><button class="secondary" data-wa-dismiss="${safe(p.id)}">Resolvido / ignorar</button></div>`).join('')||'<p class="muted">Nenhuma mensagem pendente de revisão.</p>';}
function renderIdentified(){const all=getModel().whatsapp?.identified||[],query=$('wa-boss-search').value.trim().toLowerCase(),rows=all.filter(r=>r.boss.toLowerCase().includes(query));$('wa-identified').innerHTML=`<p class="muted">${all.length} bosses identificados · ${rows.length} nesta busca</p>`+(rows.length?`<div class="table-wrap"><table class="ranking-table"><thead><tr><th>Boss</th><th>Estava</th><th>Não estava</th><th>Para revisar</th><th>Último relato</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${safe(r.boss)}</td><td>${r.found}</td><td>${r.empty}</td><td>${r.pending}</td><td>${r.lastAt?new Date(r.lastAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Data não reconhecida'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Nenhum boss reconhecido nesta busca. Verifique o grupo e o diagnóstico da leitura acima.</p>');}
