import {ensureOperational,appendOperationalEvent} from './operational-state.mjs';

const severe=s=>s==='critical';
const keyCounts=rows=>{const m=new Map();for(const x of rows){const k=String(x);m.set(k,(m.get(k)||0)+1);}return [...m.entries()].filter(([,n])=>n>1);};
export function auditIntegrity(state,at=Date.now()){
 ensureOperational(state);const issues=[],add=(severity,code,message,detail={})=>issues.push({severity,code,message,detail});
 const wa=state.whatsapp||{},community=wa.communityEvidence||[],candidates=wa.candidates||[],checks=state.groupChecks||[],intel=state.intelligence||{},events=intel.events||[],forecasts=intel.forecasts||[];
 for(const [id,n] of keyCounts(community.map(x=>x.id)))add('critical','DUPLICATE_COMMUNITY_EVIDENCE','Evidence duplicada no armazenamento do Lunarian.',{id,count:n});
 for(const [id,n] of keyCounts(candidates.map(x=>x.id)))add('critical','DUPLICATE_CANDIDATE','CandidateBossEvent duplicado.',{id,count:n});
 for(const [id,n] of keyCounts(events.map(x=>x.id)))add('critical','DUPLICATE_CANONICAL_EVENT','Boss event duplicado.',{id,count:n});
 for(const [id,n] of keyCounts(forecasts.map(x=>x.id)))add('high','DUPLICATE_FORECAST','Forecast duplicado.',{id,count:n});
 const evidenceIds=new Set(community.map(x=>x.id)),referencedEvidence=new Set(candidates.flatMap(c=>c.evidenceIds||[])),candidateIds=new Set(candidates.map(c=>c.id));
 for(const e of community)if(!referencedEvidence.has(e.id))add('high','ORPHAN_COMMUNITY_EVIDENCE','Community Evidence não está associada a nenhum Candidate.',{evidenceId:e.id,correlationId:e.correlationId||null});
 for(const check of checks){if(String(check.origin||'').startsWith('whatsapp')&&check.candidateId&&!candidateIds.has(check.candidateId))add('critical','WHATSAPP_CHECK_ORPHAN_CANDIDATE','Registro confirmado do WhatsApp referencia Candidate inexistente.',{checkId:check.id,candidateId:check.candidateId});}
 for(const item of state.operational?.outbox||[]){if(item.status!=='PENDING')continue;if(item.kind==='intelligence_ingest_checks'){const ids=(item.payload?.records||[]).map(x=>x.id),already=ids.length&&ids.every(id=>(events||[]).some(ev=>(ev.evidence||[]).some(e=>e.detail?.checkId===id||e.evidenceId===id)));if(already)add('medium','OUTBOX_EFFECT_ALREADY_PRESENT','Outbox ainda pendente apesar de o efeito parecer já existir; reprocessamento deve depender de idempotência.',{outboxId:item.id,kind:item.kind,recordIds:ids});}}
 for(const c of candidates){const refs=c.evidenceIds||[];if(!refs.length)add(c.status==='PENDING'?'high':'critical','CANDIDATE_WITHOUT_EVIDENCE','Candidate sem Evidence associada.',{candidateId:c.id,status:c.status});for(const id of refs)if(!evidenceIds.has(id))add('critical','CANDIDATE_ORPHAN_EVIDENCE','Candidate referencia Evidence inexistente.',{candidateId:c.id,evidenceId:id});if(c.status==='CONFIRMED'&&!checks.some(x=>x.candidateId===c.id))add('critical','CONFIRMED_CANDIDATE_WITHOUT_CHECK','Candidate confirmado sem registro persistido para ingestão.',{candidateId:c.id});}
 const seenEvidence=new Map();
 for(const e of events){if(!Array.isArray(e.evidence)||!e.evidence.length)add(/^confirmed_/.test(e.status)?'critical':'high','EVENT_WITHOUT_EVIDENCE','Evento sem evidências.',{eventId:e.id,status:e.status});if(Number.isFinite(e.startAt)&&Number.isFinite(e.endAt)&&e.endAt<e.startAt)add('critical','INVALID_EVENT_RANGE','Evento possui intervalo temporal invertido.',{eventId:e.id,startAt:e.startAt,endAt:e.endAt});if(Number.isFinite(e.estimatedAt)&&e.estimatedAt>at+5*60000)add('critical','FUTURE_EVENT','Evento possui horário futuro impossível.',{eventId:e.id,estimatedAt:e.estimatedAt});if(/^confirmed_/.test(e.status)&&['CONFLITANTE','SUSPEITO','DESCARTADO'].includes(e.qualityStatus))add('critical','CONFIRMED_EVENT_BAD_QUALITY','Evento confirmado está com qualidade incompatível.',{eventId:e.id,qualityStatus:e.qualityStatus});
  for(const ev of e.evidence||[]){if(seenEvidence.has(ev.evidenceId)&&seenEvidence.get(ev.evidenceId)!==e.id)add('critical','EVIDENCE_MULTIPLE_EVENTS','Mesma Evidence está associada a mais de um evento.',{evidenceId:ev.evidenceId,eventIds:[seenEvidence.get(ev.evidenceId),e.id]});else seenEvidence.set(ev.evidenceId,e.id);if(ev.processedAt&&ev.collectedAt&&ev.processedAt+5*60000<ev.collectedAt)add('high','TIMESTAMP_ORDER_INVALID','Evidence processada antes da coleta.',{evidenceId:ev.evidenceId,collectedAt:ev.collectedAt,processedAt:ev.processedAt});}
 }
 const datasetIssues=[];for(const ds of Object.values(intel.mlops?.datasets||{})){for(const e of ds.events||[]){const eligible=/^confirmed_/.test(e.status)&&!['CONFLITANTE','SUSPEITO','DESCARTADO'].includes(e.qualityStatus)&&e.eventType!=='absence'&&!e.anomaly&&(e.evidence||[]).some(x=>x.quality?.traceable&&x.quality?.eligibleForLearning!==false&&!x.anomaly&&['CONFIRMADO','PROVÁVEL'].includes(x.quality?.status));if(!eligible)datasetIssues.push({datasetId:ds.id,eventId:e.id,status:e.status,qualityStatus:e.qualityStatus});}}
 if(datasetIssues.length)add('critical','TRAINING_DATA_CONTAMINATION','Dataset imutável contém evento que não satisfaz TRAINING_ELIGIBLE.',{count:datasetIssues.length,samples:datasetIssues.slice(0,20)});
 for(const f of forecasts){const missing=[];if(!f.modelVersion)missing.push('modelVersion');if(!f.datasetVersion)missing.push('datasetVersion');if(!f.predictionEngineVersion)missing.push('predictionEngineVersion');if(!f.featureVersion)missing.push('featureVersion');if(!f.codeVersion)missing.push('codeVersion');if(missing.length)add('medium','FORECAST_VERSION_INCOMPLETE','Forecast sem versionamento operacional completo.',{forecastId:f.id,missing});}
 const ledger=intel.ledger||[];if(ledger.length){let previous='GENESIS';for(let i=0;i<ledger.length;i++){const row=ledger[i];if(row.previousHash!==previous){add('critical','INTELLIGENCE_LEDGER_BROKEN','Ledger da inteligência possui encadeamento inconsistente.',{index:i});break;}previous=row.hash;}}
 const criticalIssues=issues.filter(x=>severe(x.severity)).length,highIssues=issues.filter(x=>x.severity==='high').length,result={at,ok:criticalIssues===0,criticalIssues,highIssues,totalIssues:issues.length,issues:issues.slice(0,500),counts:{communityEvidence:community.length,candidates:candidates.length,groupChecks:checks.length,events:events.length,forecasts:forecasts.length,datasets:Object.keys(intel.mlops?.datasets||{}).length},trainingData:{contaminationCount:datasetIssues.length,eligibleOnly:datasetIssues.length===0}};
 state.operational.integrity={lastRunAt:at,lastResult:result};appendOperationalEvent(state,'DATA_INTEGRITY_AUDIT',{ok:result.ok,criticalIssues,highIssues,totalIssues:issues.length,counts:result.counts},{at,idempotencyKey:'integrity:'+Math.floor(at/300000)});return result;
}
export function safeRepair(state,audit,at=Date.now()){
 const actions=[];if(!audit)return actions;
 const dlq=state.pipelineDeadLetters||[],seen=new Set();for(const row of dlq){if(!row.id||seen.has(row.id)){row.status=row.status==='failed'?'duplicate_ignored':row.status;actions.push({kind:'DLQ_DUPLICATE_MARKED',id:row.id||null});}else seen.add(row.id);}
 if(actions.length)appendOperationalEvent(state,'SAFE_REPAIR',{actions},{at});return actions;
}
