const PRIORITY={CRITICAL:0,HIGH:1,NORMAL:2,LOW:3};
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
export class TaskQueue{
 constructor({concurrency=1,maxPending=50,deadLetters=[],onDeadLetter=async()=>{}}={}){if(!Number.isInteger(concurrency)||concurrency<1)throw new Error('Concorrência inválida');this.concurrency=concurrency;this.maxPending=maxPending;this.pending=[];this.running=0;this.completed=0;this.failed=0;this.lastStartedAt=0;this.lastCompletedAt=0;this.lastError='';this.deadLetters=deadLetters;this.onDeadLetter=onDeadLetter;this.active=new Map();this.sequence=0;this.inflightKeys=new Map();this.completedKeys=new Map();}
 enqueue(name,fn,{idempotent=false,maxAttempts=1,payload=null,priority='NORMAL',idempotencyKey='',correlationId=''}={}){
  if(this.pending.length>=this.maxPending)throw new Error('Fila de processamento cheia');if(maxAttempts>1&&!idempotent)throw new Error('Retry exige operação idempotente');if(!Number.isInteger(maxAttempts)||maxAttempts<1||maxAttempts>3)throw new Error('Limite de tentativas inválido');if(PRIORITY[priority]==null)throw new Error('Prioridade inválida');
  const key=String(idempotencyKey||'');if(key&&this.completedKeys.has(key))return Promise.resolve(this.completedKeys.get(key).value);if(key&&this.inflightKeys.has(key))return this.inflightKeys.get(key);
  const promise=new Promise((resolve,reject)=>{this.pending.push({id:++this.sequence,name,fn,resolve,reject,enqueuedAt:Date.now(),attempts:0,maxAttempts,payload,priority,idempotencyKey:key,correlationId:String(correlationId||'')});this.pending.sort((a,b)=>PRIORITY[a.priority]-PRIORITY[b.priority]||a.enqueuedAt-b.enqueuedAt||a.id-b.id);this.#drain();});
  if(key)this.inflightKeys.set(key,promise);return promise;
 }
 #drain(){while(this.running<this.concurrency&&this.pending.length){const job=this.pending.shift();this.running++;this.lastStartedAt=Date.now();this.active.set(job.id,{name:job.name,startedAt:this.lastStartedAt,enqueuedAt:job.enqueuedAt,priority:job.priority,correlationId:job.correlationId,idempotencyKey:job.idempotencyKey});this.#run(job).finally(()=>{this.running--;this.active.delete(job.id);if(job.idempotencyKey)this.inflightKeys.delete(job.idempotencyKey);this.#drain();});}}
 async #run(job){for(;job.attempts<job.maxAttempts;){job.attempts++;try{const v=await job.fn();this.completed++;this.lastCompletedAt=Date.now();if(job.idempotencyKey){this.completedKeys.set(job.idempotencyKey,{at:this.lastCompletedAt,value:v});if(this.completedKeys.size>10000){const oldest=[...this.completedKeys.entries()].sort((a,b)=>a[1].at-b[1].at).slice(0,this.completedKeys.size-10000);for(const [k] of oldest)this.completedKeys.delete(k);}}job.resolve(v);return;}catch(e){this.lastError=String(e?.message||e).slice(0,300);if(job.attempts===job.maxAttempts){this.failed++;this.lastCompletedAt=Date.now();this.deadLetters.push({id:String(this.lastCompletedAt)+'-'+job.id,name:job.name,payload:job.payload,error:this.lastError,stack:String(e?.stack||'').slice(0,4000),attempts:job.attempts,at:this.lastCompletedAt,origin:'task_queue',status:'failed',priority:job.priority,correlationId:job.correlationId,idempotencyKey:job.idempotencyKey});try{await this.onDeadLetter();}catch(writeError){this.lastError+='; persistência da fila: '+String(writeError?.message||writeError);}job.reject(e);return;}await sleep(Math.min(2000,250*Math.pow(2,job.attempts-1)));}}}
 stats(){const now=Date.now(),oldest=this.pending.length?Math.min(...this.pending.map(x=>x.enqueuedAt)):null;return {running:this.running,pending:this.pending.length,completed:this.completed,failed:this.failed,lastStartedAt:this.lastStartedAt,lastCompletedAt:this.lastCompletedAt,lastError:this.lastError,deadLetterCount:this.deadLetters.filter(x=>x.status==='failed').length,stalled:[...this.active.values()].filter(x=>now-x.startedAt>60000),pendingJobs:this.pending.map(x=>({name:x.name,enqueuedAt:x.enqueuedAt,priority:x.priority,correlationId:x.correlationId})),oldestPendingAgeMs:oldest==null?0:now-oldest,saturationPct:Math.round(1000*this.pending.length/Math.max(1,this.maxPending))/10,byPriority:Object.fromEntries(Object.keys(PRIORITY).map(p=>[p,this.pending.filter(x=>x.priority===p).length]))};}
}
