import {buildFeatures,availableAt,trustedEvent,digest} from './feature-store.mjs';
import {candidatePrediction,datasetSnapshot,qualityGate,metrics} from './models.mjs';
import {ensureMLOps} from './service.mjs';
import {predictAdaptive} from '../prediction/adaptive-engine.mjs';
import {calibrateConfidence} from '../learning/calibration.mjs';
export function temporalExperiment(intel,world,modelId,at=Date.now(),{boss=null,parameters={}}={}){
 const s=ensureMLOps(intel),allEvents=intel.events.filter(e=>e.world===world&&trustedEvent(e)&&availableAt(e)!=null&&availableAt(e)<=at).sort((a,b)=>a.estimatedAt-b.estimatedAt),events=allEvents.filter(e=>!boss||e.boss===boss),base=[],candidate=[],history=[],excluded=[];
 for(const actual of events){
 const previous=events.filter(e=>e.boss===actual.boss&&e.estimatedAt<actual.estimatedAt).at(-1);if(!previous)continue;
 const asOf=availableAt(previous);if(asOf>=actual.estimatedAt){excluded.push({eventId:actual.id,reason:'previous_event_not_available_before_target'});continue;}
 const f=buildFeatures(allEvents,actual.boss,world,asOf,{relatedBoss:modelId==='graph_context_interval'?parameters.sourceBoss||null:null,includeAnalog:modelId==='analog_state_interval'}),p=predictAdaptive(f.rows,actual.boss,world,{},asOf),start=performance.now(),c=candidatePrediction(modelId,f,parameters);if(p.status!=='ready'||!c||f.values.preciseSamples<5)continue;
 if(!(actual.evidence||[]).some(x=>['minute','hour'].includes(x.precision)&&x.quality?.traceable&&['CONFIRMADO','PROVÁVEL'].includes(x.quality?.status)))continue;
 const ds=datasetSnapshot(s.datasets,f,{experiment:modelId,boss:boss||null,parameters:structuredClone(parameters)}),pairId=actual.id,common={pairId,boss:actual.boss,world,asOf,datasetId:ds.id,resolvedAt:availableAt(actual),actualAt:actual.estimatedAt};
 const prior=history.filter(x=>x.resolvedAt<asOf),bCal=calibrateConfidence(p.confidence,prior.filter(x=>x.modelId==='adaptive_ensemble'),world,actual.boss),cCal=calibrateConfidence(p.confidence,prior.filter(x=>x.modelId===modelId),world,actual.boss);
 const b={...common,modelId:'adaptive_ensemble',errorMinutes:Math.abs(actual.estimatedAt-p.predictedCenterAt)/60000,windowHit:actual.estimatedAt>=p.windowStart&&actual.estimatedAt<=p.windowEnd,confidence:bCal.samples>=20?bCal.calibrated:null,confidenceRaw:p.confidence,latencyMs:0};
 const r={...common,modelId,errorMinutes:Math.abs(actual.estimatedAt-c.predictedAt)/60000,windowHit:actual.estimatedAt>=c.windowStart&&actual.estimatedAt<=c.windowEnd,confidence:cCal.samples>=20?cCal.calibrated:null,confidenceRaw:p.confidence,latencyMs:performance.now()-start};
 base.push(b);candidate.push(r);history.push(b,r);
 }
 const cut=Math.floor(candidate.length*.6),validationEnd=Math.floor(candidate.length*.8),developmentGate=qualityGate(base.slice(0,cut),candidate.slice(0,cut),{minSamples:20,temporalPassed:true,leakagePassed:true}),validation=qualityGate(base.slice(cut,validationEnd),candidate.slice(cut,validationEnd),{minSamples:20,temporalPassed:true,leakagePassed:true}),test=qualityGate(base.slice(validationEnd),candidate.slice(validationEnd),{minSamples:20,temporalPassed:true,leakagePassed:true});
 const pairs=candidate.map((x,i)=>({pairId:x.pairId,boss:x.boss,world:x.world,asOf:x.asOf,resolvedAt:x.resolvedAt,datasetId:x.datasetId,championErrorMinutes:base[i]?.errorMinutes??null,challengerErrorMinutes:x.errorMinutes,championWindowHit:!!base[i]?.windowHit,challengerWindowHit:!!x.windowHit,championConfidence:base[i]?.confidence??null,challengerConfidence:x.confidence??null,challengerLatencyMs:x.latencyMs??null,improvementMinutes:Number.isFinite(base[i]?.errorMinutes)&&Number.isFinite(x.errorMinutes)?base[i].errorMinutes-x.errorMinutes:null}));
 const result={id:'experiment_'+digest({world,modelId,boss,parameters,at,datasets:candidate.map(x=>x.datasetId)}),world,boss,modelId,parameters:structuredClone(parameters),at,samples:candidate.length,datasetIds:[...new Set(candidate.map(x=>x.datasetId))],excluded,development:metrics(candidate.slice(0,cut)),developmentComparison:developmentGate,validation,test,split:{development:[0,cut],validation:[cut,validationEnd],holdout:[validationEnd,candidate.length]},temporalPassed:candidate.length>=100&&validation.passed&&test.passed,leakagePassed:candidate.every(x=>{const ds=s.datasets[x.datasetId];return ds.events.every(e=>availableAt(e)<=x.asOf&&e.estimatedAt<=x.asOf)&&(ds.contextEvents||[]).every(e=>availableAt(e)<=x.asOf&&e.estimatedAt<=x.asOf)&&(ds.analogExamples||[]).every(a=>a.evaluatedAt<=x.asOf&&a.maxContextAvailableAt<=a.evaluatedAt&&a.outcomeAvailableAt<=x.asOf&&a.outcomeAt>a.evaluatedAt);}),rows:candidate,pairs};
 s.backtests.push(result);return result;
}
