(()=>{
 const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f\u200e\u200f\u202a-\u202e]/g,'').replace(/\s+/g,' ').trim().toLowerCase();
 const blocked=new Set(['dados do perfil','profile details','contact info','dados do contato','group info','dados do grupo','search','pesquisar','menu','mais opções','more options','online','digitando…','typing…']);
 function headerNames(doc){const header=doc.querySelector('#main header');if(!header)return [];
  const candidates=[...header.querySelectorAll('[data-testid="conversation-info-header-chat-title"],span[dir="auto"],span[title], [role="heading"]')];
  return [...new Set(candidates.filter(el=>!el.closest('[data-icon]')).map(el=>el.textContent?.trim()).filter(s=>s&&s.length<=150&&!blocked.has(norm(s))))];
 }
 function title(doc,expected){const candidates=headerNames(doc);return expected?candidates.find(s=>norm(s)===norm(expected))||'':candidates[0]||'';}
 function timestamp(meta){const m=String(meta||'').match(/\[(\d{1,2}):(\d{2})(?:\s*([AP]M))?,\s*(\d{1,2})[/.\-](\d{1,2})[/.\-](\d{2,4})\]/i);if(!m)return {date:'',time:'',at:null};let hour=+m[1];if(m[3])hour=hour%12+(/PM/i.test(m[3])?12:0);const year=m[6].length===2?'20'+m[6]:m[6],date=`${year}-${m[5].padStart(2,'0')}-${m[4].padStart(2,'0')}`,time=`${String(hour).padStart(2,'0')}:${m[2]}`;const at=Date.parse(date+'T'+time+':00-03:00');if(hour>23||+m[2]>59||!Number.isFinite(at)||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)return {date:'',time:'',at:null};return {date,time,at};}
 function messageNodes(doc){const main=doc.querySelector('#main');if(!main)return [];const nodes=[...main.querySelectorAll('[data-id]')].filter(el=>el.querySelector('[data-pre-plain-text],.selectable-text,[data-testid="image-thumb"],img[src^="blob:"]'));return nodes.length?nodes:[...main.querySelectorAll('[data-pre-plain-text]')];}
 function extractNode(el){const copy=el.matches('[data-pre-plain-text]')?el:el.querySelector('[data-pre-plain-text]');const meta=copy?.getAttribute('data-pre-plain-text')||'';const texts=[...el.querySelectorAll('.selectable-text')].filter(e=>!e.parentElement?.closest('.selectable-text')).map(e=>e.innerText||e.textContent||'');let text=texts.join('\n').trim();if(!text&&copy)text=(copy.innerText||copy.textContent||'').trim();const media=[...el.querySelectorAll('img')].some(img=>(img.width>80&&img.height>60)||img.closest('[data-testid="image-thumb"]'));if(media&&!texts.length)text='[Foto sem nome de boss]';return {text:text.slice(0,6000),media,nativeId:el.getAttribute('data-id')||el.closest('[data-id]')?.getAttribute('data-id')||'',author:author(meta),...timestamp(meta)};}
 function health(doc){const app=!!doc.querySelector('#app'),main=doc.querySelector('#main'),header=!!main?.querySelector('header'),messages=main?messageNodes(doc).length:0;return {app,main:!!main,header,messages,ok:app&&!!main&&header};}\n function groupIdentity(doc,expected){const main=doc.querySelector('#main'),header=main?.querySelector('header');for(const el of [main,header])for(const key of ['data-chat-id','data-jid','data-id']){const v=el?.getAttribute?.(key);if(v&&/@g\.us$/i.test(v))return v;}return title(doc,expected);}\n globalThis.BossWhatsAppAdapter={norm,blocked,headerNames,title,timestamp,messageNodes,extractNode,health,groupIdentity};
})();
