import {eventsAsOf} from './canonical-events.mjs';
import {mean,adjustFDR} from './statistics.mjs';

const H=3600000,DAY=24*H;
const round=(n,d=4)=>Number.isFinite(n)?Math.round(n*10**d)/10**d:null;
const quantile=(a,q)=>{if(!a.length)return null;const x=[...a].sort((m,n)=>m-n),p=(x.length-1)*q,i=Math.floor(p),f=p-i;return x[i]+(x[Math.min(i+1,x.length-1)]-x[i])*f;};
function localHour(at){const p=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date(at)).map(x=>[x.type,x.value]));return (Number(p.hour)%24)+Number(p.minute)/60;}
function latestSchedule(d,world,at){return (d.serverSaveSchedules||[]).filter(x=>x.world===world&&Number.isFinite(x.knownAt)&&x.knownAt<=at&&Number.isFinite(x.validFrom)&&x.validFrom<=at&&Number.isFinite(Number(x.hour))).sort((a,b)=>b.validFrom-a.validFrom)[0]||null;}
function continuousCoverage(d,boss,world,start,end,asOf){
 const rows=(d.coverage||[]).filter(x=>!x.candidateId&&x.boss===boss&&x.world===world&&x.verified&&x.continuous!==false&&Number.isFinite(x.knownAt)&&x.knownAt<=asOf&&x.endAt>start&&x.startAt<end).sort((a,b)=>a.startAt-b.startAt);let through=start;
 for(const x of rows){if(x.startAt>through)break;through=Math.max(through,x.endAt);if(through>=end)return true;}return false;
}
function exactEvents(events,boss){return events.filter(x=>x.boss===boss&&x.spawn?.lower===x.spawn?.upper&&Number.isFinite(x.spawn?.estimate));}
function outcome(events,boss,start,end){return exactEvents(events,boss).some(x=>x.spawn.estimate>start&&x.spawn.estimate<=end);}
function preState(events,d,world,at,sourceBoss,targetBoss){
 const known=events.filter(x=>x.spawn.estimate<at&&x.availableAt<=at),recent=h=>known.filter(x=>x.spawn.estimate>=at-h*H),last=known.at(-1),source=known.filter(x=>x.boss===sourceBoss).at(-1),target=known.filter(x=>x.boss===targetBoss).at(-1),save=latestSchedule(d,world,at),hour=localHour(at),regime=(d.regimeHistory||[]).filter(x=>x.world===world&&x.asOf<=at).sort((a,b)=>a.asOf-b.asOf).at(-1);
 return {bossesLast6h:recent(6).length,bossesLast12h:recent(12).length,bossesLast24h:recent(24).length,uniqueBossesLast24h:new Set(recent(24).map(x=>x.boss)).size,hoursSinceLastEvent:last?Math.min(240,(at-last.spawn.estimate)/H):240,hoursSinceSource:source?Math.min(720,(at-source.spawn.estimate)/H):720,hoursSinceTarget:target?Math.min(720,(at-target.spawn.estimate)/H):720,hoursSinceServerSave:save?((hour-Number(save.hour)+24)%24):12,hourSin:Math.sin(2*Math.PI*hour/24),hourCos:Math.cos(2*Math.PI*hour/24),regimeStatus:regime?.status||null};
}
const COVARS=['bossesLast6h','bossesLast12h','bossesLast24h','uniqueBossesLast24h','hoursSinceLastEvent','hoursSinceSource','hoursSinceTarget','hoursSinceServerSave','hourSin','hourCos'];
const SCALES={bossesLast6h:10,bossesLast12h:20,bossesLast24h:40,uniqueBossesLast24h:20,hoursSinceLastEvent:72,hoursSinceSource:240,hoursSinceTarget:240,hoursSinceServerSave:24,hourSin:1,hourCos:1};
function distance(a,b){let d=0;for(const key of COVARS)d+=((Number(a[key])-Number(b[key]))/(SCALES[key]||1))**2;d=Math.sqrt(d/COVARS.length);if(a.regimeStatus&&b.regimeStatus&&a.regimeStatus!==b.regimeStatus)d+=.2;return d;}
function pairedBinaryTest(pairs,keyA,keyB){
 const plus=pairs.filter(x=>x[keyA]===1&&x[keyB]===0).length,minus=pairs.filter(x=>x[keyA]===0&&x[keyB]===1).length,n=plus+minus;if(!n)return {p:1,discordant:0,plus,minus};
 const k=Math.min(plus,minus);let term=Math.exp(-n*Math.log(2)),tail=term;for(let i=0;i<k;i++){term*=((n-i)/(i+1));tail+=term;}return {p:Math.min(1,2*tail),discordant:n,plus,minus};
}
function effectCI(values){if(values.length<2)return null;const m=mean(values),sd=Math.sqrt(mean(values.map(x=>(x-m)**2))),se=sd/Math.sqrt(values.length);return [Math.max(-1,m-1.96*se),Math.min(1,m+1.96*se)];}
function smd(a,b,key){if(!a.length||!b.length)return null;const ma=mean(a.map(x=>Number(x[key]))),mb=mean(b.map(x=>Number(x[key]))),va=mean(a.map(x=>(Number(x[key])-ma)**2)),vb=mean(b.map(x=>(Number(x[key])-mb)**2)),sd=Math.sqrt((va+vb)/2);return sd>1e-9?(ma-mb)/sd:Math.abs(ma-mb)<1e-9?0:Number.POSITIVE_INFINITY;}
function coverageRange(d,sourceBoss,targetBoss,world,asOf){
 const rows=(d.coverage||[]).filter(x=>!x.candidateId&&x.world===world&&x.verified&&x.continuous!==false&&[sourceBoss,targetBoss].includes(x.boss)&&x.knownAt<=asOf);if(!rows.length)return null;return {start:Math.max(asOf-365*DAY,Math.min(...rows.map(x=>x.startAt))),end:Math.min(asOf,Math.max(...rows.map(x=>x.endAt)))};
}
function candidateControls(events,d,world,sourceBoss,targetBoss,fromHours,toHours,asOf,maxControls=1200){
 const range=coverageRange(d,sourceBoss,targetBoss,world,asOf);if(!range)return [];const out=[],step=6*H,sourceEvents=exactEvents(events,sourceBoss),prior=24*H,from=fromHours*H,to=toHours*H;
 for(let at=Math.ceil((range.start+Math.max(prior,to))/step)*step;at<=range.end-to&&at<=asOf-to;at+=step){if(!continuousCoverage(d,sourceBoss,world,at-prior,at+H,asOf)||!continuousCoverage(d,targetBoss,world,at-to,at+to,asOf))continue;if(sourceEvents.some(x=>Math.abs(x.spawn.estimate-at)<=H))continue;out.push({at,state:preState(events,d,world,at,sourceBoss,targetBoss),outcome:outcome(events,targetBoss,at+from,at+to)?1:0,preOutcome:outcome(events,targetBoss,at-to,at-from)?1:0});if(out.length>=maxControls)break;}
 return out;
}
function treatmentRows(events,d,world,sourceBoss,targetBoss,fromHours,toHours,asOf,maxTreatments=100){
 const from=fromHours*H,to=toHours*H,prior=24*H;return exactEvents(events,sourceBoss).filter(x=>x.availableAt<=asOf&&x.spawn.estimate+to<=asOf&&continuousCoverage(d,targetBoss,world,x.spawn.estimate-to,x.spawn.estimate+to,asOf)&&continuousCoverage(d,sourceBoss,world,x.spawn.estimate-prior,x.spawn.estimate+H,asOf)).slice(-maxTreatments).map(x=>({eventId:x.id,at:x.spawn.estimate,state:preState(events,d,world,x.spawn.estimate,sourceBoss,targetBoss),outcome:outcome(events,targetBoss,x.spawn.estimate+from,x.spawn.estimate+to)?1:0,preOutcome:outcome(events,targetBoss,x.spawn.estimate-to,x.spawn.estimate-from)?1:0}));
}
function matchRows(treated,controls,toHours,caliper=.35){
 const used=new Set(),pairs=[];for(const t of treated){let best=null;for(let i=0;i<controls.length;i++){if(used.has(i)||Math.abs(controls[i].at-t.at)<2*toHours*H)continue;const d=distance(t.state,controls[i].state);if(d<=caliper&&(!best||d<best.distance))best={i,row:controls[i],distance:d};}if(!best)continue;used.add(best.i);pairs.push({treatmentEventId:t.eventId,treatmentAt:t.at,controlAt:best.row.at,treatmentOutcome:t.outcome,controlOutcome:best.row.outcome,treatmentPreOutcome:t.preOutcome,controlPreOutcome:best.row.preOutcome,distance:best.distance,treatmentState:t.state,controlState:best.row.state});}return pairs;
}
function stability(pairs){
 if(pairs.length<20)return {passed:false,reason:'insufficient_pairs'};const sorted=[...pairs].sort((a,b)=>a.treatmentAt-b.treatmentAt),cut=Math.floor(sorted.length/2),a=sorted.slice(0,cut),b=sorted.slice(cut),ea=mean(a.map(x=>x.treatmentOutcome-x.controlOutcome)),eb=mean(b.map(x=>x.treatmentOutcome-x.controlOutcome)),same=ea===0||eb===0?Math.abs(ea-eb)<=.1:Math.sign(ea)===Math.sign(eb);return {passed:a.length>=8&&b.length>=8&&same&&Math.abs(ea-eb)<=.25,earlyEffect:round(ea),lateEffect:round(eb),earlySamples:a.length,lateSamples:b.length};
}
function evaluateRelation(intel,world,asOf,relation,config={}){
 const d=intel.discovery,events=eventsAsOf(d,world,asOf),sourceBoss=relation.sourceEntity?.id,targetBoss=relation.targetEntity?.id,fromHours=Math.max(0,Number(relation.window?.fromHours)||0),toHours=Math.min(48,Number(relation.window?.toHours)||0),treated=treatmentRows(events,d,world,sourceBoss,targetBoss,fromHours,toHours,asOf,config.maxTreatments||100),controls=candidateControls(events,d,world,sourceBoss,targetBoss,fromHours,toHours,asOf,config.maxControls||1200),pairs=matchRows(treated,controls,toHours,config.caliper||.35);
 const treatedRisk=mean(pairs.map(x=>x.treatmentOutcome)),controlRisk=mean(pairs.map(x=>x.controlOutcome)),effect=treatedRisk==null||controlRisk==null?null:treatedRisk-controlRisk,rr=controlRisk>0?treatedRisk/controlRisk:null,paired=pairedBinaryTest(pairs,'treatmentOutcome','controlOutcome'),placebo=pairedBinaryTest(pairs,'treatmentPreOutcome','controlPreOutcome'),placeboEffect=mean(pairs.map(x=>x.treatmentPreOutcome-x.controlPreOutcome)),balance=Object.fromEntries(COVARS.map(k=>[k,round(smd(pairs.map(x=>x.treatmentState),pairs.map(x=>x.controlState),k),3)])),maxAbsSmd=Math.max(0,...Object.values(balance).filter(Number.isFinite).map(Math.abs)),stable=stability(pairs);
 return {id:'CAUSAL-'+relation.id,relationshipId:relation.id,world,sourceBoss,targetBoss,window:{fromHours,toHours},analysisAsOf:asOf,treatedEligible:treated.length,controlPool:controls.length,matchedPairs:pairs.length,matchRate:treated.length?pairs.length/treated.length:0,caliper:config.caliper||.35,treatedRisk,matchedControlRisk:controlRisk,averageTreatmentEffectOnTreated:effect,riskRatio:rr,effectCi95:effectCI(pairs.map(x=>x.treatmentOutcome-x.controlOutcome)),causalTest:paired,placeboTest:placebo,placeboEffect,balance:{covariates:balance,maxAbsSmd},stability:stable,lineage:{pairs:pairs.slice(0,200).map(x=>({treatmentEventId:x.treatmentEventId,treatmentAt:x.treatmentAt,controlAt:x.controlAt,distance:round(x.distance,4),treatmentOutcome:x.treatmentOutcome,controlOutcome:x.controlOutcome,treatmentPreOutcome:x.treatmentPreOutcome,controlPreOutcome:x.controlPreOutcome}))},identificationAssumptions:{temporalOrder:true,preTreatmentCovariatesOnly:true,measuredBalanceChecked:true,unmeasuredConfoundingResolved:false,noInterferenceVerified:false},causalityProven:false,productionEligible:false,aiLabPromotionEligible:false};
}
export function causalDiscoveryLab(intel,world,asOf=Date.now(),{relationships=null,maxRelations=12,caliper=.35}={}){
 const all=relationships||Object.values(intel.discovery?.temporalKnowledge?.relationshipRegistry||{}),eligible=all.filter(r=>r.world===world&&r.sourceEntity?.id&&r.targetEntity?.id&&r.sourceEntity.id!==r.targetEntity.id&&Number(r.metrics?.sampleSize)>=30&&r.metrics?.direction==='POSITIVE'&&Number(r.metrics?.adjustedSignificance)<=.1&&Number(r.window?.toHours)>0&&Number(r.window?.toHours)<=48&&!['REJECTED','ARCHIVED'].includes(r.status)).sort((a,b)=>(b.metrics?.qualityScore||0)-(a.metrics?.qualityScore||0)).slice(0,maxRelations),rows=eligible.map(r=>evaluateRelation(intel,world,asOf,r,{caliper})),main=rows.map(row=>({test:row.causalTest,row})),placebos=rows.map(row=>({test:row.placeboTest,row}));
 adjustFDR(main,'test','BY');adjustFDR(placebos,'test','BY');for(let i=0;i<rows.length;i++){rows[i].causalTest.q=main[i].test.q;rows[i].placeboTest.q=placebos[i].test.q;const x=rows[i],enough=x.matchedPairs>=20&&x.matchRate>=.6,balanced=x.balance.maxAbsSmd<=.25,material=Number.isFinite(x.averageTreatmentEffectOnTreated)&&Math.abs(x.averageTreatmentEffectOnTreated)>=.1,significant=x.causalTest.q<=.05,placeboMagnitude=Math.abs(x.placeboEffect||0),placeboPass=placeboMagnitude<=Math.max(.08,Math.abs(x.averageTreatmentEffectOnTreated||0)*.5)&&x.placeboTest.q>.05,stable=x.stability.passed;
  x.gates={sample:enough,balance:balanced,materialEffect:material,adjustedSignificance:significant,reverseTimePlacebo:placeboPass,temporalStability:stable,unmeasuredConfoundingResolved:false};
  x.status=!enough?'INSUFFICIENT_DATA':!balanced?'INCONCLUSIVE_BALANCE':!placeboPass?'REJECTED_PLACEBO':!stable?'INCONCLUSIVE_STABILITY':significant&&material?'CAUSAL_CANDIDATE':'REJECTED_NO_EFFECT';x.evidenceLevel=x.status==='CAUSAL_CANDIDATE'?'MATCHED_OBSERVATIONAL_WITH_PLACEBO':'OBSERVATIONAL_SCREENING';x.note=x.status==='CAUSAL_CANDIDATE'?'Compatível com hipótese causal sob matching e placebos, mas causalidade NÃO está provada; confundimento não medido continua possível.':'Não existe evidência suficiente para interpretação causal.';}
 return {version:1,world,asOf,status:rows.length?'MEASURED':'INSUFFICIENT_DATA',testedRelationships:rows.length,numberOfTests:rows.length,falseDiscoveryMethod:'Benjamini-Yekutieli',method:'temporal_nearest_neighbor_matching_with_reverse_time_placebo',results:rows,policy:{maxRelations,caliper,minPairs:20,minMatchRate:.6,maxAbsSmd:.25,minAbsoluteEffect:.1,autoPromotion:false,causalityProvenRequires:'randomized_or_strong_identification_design'},limitations:['Matching controla somente covariáveis observadas.','Confundimento não medido permanece possível.','Placebo reverso reduz falsas descobertas, mas não prova causalidade.','Nenhum resultado altera Prediction Engine, Source Intelligence ou AI Lab automaticamente.']};
}
