import https from 'node:https';
import {lookup} from 'node:dns/promises';
import {isIP} from 'node:net';
import {digest} from '../mlops/feature-store.mjs';
const PUBLIC_ROOTS=['rubinot.com.br','rubinot.app','www.rubinottools.com'];
export function isPublicAddress(ip){
 if(isIP(ip)===4){const [a,b]=ip.split('.').map(Number);return !(a===0||a===10||a===127||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&(b===168||b===0)||a===100&&b>=64&&b<=127||a>=224||a===198&&(b===18||b===19));}
 if(isIP(ip)===6){const s=ip.toLowerCase();return !s.startsWith('::')&&!s.startsWith('fc')&&!s.startsWith('fd')&&!/^fe[89ab]/.test(s)&&!s.startsWith('ff')&&!s.startsWith('2001:db8:');}return false;
}
export function publicURL(value,approvedHosts){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.port||!approvedHosts.includes(u.hostname)||isIP(u.hostname)||u.href.length>1000)throw new Error('Origem pública não autorizada');return u;}
export async function readPublic(url,{approvedHosts=PUBLIC_ROOTS,maxBytes=2*1024*1024,timeoutMs=12000,resolver=lookup}={}){
 const u=publicURL(url,approvedHosts),addresses=await resolver(u.hostname,{all:true,verbatim:true});if(!addresses.length||addresses.some(a=>!isPublicAddress(a.address)))throw new Error('Endereço de rede não público');const chosen=addresses[0];
 return new Promise((resolve,reject)=>{const req=https.get(u,{headers:{'User-Agent':'BossRadarResearch/1.0 (+public-data-only)','Accept':'text/html,application/json,application/rss+xml,application/atom+xml,text/plain'},lookup:(host,options,callback)=>options?.all?callback(null,[chosen]):callback(null,chosen.address,chosen.family)},res=>{let length=0;const chunks=[];res.on('data',c=>{length+=c.length;if(length>maxBytes){req.destroy(new Error('Documento excedeu limite'));return;}chunks.push(c);});res.on('end',()=>{if(res.statusCode>=300&&res.statusCode<400){reject(new Error('Redirecionamento exige revisão da origem'));return;}resolve({status:res.statusCode,body:Buffer.concat(chunks).toString('utf8'),contentType:String(res.headers['content-type']||''),url:u.href});});res.on('error',reject);});req.setTimeout(timeoutMs,()=>req.destroy(new Error('Tempo de consulta excedido')));req.on('error',reject);});
}
export function robotsAllowed(text,path,userAgent='bossradarresearch'){
 const groups=[];let group={agents:[],rules:[]};for(const raw of text.split(/\r?\n/)){const line=raw.split('#')[0].trim(),match=line.match(/^([a-z-]+)\s*:\s*(.*)$/i);if(!match)continue;const key=match[1].toLowerCase(),value=match[2].trim();if(key==='user-agent'){if(group.rules.length){groups.push(group);group={agents:[],rules:[]};}group.agents.push(value.toLowerCase());}else if(['allow','disallow'].includes(key)&&value)group.rules.push({allow:key==='allow',path:value});}groups.push(group);
 const specific=groups.filter(g=>g.agents.some(a=>a!=='*'&&userAgent.includes(a))),selected=specific.length?specific:groups.filter(g=>g.agents.includes('*')),matches=[];
 for(const g of selected)for(const r of g.rules){const escaped=r.path.replace(/[.+?^{}()|[\]\\]/g,'\\$&').replace(/\*/g,'.*'),pattern='^'+escaped.replace(/\$$/,'$');if(new RegExp(pattern).test(path))matches.push(r);}
 matches.sort((a,b)=>b.path.length-a.path.length||Number(b.allow)-Number(a.allow));return matches.length?matches[0].allow:true;
}
const plain=text=>String(text).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
export function discoverLinks(html,base){const origin=new URL(base),links=[];for(const m of html.matchAll(/href=["']([^"']{1,1000})["']/gi)){try{const u=new URL(m[1],origin);u.hash='';if(u.protocol==='https:'&&!u.username&&!u.password&&!isIP(u.hostname)&&/boss|news|changelog|event|serverinfo|status|ranking|guild|forum|feed|api|killstat/i.test(u.href)&&!/_next|\.(?:js|css|png|gif|svg|woff)/i.test(u.pathname)&&!links.includes(u.href))links.push(u.href);}catch{}}return links.slice(0,30);}
export function parsePublications(html,sourceRef,collectedAt){
 const clean=html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,''),rows=[];const months={jan:1,fev:2,mar:3,abr:4,mai:5,jun:6,jul:7,ago:8,set:9,out:10,nov:11,dez:12};
 const pieces=[...clean.matchAll(/<tr\b[^>]*>([\s\S]{0,20000}?)<\/tr>/gi)].map(m=>m[1]);if(!pieces.length)pieces.push(...[...clean.matchAll(/<(?:article|item|entry)\b[^>]*>([\s\S]{0,20000}?)<\/(?:article|item|entry)>/gi)].map(m=>m[1]));
 for(const piece of pieces.slice(0,100)){const text=plain(piece),date=text.match(/(\d{1,2}) de ([a-z]{3})\.? de (\d{4})/i),iso=piece.match(/(?:datetime=["']|<pubDate>|<published>|<updated>)([^"'<]+)/i);let publishedAt=null,publishedLower=null,publishedUpper=null;
  if(iso){const value=Date.parse(iso[1]);if(Number.isFinite(value)&&value<=collectedAt&&/Z|[+-]\d\d:?\d\d|GMT/.test(iso[1]))publishedAt=value;}
  if(date&&months[date[2].toLowerCase()]){const day=date[3]+'-'+String(months[date[2].toLowerCase()]).padStart(2,'0')+'-'+date[1].padStart(2,'0');publishedLower=Date.parse(day+'T00:00:00-03:00');publishedUpper=publishedLower+86400000-1;if(publishedLower>collectedAt)continue;}
  if(!publishedAt&&!publishedLower)continue;const title=text.slice(0,160),category=/manuten|maintenance/i.test(text)?'maintenance_announcement':/hotfix/i.test(text)?'hotfix_announcement':/update|atualiza|melhoria|changelog/i.test(text)?'update_announcement':/evento|event/i.test(text)?'event_announcement':'public_information';
  rows.push({id:'PUB-'+digest({sourceRef,text,publishedAt,publishedLower}).slice(0,24),sourceRef,title,text:text.slice(0,800),category,publishedAt,publishedLower,publishedUpper,collectedAt,availableAt:collectedAt,payloadHash:digest(text),verifiedExecution:false,mode:'shadow'});
 }return rows;
}
export function parseBossJSON(body,collectedAt){const data=JSON.parse(body),rows=Array.isArray(data)?data:data.events;if(!Array.isArray(rows)||rows.length>1000)throw new Error('Feed requer coleção explícita de eventos');return rows.filter(r=>r.eventType==='appearance'&&typeof r.boss==='string'&&typeof r.world==='string'&&Number.isFinite(r.spawn?.lower)&&Number.isFinite(r.spawn?.upper)&&r.spawn.lower>0&&r.spawn.lower<=r.spawn.upper&&r.spawn.upper<=r.detectedAt&&Number.isFinite(r.detectedAt)&&r.detectedAt<=collectedAt).map(r=>({boss:r.boss,world:r.world,spawnLower:r.spawn.lower,spawnUpper:r.spawn.upper,detectedAt:r.detectedAt,publishedAt:Number.isFinite(r.publishedAt)&&r.publishedAt<=collectedAt?r.publishedAt:null,payloadHash:digest(r)}));}
export async function collectPublicSources(d,{request=readPublic,register,sample,at=Date.now(),limit=6,clock=Date.now}={}){
 d.publications||=[];d.collectionRuns||=[];d.collectorPolicy||={approvedHosts:[...PUBLIC_ROOTS],maxPagesPerRun:6};const policy=d.collectorPolicy,selected=d.candidates.filter(c=>!['BLOQUEADA','DESCARTADA'].includes(c.status)&&policy.approvedHosts.includes(new URL(c.url).hostname)).slice(0,Math.min(limit,policy.maxPagesPerRun)),results=[],robots=new Map();
 for(const c of selected){try{const u=publicURL(c.url,policy.approvedHosts);if(!robots.has(u.origin)){const r=await request(u.origin+'/robots.txt',{approvedHosts:policy.approvedHosts,maxBytes:100000});if(r.status!==200&&r.status!==404)throw new Error('Regras de acesso indisponíveis');robots.set(u.origin,r.status===404?'':r.body);}
   const delay=Math.max(1,...[...robots.get(u.origin).matchAll(/crawl-delay:\s*(\d+(?:\.\d+)?)/gi)].map(m=>Number(m[1])));if(clock()-(policy.lastRequests?.[u.origin]||0)<delay*1000)throw new Error('Aguardar intervalo de coleta da origem');policy.lastRequests||={};policy.lastRequests[u.origin]=clock();
   if(!robotsAllowed(robots.get(u.origin),u.pathname+u.search)){c.status='BLOQUEADA';throw new Error('robots.txt impede coleta');}const r=await request(c.url,{approvedHosts:policy.approvedHosts});if(r.status!==200)throw new Error('Consulta pública recusada: HTTP '+r.status);if(/captcha|cf-chl-|verify you are human/i.test(r.body.slice(0,20000)))throw new Error('Proteção de acesso detectada; nenhuma tentativa de contorno');
   const receivedAt=Math.max(at,clock());const links=discoverLinks(r.body,c.url);for(const url of links){if(d.candidates.length>=100)break;try{register(d,{name:new URL(url).hostname+new URL(url).pathname,url},receivedAt);}catch{}}
   const publications=parsePublications(r.body,c.url,receivedAt);for(const p of publications)if(!d.publications.some(x=>x.id===p.id))d.publications.push({...p,sourceId:c.id});
   let samples=0;if(c.collector==='public_boss_json'&&r.contentType.includes('json')){for(const row of parseBossJSON(r.body,receivedAt)){sample(d,{...row,sourceId:c.id},receivedAt);samples++;}}
   c.lastCollectedAt=receivedAt;c.lastCollectionError=null;c.accessVerifiedAt=receivedAt;results.push({sourceId:c.id,status:'collected',publications:publications.length,samples,discovered:links.length});
  }catch(e){c.lastCollectionError=String(e.message).slice(0,200);results.push({sourceId:c.id,status:'blocked_or_unavailable',reason:c.lastCollectionError});}}
 const run={id:'COL-'+digest({at,results}).slice(0,20),at,results};d.collectionRuns.push(run);return run;
}
export function configureCollector(d,input,at=Date.now()){const c=d.candidates.find(c=>c.id===input.sourceId);if(!c||!['public_page','public_boss_json'].includes(input.collector)||input.publicAccessApproved!==true)throw new Error('Coletor exige fonte cadastrada e revisão do acesso público');const host=new URL(c.url).hostname;publicURL(c.url,[host]);d.collectorPolicy||={approvedHosts:[...PUBLIC_ROOTS],maxPagesPerRun:6};if(!d.collectorPolicy.approvedHosts.includes(host))d.collectorPolicy.approvedHosts.push(host);c.collector=input.collector;c.accessApprovedAt=at;return {id:c.id,collector:c.collector,mode:'shadow'};}
export async function collectAuthorizedDiscord(config,{fetcher=fetch,token=process.env.BOSS_RADAR_DISCORD_TOKEN,at=Date.now()}={}){
 if(config.after&&!/^\d{16,22}$/.test(config.after))throw new Error('Cursor de mensagens inválido');
 if(config.authorized!==true||!/^\d{16,22}$/.test(config.channelId)||!token)throw new Error('Discord requer bot autorizado, canal permitido e token no ambiente');const response=await fetcher('https://discord.com/api/v10/channels/'+config.channelId+'/messages?limit=50'+(config.after?'&after='+encodeURIComponent(config.after):''),{headers:{Authorization:'Bot '+token},signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error('Discord recusou leitura: HTTP '+response.status);const rows=await response.json();if(!Array.isArray(rows))throw new Error('Resposta de mensagens inválida');return rows.map(m=>({id:String(m.id),sourceRef:'discord://authorized-channel/'+config.channelId,publishedAt:Date.parse(m.timestamp),collectedAt:Math.max(at,Date.now()),content:String(m.content||'').slice(0,3000)}));
}
