import {digest} from '../mlops/feature-store.mjs';
import {eventsAsOf} from './canonical-events.mjs';
export function knowledgeGraph(intel,world,asOf=Date.now(),{offset=0,limit=1000}={}){
 const d=intel.discovery,nodes=new Map(),edges=[],node=(type,key,payload={})=>{const id=type+':'+digest(key).slice(0,20);if(!nodes.has(id))nodes.set(id,{id,type,key,...payload});return id;},edge=(from,to,type)=>edges.push({id:digest({from,to,type}),from,to,type});const server=node('server',world);
 for(const e of eventsAsOf(d,world,asOf)){const boss=node('boss',world+'|'+e.boss,{name:e.boss}),spawn=node('spawn',e.id,{spawn:e.spawn,availableAt:e.availableAt});edge(boss,server,'belongs_to');edge(spawn,boss,'appearance_of');for(const s of e.evidence){const source=node('source',s.sourceId);edge(source,spawn,'reports');const confirmation=node('confirmation',s.id||digest(s),{collectedAt:s.collectedAt,publishedAt:s.publishedAt});edge(confirmation,spawn,'supports');edge(confirmation,source,'originates_from');}}
 for(const c of d.context.filter(c=>c.world===world&&c.knownAt<=asOf)){const context=node(c.type,c.id,{startAt:c.startAt,knownAt:c.knownAt});edge(context,server,'affects_context_of');edge(node('source',c.sourceRef),context,'reports');}
 for(const p of (d.publications||[]).filter(p=>p.availableAt<=asOf)){const publication=node('publication',p.id,{title:p.title,availableAt:p.availableAt});edge(node('source',p.sourceId||p.sourceRef),publication,'publishes');edge(publication,server,'candidate_context_for');}
 for(const r of (intel.mlops?.runs||[]).filter(r=>r.world===world&&r.asOf<=asOf)){const prediction=node('prediction',r.identity+'|'+r.modelId,{issuedAt:r.asOf}),model=node('model',r.modelId+'|'+r.modelVersion),boss=node('boss',world+'|'+r.boss,{name:r.boss});edge(model,prediction,'produces');edge(prediction,boss,'forecasts');edge(node('dataset',r.datasetId),prediction,'input_to');}
 const all=[...nodes.values()],selected=all.slice(Math.max(0,offset),Math.max(0,offset)+Math.min(5000,Math.max(1,limit))),ids=new Set(selected.map(n=>n.id));return {world,asOf,nodes:selected,edges:edges.filter(e=>ids.has(e.from)&&ids.has(e.to)),totalNodes:all.length,totalEdges:edges.length,offset,nextOffset:offset+selected.length<all.length?offset+selected.length:null,inference:'typed provenance only; relations do not imply causality'};
}
